// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account_media_users.sql

package sqlite

import (
	"context"
)

const createAccountMediaUserIfAbsent = `-- name: CreateAccountMediaUserIfAbsent :execrows
INSERT INTO account_media_users (
    account_id, media_server_id, media_user_id, username, source, created_at, updated_at
) VALUES (
    ?1, ?2, ?3,
    ?4, ?5, ?6, ?7
)
ON CONFLICT DO NOTHING
`

type CreateAccountMediaUserIfAbsentParams struct {
	AccountID     string
	MediaServerID string
	MediaUserID   string
	Username      string
	Source        string
	CreatedAt     string
	UpdatedAt     string
}

func (q *Queries) CreateAccountMediaUserIfAbsent(ctx context.Context, arg CreateAccountMediaUserIfAbsentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createAccountMediaUserIfAbsent,
		arg.AccountID,
		arg.MediaServerID,
		arg.MediaUserID,
		arg.Username,
		arg.Source,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteAccountMediaUser = `-- name: DeleteAccountMediaUser :execrows
DELETE FROM account_media_users
WHERE account_id = ?1
  AND media_server_id = ?2
`

type DeleteAccountMediaUserParams struct {
	AccountID     string
	MediaServerID string
}

func (q *Queries) DeleteAccountMediaUser(ctx context.Context, arg DeleteAccountMediaUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAccountMediaUser, arg.AccountID, arg.MediaServerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAccountMediaUser = `-- name: GetAccountMediaUser :one
SELECT amu.account_id, amu.media_server_id, ms.name AS media_server_name,
       amu.media_user_id, amu.username, amu.source, amu.created_at, amu.updated_at
FROM account_media_users AS amu
JOIN media_servers AS ms ON ms.id = amu.media_server_id
WHERE amu.account_id = ?1
  AND amu.media_server_id = ?2
`

type GetAccountMediaUserParams struct {
	AccountID     string
	MediaServerID string
}

type GetAccountMediaUserRow struct {
	AccountID       string
	MediaServerID   string
	MediaServerName string
	MediaUserID     string
	Username        string
	Source          string
	CreatedAt       string
	UpdatedAt       string
}

func (q *Queries) GetAccountMediaUser(ctx context.Context, arg GetAccountMediaUserParams) (GetAccountMediaUserRow, error) {
	row := q.db.QueryRowContext(ctx, getAccountMediaUser, arg.AccountID, arg.MediaServerID)
	var i GetAccountMediaUserRow
	err := row.Scan(
		&i.AccountID,
		&i.MediaServerID,
		&i.MediaServerName,
		&i.MediaUserID,
		&i.Username,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccountMediaUsers = `-- name: ListAccountMediaUsers :many
SELECT amu.account_id, amu.media_server_id, ms.name AS media_server_name,
       amu.media_user_id, amu.username, amu.source, amu.created_at, amu.updated_at
FROM account_media_users AS amu
JOIN media_servers AS ms ON ms.id = amu.media_server_id
WHERE amu.account_id = ?1
ORDER BY ms.name_key, amu.media_server_id
LIMIT ?2
`

type ListAccountMediaUsersParams struct {
	AccountID string
	PageSize  int64
}

type ListAccountMediaUsersRow struct {
	AccountID       string
	MediaServerID   string
	MediaServerName string
	MediaUserID     string
	Username        string
	Source          string
	CreatedAt       string
	UpdatedAt       string
}

func (q *Queries) ListAccountMediaUsers(ctx context.Context, arg ListAccountMediaUsersParams) ([]ListAccountMediaUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listAccountMediaUsers, arg.AccountID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountMediaUsersRow{}
	for rows.Next() {
		var i ListAccountMediaUsersRow
		if err := rows.Scan(
			&i.AccountID,
			&i.MediaServerID,
			&i.MediaServerName,
			&i.MediaUserID,
			&i.Username,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAccountMediaUser = `-- name: SetAccountMediaUser :exec
INSERT INTO account_media_users (
    account_id, media_server_id, media_user_id, username, source, created_at, updated_at
) VALUES (
    ?1, ?2, ?3,
    ?4, ?5, ?6, ?7
)
ON CONFLICT (account_id, media_server_id) DO UPDATE SET
    media_user_id = excluded.media_user_id,
    username = excluded.username,
    source = excluded.source,
    updated_at = excluded.updated_at
`

type SetAccountMediaUserParams struct {
	AccountID     string
	MediaServerID string
	MediaUserID   string
	Username      string
	Source        string
	CreatedAt     string
	UpdatedAt     string
}

func (q *Queries) SetAccountMediaUser(ctx context.Context, arg SetAccountMediaUserParams) error {
	_, err := q.db.ExecContext(ctx, setAccountMediaUser,
		arg.AccountID,
		arg.MediaServerID,
		arg.MediaUserID,
		arg.Username,
		arg.Source,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
