// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts_sqlite.sql

package sqlite

import (
	"context"
)

const usernamesByAccountIDs = `-- name: UsernamesByAccountIDs :many

SELECT id, username
FROM accounts
WHERE id IN (
    SELECT value FROM json_each(CAST(?1 AS TEXT))
)
ORDER BY id
`

type UsernamesByAccountIDsRow struct {
	ID       string
	Username string
}

// SQLite account queries whose parameter syntax is engine-specific.
func (q *Queries) UsernamesByAccountIDs(ctx context.Context, accountIdsJson string) ([]UsernamesByAccountIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, usernamesByAccountIDs, accountIdsJson)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsernamesByAccountIDsRow{}
	for rows.Next() {
		var i UsernamesByAccountIDsRow
		if err := rows.Scan(&i.ID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
