// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity.sql

package sqlite

import (
	"context"
	"database/sql"
)

const listTimelineWatches = `-- name: ListTimelineWatches :many

SELECT w.id, w.media_server_id, w.media_user_id, w.username, w.device_id, w.device_name,
       w.client, w.server_session_id, w.item_id, w.item_name, w.item_type, w.series_name,
       w.season_number, w.episode_number, w.play_method, w.state, w.started_at, w.last_seen_at,
       w.ended_at, w.active_seconds, w.last_position_ms, w.source, w.created_at, w.updated_at,
       w.library_id, w.library_name, w.stream_container, w.stream_video_codec,
       w.stream_audio_codec, w.stream_bitrate, w.stream_width, w.stream_height,
       w.stream_framerate_hundredths, w.stream_audio_channels, w.stream_is_video_direct,
       w.stream_is_audio_direct, w.stream_transcode_reasons, w.runtime_ms, w.import_record_id,
       w.series_id, w.import_source, w.import_provenance_guard, w.import_origin_record_id,
       ms.name AS media_server_name
FROM watches w
JOIN media_servers ms ON ms.id = w.media_server_id
WHERE w.media_server_id = ?1
  AND w.media_user_id = ?2
  AND (w.started_at, w.id) < (?3, CAST(?4 AS TEXT))
  AND NOT EXISTS (
      SELECT 1 FROM media_server_exclusions e
      WHERE e.media_server_id = w.media_server_id
        AND ((e.kind = 'media_user' AND e.external_id = w.media_user_id)
          OR (e.kind = 'library' AND (e.external_id = w.library_id OR EXISTS (
              SELECT 1 FROM library_items excluded_item
              WHERE excluded_item.media_server_id = w.media_server_id
                AND excluded_item.item_id = w.item_id
                AND excluded_item.library_id = e.external_id))))
  )
ORDER BY w.started_at DESC, w.id DESC
LIMIT ?5
`

type ListTimelineWatchesParams struct {
	MediaServerID   string
	MediaUserID     string
	BeforeStartedAt string
	BeforeID        string
	PageSize        int64
}

type ListTimelineWatchesRow struct {
	ID                        string
	MediaServerID             string
	MediaUserID               string
	Username                  string
	DeviceID                  string
	DeviceName                string
	Client                    string
	ServerSessionID           string
	ItemID                    string
	ItemName                  string
	ItemType                  string
	SeriesName                string
	SeasonNumber              sql.NullInt64
	EpisodeNumber             sql.NullInt64
	PlayMethod                string
	State                     string
	StartedAt                 string
	LastSeenAt                string
	EndedAt                   sql.NullString
	ActiveSeconds             int64
	LastPositionMs            int64
	Source                    string
	CreatedAt                 string
	UpdatedAt                 string
	LibraryID                 string
	LibraryName               string
	StreamContainer           sql.NullString
	StreamVideoCodec          sql.NullString
	StreamAudioCodec          sql.NullString
	StreamBitrate             sql.NullInt64
	StreamWidth               sql.NullInt64
	StreamHeight              sql.NullInt64
	StreamFramerateHundredths sql.NullInt64
	StreamAudioChannels       sql.NullInt64
	StreamIsVideoDirect       sql.NullInt64
	StreamIsAudioDirect       sql.NullInt64
	StreamTranscodeReasons    sql.NullString
	RuntimeMs                 sql.NullInt64
	ImportRecordID            sql.NullString
	SeriesID                  sql.NullString
	ImportSource              sql.NullString
	ImportProvenanceGuard     sql.NullInt64
	ImportOriginRecordID      sql.NullString
	MediaServerName           string
}

// Per-user timeline query shared by SQLite and PostgreSQL. Activity title
// matching is engine-specific so q remains a literal substring.
func (q *Queries) ListTimelineWatches(ctx context.Context, arg ListTimelineWatchesParams) ([]ListTimelineWatchesRow, error) {
	rows, err := q.db.QueryContext(ctx, listTimelineWatches,
		arg.MediaServerID,
		arg.MediaUserID,
		arg.BeforeStartedAt,
		arg.BeforeID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTimelineWatchesRow{}
	for rows.Next() {
		var i ListTimelineWatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.MediaServerID,
			&i.MediaUserID,
			&i.Username,
			&i.DeviceID,
			&i.DeviceName,
			&i.Client,
			&i.ServerSessionID,
			&i.ItemID,
			&i.ItemName,
			&i.ItemType,
			&i.SeriesName,
			&i.SeasonNumber,
			&i.EpisodeNumber,
			&i.PlayMethod,
			&i.State,
			&i.StartedAt,
			&i.LastSeenAt,
			&i.EndedAt,
			&i.ActiveSeconds,
			&i.LastPositionMs,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LibraryID,
			&i.LibraryName,
			&i.StreamContainer,
			&i.StreamVideoCodec,
			&i.StreamAudioCodec,
			&i.StreamBitrate,
			&i.StreamWidth,
			&i.StreamHeight,
			&i.StreamFramerateHundredths,
			&i.StreamAudioChannels,
			&i.StreamIsVideoDirect,
			&i.StreamIsAudioDirect,
			&i.StreamTranscodeReasons,
			&i.RuntimeMs,
			&i.ImportRecordID,
			&i.SeriesID,
			&i.ImportSource,
			&i.ImportProvenanceGuard,
			&i.ImportOriginRecordID,
			&i.MediaServerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
