// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authorization.sql

package sqlite

import (
	"context"
	"database/sql"
)

const assignRoleIDToAccount = `-- name: AssignRoleIDToAccount :execrows
INSERT INTO account_roles (account_id, role_id)
VALUES (?1, ?2)
ON CONFLICT DO NOTHING
`

type AssignRoleIDToAccountParams struct {
	AccountID string
	RoleID    string
}

func (q *Queries) AssignRoleIDToAccount(ctx context.Context, arg AssignRoleIDToAccountParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, assignRoleIDToAccount, arg.AccountID, arg.RoleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAuthorizationSnapshot = `-- name: GetAuthorizationSnapshot :many
SELECT r.name AS role_name, rp.permission
FROM account_roles ar
JOIN roles r ON r.id = ar.role_id
LEFT JOIN role_permissions rp ON rp.role_id = r.id
WHERE ar.account_id = ?1
ORDER BY r.name, rp.permission
`

type GetAuthorizationSnapshotRow struct {
	RoleName   string
	Permission sql.NullString
}

func (q *Queries) GetAuthorizationSnapshot(ctx context.Context, accountID string) ([]GetAuthorizationSnapshotRow, error) {
	rows, err := q.db.QueryContext(ctx, getAuthorizationSnapshot, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAuthorizationSnapshotRow{}
	for rows.Next() {
		var i GetAuthorizationSnapshotRow
		if err := rows.Scan(&i.RoleName, &i.Permission); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoleIDByName = `-- name: GetRoleIDByName :one
SELECT id
FROM roles
WHERE name = ?1
`

func (q *Queries) GetRoleIDByName(ctx context.Context, roleName string) (string, error) {
	row := q.db.QueryRowContext(ctx, getRoleIDByName, roleName)
	var id string
	err := row.Scan(&id)
	return id, err
}

const listAccountPermissions = `-- name: ListAccountPermissions :many

SELECT DISTINCT rp.permission
FROM account_roles ar
JOIN role_permissions rp ON rp.role_id = ar.role_id
WHERE ar.account_id = ?1
ORDER BY rp.permission
`

// Authorization queries are shared by SQLite and PostgreSQL. Effective
// permissions are computed from current database state for every request.
func (q *Queries) ListAccountPermissions(ctx context.Context, accountID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAccountPermissions, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var permission string
		if err := rows.Scan(&permission); err != nil {
			return nil, err
		}
		items = append(items, permission)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesWithPermissions = `-- name: ListRolesWithPermissions :many
WITH role_page AS (
    SELECT id, name, description, built_in, created_at
    FROM roles
    WHERE name > ?1
    ORDER BY name
    LIMIT ?2
)
SELECT role_page.id, role_page.name, role_page.description, role_page.built_in,
       role_page.created_at, rp.permission
FROM role_page
LEFT JOIN role_permissions rp ON rp.role_id = role_page.id
ORDER BY role_page.name, rp.permission
`

type ListRolesWithPermissionsParams struct {
	AfterName string
	PageSize  int64
}

type ListRolesWithPermissionsRow struct {
	ID          string
	Name        string
	Description string
	BuiltIn     int64
	CreatedAt   string
	Permission  sql.NullString
}

func (q *Queries) ListRolesWithPermissions(ctx context.Context, arg ListRolesWithPermissionsParams) ([]ListRolesWithPermissionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRolesWithPermissions, arg.AfterName, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRolesWithPermissionsRow{}
	for rows.Next() {
		var i ListRolesWithPermissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.BuiltIn,
			&i.CreatedAt,
			&i.Permission,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
