// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exclusions_sqlite.sql

package sqlite

import (
	"context"
)

const lockMediaServerForExclusionReplace = `-- name: LockMediaServerForExclusionReplace :one

SELECT id FROM media_servers
WHERE id = ?1
`

// SQLite exclusion replacement transaction parity.
func (q *Queries) LockMediaServerForExclusionReplace(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, lockMediaServerForExclusionReplace, id)
	var id_2 string
	err := row.Scan(&id_2)
	return id_2, err
}
