// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exclusions.sql

package sqlite

import (
	"context"
)

const deleteMediaServerExclusions = `-- name: DeleteMediaServerExclusions :exec
DELETE FROM media_server_exclusions WHERE media_server_id = ?1
`

func (q *Queries) DeleteMediaServerExclusions(ctx context.Context, mediaServerID string) error {
	_, err := q.db.ExecContext(ctx, deleteMediaServerExclusions, mediaServerID)
	return err
}

const insertMediaServerExclusion = `-- name: InsertMediaServerExclusion :exec
INSERT INTO media_server_exclusions (media_server_id, kind, external_id)
VALUES (?1, ?2, ?3)
`

type InsertMediaServerExclusionParams struct {
	MediaServerID string
	Kind          string
	ExternalID    string
}

func (q *Queries) InsertMediaServerExclusion(ctx context.Context, arg InsertMediaServerExclusionParams) error {
	_, err := q.db.ExecContext(ctx, insertMediaServerExclusion, arg.MediaServerID, arg.Kind, arg.ExternalID)
	return err
}

const listMediaServerExclusions = `-- name: ListMediaServerExclusions :many

SELECT media_server_id, kind, external_id
FROM media_server_exclusions
WHERE media_server_id = ?1
ORDER BY kind, external_id
`

// Per-media-server exclusion settings shared by SQLite and PostgreSQL.
func (q *Queries) ListMediaServerExclusions(ctx context.Context, mediaServerID string) ([]MediaServerExclusion, error) {
	rows, err := q.db.QueryContext(ctx, listMediaServerExclusions, mediaServerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaServerExclusion{}
	for rows.Next() {
		var i MediaServerExclusion
		if err := rows.Scan(&i.MediaServerID, &i.Kind, &i.ExternalID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
