// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: imports.sql

package sqlite

import (
	"context"
	"database/sql"
)

const cancelImport = `-- name: CancelImport :execrows
UPDATE imports
SET state = 'cancelled', finished_at = ?1, updated_at = ?1,
    lease_token = '', lease_expires_at = NULL
WHERE id = ?2 AND state IN ('pending', 'running')
`

type CancelImportParams struct {
	Now sql.NullString
	ID  string
}

func (q *Queries) CancelImport(ctx context.Context, arg CancelImportParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, cancelImport, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const checkpointImport = `-- name: CheckpointImport :execrows
UPDATE imports
SET cursor = ?1, read_count = read_count + ?2,
    imported_count = imported_count + ?3,
    skipped_count = skipped_count + ?4,
    duplicate_count = duplicate_count + ?5,
    lease_expires_at = ?6, updated_at = ?7
WHERE id = ?8 AND state = 'running' AND lease_token = ?9
`

type CheckpointImportParams struct {
	Cursor         string
	ReadDelta      int64
	ImportedDelta  int64
	SkippedDelta   int64
	DuplicateDelta int64
	ExpiresAt      sql.NullString
	Now            string
	ID             string
	Token          string
}

func (q *Queries) CheckpointImport(ctx context.Context, arg CheckpointImportParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, checkpointImport,
		arg.Cursor,
		arg.ReadDelta,
		arg.ImportedDelta,
		arg.SkippedDelta,
		arg.DuplicateDelta,
		arg.ExpiresAt,
		arg.Now,
		arg.ID,
		arg.Token,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createImport = `-- name: CreateImport :exec

INSERT INTO imports (
    id, media_server_id, source, state, cursor, read_count, imported_count,
    skipped_count, duplicate_count, last_error, lease_token, lease_expires_at,
    requested_by, created_at, started_at, finished_at, updated_at
) VALUES (
    ?1, ?2, ?3, ?4,
    ?5, ?6, ?7,
    ?8, ?9, ?10,
    ?11, ?12, ?13,
    ?14, ?15, ?16, ?17
)
`

type CreateImportParams struct {
	ID             string
	MediaServerID  string
	Source         string
	State          string
	Cursor         string
	ReadCount      int64
	ImportedCount  int64
	SkippedCount   int64
	DuplicateCount int64
	LastError      string
	LeaseToken     string
	LeaseExpiresAt sql.NullString
	RequestedBy    string
	CreatedAt      string
	StartedAt      sql.NullString
	FinishedAt     sql.NullString
	UpdatedAt      string
}

// History-import queries shared by SQLite and PostgreSQL.
func (q *Queries) CreateImport(ctx context.Context, arg CreateImportParams) error {
	_, err := q.db.ExecContext(ctx, createImport,
		arg.ID,
		arg.MediaServerID,
		arg.Source,
		arg.State,
		arg.Cursor,
		arg.ReadCount,
		arg.ImportedCount,
		arg.SkippedCount,
		arg.DuplicateCount,
		arg.LastError,
		arg.LeaseToken,
		arg.LeaseExpiresAt,
		arg.RequestedBy,
		arg.CreatedAt,
		arg.StartedAt,
		arg.FinishedAt,
		arg.UpdatedAt,
	)
	return err
}

const findCollectedImportDuplicate = `-- name: FindCollectedImportDuplicate :one
SELECT EXISTS (
    SELECT 1 FROM watches
    WHERE media_server_id = ?1
      AND media_user_id = ?2
      AND item_id = ?3
      AND source <> 'import'
      AND started_at >= ?4
      AND started_at <= ?5
)
`

type FindCollectedImportDuplicateParams struct {
	MediaServerID string
	MediaUserID   string
	ItemID        string
	StartAfter    string
	StartBefore   string
}

func (q *Queries) FindCollectedImportDuplicate(ctx context.Context, arg FindCollectedImportDuplicateParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, findCollectedImportDuplicate,
		arg.MediaServerID,
		arg.MediaUserID,
		arg.ItemID,
		arg.StartAfter,
		arg.StartBefore,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const finishImport = `-- name: FinishImport :execrows
UPDATE imports
SET state = ?1, last_error = ?2,
    finished_at = ?3, updated_at = ?3,
    lease_token = '', lease_expires_at = NULL
WHERE id = ?4 AND state = 'running' AND lease_token = ?5
`

type FinishImportParams struct {
	State     string
	LastError string
	Now       sql.NullString
	ID        string
	Token     string
}

func (q *Queries) FinishImport(ctx context.Context, arg FinishImportParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, finishImport,
		arg.State,
		arg.LastError,
		arg.Now,
		arg.ID,
		arg.Token,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getImport = `-- name: GetImport :one
SELECT id, media_server_id, source, state, cursor, read_count, imported_count, skipped_count, duplicate_count, last_error, lease_token, lease_expires_at, requested_by, created_at, started_at, finished_at, updated_at FROM imports WHERE id = ?1
`

func (q *Queries) GetImport(ctx context.Context, id string) (Import, error) {
	row := q.db.QueryRowContext(ctx, getImport, id)
	var i Import
	err := row.Scan(
		&i.ID,
		&i.MediaServerID,
		&i.Source,
		&i.State,
		&i.Cursor,
		&i.ReadCount,
		&i.ImportedCount,
		&i.SkippedCount,
		&i.DuplicateCount,
		&i.LastError,
		&i.LeaseToken,
		&i.LeaseExpiresAt,
		&i.RequestedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertImportedWatch = `-- name: InsertImportedWatch :execrows
INSERT INTO watches (
    id, media_server_id, media_user_id, username, device_id, device_name, client,
    server_session_id, item_id, item_name, item_type, series_name, library_id,
    library_name, season_number, episode_number, play_method,
    stream_container, stream_video_codec, stream_audio_codec, stream_bitrate,
    stream_width, stream_height, stream_framerate_hundredths, stream_audio_channels,
    stream_is_video_direct, stream_is_audio_direct, stream_transcode_reasons,
    state, started_at, last_seen_at, ended_at, active_seconds, last_position_ms, source,
    created_at, updated_at, import_source, import_record_id
) VALUES (
    ?1, ?2, ?3, ?4,
    ?5, ?6, ?7, '', ?8, ?9,
    ?10, ?11, ?12, ?13,
    ?14, ?15, ?16,
    ?17, ?18, ?19,
    ?20, ?21, ?22,
    ?23, ?24,
    ?25, ?26,
    ?27, 'stopped', ?28, ?29,
    ?29, ?30, ?31, 'import',
    ?32, ?32, ?33, ?34
)
ON CONFLICT (media_server_id, import_source, import_record_id)
WHERE import_record_id IS NOT NULL DO NOTHING
`

type InsertImportedWatchParams struct {
	ID                        string
	MediaServerID             string
	MediaUserID               string
	Username                  string
	DeviceID                  string
	DeviceName                string
	Client                    string
	ItemID                    string
	ItemName                  string
	ItemType                  string
	SeriesName                string
	LibraryID                 string
	LibraryName               string
	SeasonNumber              sql.NullInt64
	EpisodeNumber             sql.NullInt64
	PlayMethod                string
	StreamContainer           sql.NullString
	StreamVideoCodec          sql.NullString
	StreamAudioCodec          sql.NullString
	StreamBitrate             sql.NullInt64
	StreamWidth               sql.NullInt64
	StreamHeight              sql.NullInt64
	StreamFramerateHundredths sql.NullInt64
	StreamAudioChannels       sql.NullInt64
	StreamIsVideoDirect       sql.NullInt64
	StreamIsAudioDirect       sql.NullInt64
	StreamTranscodeReasons    sql.NullString
	StartedAt                 string
	EndedAt                   string
	ActiveSeconds             int64
	LastPositionMs            int64
	Now                       string
	ImportSource              sql.NullString
	ImportRecordID            sql.NullString
}

func (q *Queries) InsertImportedWatch(ctx context.Context, arg InsertImportedWatchParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertImportedWatch,
		arg.ID,
		arg.MediaServerID,
		arg.MediaUserID,
		arg.Username,
		arg.DeviceID,
		arg.DeviceName,
		arg.Client,
		arg.ItemID,
		arg.ItemName,
		arg.ItemType,
		arg.SeriesName,
		arg.LibraryID,
		arg.LibraryName,
		arg.SeasonNumber,
		arg.EpisodeNumber,
		arg.PlayMethod,
		arg.StreamContainer,
		arg.StreamVideoCodec,
		arg.StreamAudioCodec,
		arg.StreamBitrate,
		arg.StreamWidth,
		arg.StreamHeight,
		arg.StreamFramerateHundredths,
		arg.StreamAudioChannels,
		arg.StreamIsVideoDirect,
		arg.StreamIsAudioDirect,
		arg.StreamTranscodeReasons,
		arg.StartedAt,
		arg.EndedAt,
		arg.ActiveSeconds,
		arg.LastPositionMs,
		arg.Now,
		arg.ImportSource,
		arg.ImportRecordID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listActiveBloomImportCursors = `-- name: ListActiveBloomImportCursors :many
SELECT cursor FROM imports
WHERE source = 'bloom_export' AND state IN ('pending', 'running')
ORDER BY id
LIMIT 10001
`

func (q *Queries) ListActiveBloomImportCursors(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listActiveBloomImportCursors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var cursor string
		if err := rows.Scan(&cursor); err != nil {
			return nil, err
		}
		items = append(items, cursor)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImports = `-- name: ListImports :many
SELECT id, media_server_id, source, state, cursor, read_count, imported_count, skipped_count, duplicate_count, last_error, lease_token, lease_expires_at, requested_by, created_at, started_at, finished_at, updated_at FROM imports
WHERE (created_at < ?1
       OR (created_at = ?1 AND id < ?2))
ORDER BY created_at DESC, id DESC
LIMIT ?3
`

type ListImportsParams struct {
	BeforeCreatedAt string
	BeforeID        string
	PageSize        int64
}

func (q *Queries) ListImports(ctx context.Context, arg ListImportsParams) ([]Import, error) {
	rows, err := q.db.QueryContext(ctx, listImports, arg.BeforeCreatedAt, arg.BeforeID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Import{}
	for rows.Next() {
		var i Import
		if err := rows.Scan(
			&i.ID,
			&i.MediaServerID,
			&i.Source,
			&i.State,
			&i.Cursor,
			&i.ReadCount,
			&i.ImportedCount,
			&i.SkippedCount,
			&i.DuplicateCount,
			&i.LastError,
			&i.LeaseToken,
			&i.LeaseExpiresAt,
			&i.RequestedBy,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renewImportLease = `-- name: RenewImportLease :execrows
UPDATE imports
SET lease_expires_at = ?1, updated_at = ?2
WHERE id = ?3 AND state = 'running' AND lease_token = ?4
`

type RenewImportLeaseParams struct {
	ExpiresAt sql.NullString
	Now       string
	ID        string
	Token     string
}

func (q *Queries) RenewImportLease(ctx context.Context, arg RenewImportLeaseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, renewImportLease,
		arg.ExpiresAt,
		arg.Now,
		arg.ID,
		arg.Token,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
