// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invites.sql

package sqlite

import (
	"context"
	"database/sql"
)

const claimInviteProvisioningFailure = `-- name: ClaimInviteProvisioningFailure :one
UPDATE invite_provisioning_failures SET
    lease_token = ?1, lease_expires_at = ?2,
    attempts = attempts + 1, terminal = attempts + 1 >= 8, updated_at = ?3
WHERE id = ?4 AND terminal = FALSE AND attempts < 8
  AND next_attempt_at <= ?5
  AND (lease_token = '' OR lease_expires_at <= ?5)
RETURNING id, invite_id, media_server_id, media_user_id, media_user_owned, account_id, username, reason,
          attempts, next_attempt_at, lease_token, lease_expires_at, last_error, terminal,
          created_at, updated_at
`

type ClaimInviteProvisioningFailureParams struct {
	LeaseToken     string
	LeaseExpiresAt sql.NullString
	UpdatedAt      string
	ID             string
	DueAt          string
}

type ClaimInviteProvisioningFailureRow struct {
	ID             string
	InviteID       string
	MediaServerID  string
	MediaUserID    sql.NullString
	MediaUserOwned int64
	AccountID      sql.NullString
	Username       string
	Reason         string
	Attempts       int64
	NextAttemptAt  string
	LeaseToken     string
	LeaseExpiresAt sql.NullString
	LastError      string
	Terminal       int64
	CreatedAt      string
	UpdatedAt      string
}

func (q *Queries) ClaimInviteProvisioningFailure(ctx context.Context, arg ClaimInviteProvisioningFailureParams) (ClaimInviteProvisioningFailureRow, error) {
	row := q.db.QueryRowContext(ctx, claimInviteProvisioningFailure,
		arg.LeaseToken,
		arg.LeaseExpiresAt,
		arg.UpdatedAt,
		arg.ID,
		arg.DueAt,
	)
	var i ClaimInviteProvisioningFailureRow
	err := row.Scan(
		&i.ID,
		&i.InviteID,
		&i.MediaServerID,
		&i.MediaUserID,
		&i.MediaUserOwned,
		&i.AccountID,
		&i.Username,
		&i.Reason,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LeaseToken,
		&i.LeaseExpiresAt,
		&i.LastError,
		&i.Terminal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeInviteProvisioningCleanup = `-- name: CompleteInviteProvisioningCleanup :execrows
DELETE FROM invite_provisioning_failures
WHERE id = ?1 AND lease_token = ?2
`

type CompleteInviteProvisioningCleanupParams struct {
	ID         string
	LeaseToken string
}

func (q *Queries) CompleteInviteProvisioningCleanup(ctx context.Context, arg CompleteInviteProvisioningCleanupParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeInviteProvisioningCleanup, arg.ID, arg.LeaseToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createInvite = `-- name: CreateInvite :exec
INSERT INTO invites (
    id, media_server_id, created_by_account_id, code_hash, label,
    expires_at, max_uses, use_count, revoked_at, created_at, updated_at
) VALUES (
    ?1, ?2, ?3,
    ?4, ?5, ?6, ?7,
    0, NULL, ?8, ?9
)
`

type CreateInviteParams struct {
	ID                 string
	MediaServerID      string
	CreatedByAccountID string
	CodeHash           []byte
	Label              string
	ExpiresAt          sql.NullString
	MaxUses            sql.NullInt64
	CreatedAt          string
	UpdatedAt          string
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) error {
	_, err := q.db.ExecContext(ctx, createInvite,
		arg.ID,
		arg.MediaServerID,
		arg.CreatedByAccountID,
		arg.CodeHash,
		arg.Label,
		arg.ExpiresAt,
		arg.MaxUses,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createInviteLibrary = `-- name: CreateInviteLibrary :exec
INSERT INTO invite_libraries (invite_id, library_id)
VALUES (?1, ?2)
`

type CreateInviteLibraryParams struct {
	InviteID  string
	LibraryID string
}

func (q *Queries) CreateInviteLibrary(ctx context.Context, arg CreateInviteLibraryParams) error {
	_, err := q.db.ExecContext(ctx, createInviteLibrary, arg.InviteID, arg.LibraryID)
	return err
}

const dismissInviteProvisioningFailure = `-- name: DismissInviteProvisioningFailure :execrows
DELETE FROM invite_provisioning_failures
WHERE id = ?1
  AND (lease_token = '' OR (lease_expires_at IS NOT NULL AND lease_expires_at <= ?2))
`

type DismissInviteProvisioningFailureParams struct {
	ID          string
	DismissedAt sql.NullString
}

func (q *Queries) DismissInviteProvisioningFailure(ctx context.Context, arg DismissInviteProvisioningFailureParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, dismissInviteProvisioningFailure, arg.ID, arg.DismissedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getClaimedInviteProvisioningFailure = `-- name: GetClaimedInviteProvisioningFailure :one
SELECT id, invite_id, media_server_id, media_user_id, media_user_owned, account_id, username, reason,
       attempts, next_attempt_at, lease_token, lease_expires_at, last_error, terminal,
       created_at, updated_at
FROM invite_provisioning_failures
WHERE id = ?1 AND lease_token = ?2
`

type GetClaimedInviteProvisioningFailureParams struct {
	ID         string
	LeaseToken string
}

type GetClaimedInviteProvisioningFailureRow struct {
	ID             string
	InviteID       string
	MediaServerID  string
	MediaUserID    sql.NullString
	MediaUserOwned int64
	AccountID      sql.NullString
	Username       string
	Reason         string
	Attempts       int64
	NextAttemptAt  string
	LeaseToken     string
	LeaseExpiresAt sql.NullString
	LastError      string
	Terminal       int64
	CreatedAt      string
	UpdatedAt      string
}

func (q *Queries) GetClaimedInviteProvisioningFailure(ctx context.Context, arg GetClaimedInviteProvisioningFailureParams) (GetClaimedInviteProvisioningFailureRow, error) {
	row := q.db.QueryRowContext(ctx, getClaimedInviteProvisioningFailure, arg.ID, arg.LeaseToken)
	var i GetClaimedInviteProvisioningFailureRow
	err := row.Scan(
		&i.ID,
		&i.InviteID,
		&i.MediaServerID,
		&i.MediaUserID,
		&i.MediaUserOwned,
		&i.AccountID,
		&i.Username,
		&i.Reason,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LeaseToken,
		&i.LeaseExpiresAt,
		&i.LastError,
		&i.Terminal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvite = `-- name: GetInvite :one
SELECT id, media_server_id, created_by_account_id, label, expires_at,
       max_uses, use_count, revoked_at, created_at, updated_at
FROM invites
WHERE id = ?1
`

type GetInviteRow struct {
	ID                 string
	MediaServerID      string
	CreatedByAccountID string
	Label              string
	ExpiresAt          sql.NullString
	MaxUses            sql.NullInt64
	UseCount           int64
	RevokedAt          sql.NullString
	CreatedAt          string
	UpdatedAt          string
}

func (q *Queries) GetInvite(ctx context.Context, id string) (GetInviteRow, error) {
	row := q.db.QueryRowContext(ctx, getInvite, id)
	var i GetInviteRow
	err := row.Scan(
		&i.ID,
		&i.MediaServerID,
		&i.CreatedByAccountID,
		&i.Label,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.UseCount,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInviteByCodeHash = `-- name: GetInviteByCodeHash :one
SELECT id, media_server_id, created_by_account_id, code_hash, label, expires_at,
       max_uses, use_count, revoked_at, created_at, updated_at,
       EXISTS (SELECT 1 FROM invite_provisioning_failures AS failure
               WHERE failure.invite_id = invites.id) AS blocked
FROM invites
WHERE code_hash = ?1
`

type GetInviteByCodeHashRow struct {
	ID                 string
	MediaServerID      string
	CreatedByAccountID string
	CodeHash           []byte
	Label              string
	ExpiresAt          sql.NullString
	MaxUses            sql.NullInt64
	UseCount           int64
	RevokedAt          sql.NullString
	CreatedAt          string
	UpdatedAt          string
	Blocked            bool
}

func (q *Queries) GetInviteByCodeHash(ctx context.Context, codeHash []byte) (GetInviteByCodeHashRow, error) {
	row := q.db.QueryRowContext(ctx, getInviteByCodeHash, codeHash)
	var i GetInviteByCodeHashRow
	err := row.Scan(
		&i.ID,
		&i.MediaServerID,
		&i.CreatedByAccountID,
		&i.CodeHash,
		&i.Label,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.UseCount,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Blocked,
	)
	return i, err
}

const incrementInviteUse = `-- name: IncrementInviteUse :execrows
UPDATE invites
SET use_count = use_count + 1, updated_at = ?1
WHERE id = ?2
`

type IncrementInviteUseParams struct {
	UpdatedAt string
	ID        string
}

func (q *Queries) IncrementInviteUse(ctx context.Context, arg IncrementInviteUseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, incrementInviteUse, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertInviteProvisioningFailureIfAbsent = `-- name: InsertInviteProvisioningFailureIfAbsent :exec
INSERT INTO invite_provisioning_failures (
    id, invite_id, media_server_id, media_user_id, media_user_owned, account_id, username, reason,
    attempts, next_attempt_at, lease_token, lease_expires_at, last_error, terminal,
    created_at, updated_at
) VALUES (
    ?1, ?2, ?3, ?4,
    ?5, ?6, ?7, ?8,
    0, ?9, '', NULL, ?10, ?11,
    ?12, ?13
)
ON CONFLICT (id) DO NOTHING
`

type InsertInviteProvisioningFailureIfAbsentParams struct {
	ID             string
	InviteID       string
	MediaServerID  string
	MediaUserID    sql.NullString
	MediaUserOwned int64
	AccountID      sql.NullString
	Username       string
	Reason         string
	NextAttemptAt  string
	LastError      string
	Terminal       int64
	CreatedAt      string
	UpdatedAt      string
}

func (q *Queries) InsertInviteProvisioningFailureIfAbsent(ctx context.Context, arg InsertInviteProvisioningFailureIfAbsentParams) error {
	_, err := q.db.ExecContext(ctx, insertInviteProvisioningFailureIfAbsent,
		arg.ID,
		arg.InviteID,
		arg.MediaServerID,
		arg.MediaUserID,
		arg.MediaUserOwned,
		arg.AccountID,
		arg.Username,
		arg.Reason,
		arg.NextAttemptAt,
		arg.LastError,
		arg.Terminal,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertInviteRedemption = `-- name: InsertInviteRedemption :exec
INSERT INTO invite_redemptions (
    id, invite_id, media_server_id, media_user_id, username, redeemed_at
) VALUES (
    ?1, ?2, ?3,
    ?4, ?5, ?6
)
`

type InsertInviteRedemptionParams struct {
	ID            string
	InviteID      string
	MediaServerID string
	MediaUserID   string
	Username      string
	RedeemedAt    string
}

func (q *Queries) InsertInviteRedemption(ctx context.Context, arg InsertInviteRedemptionParams) error {
	_, err := q.db.ExecContext(ctx, insertInviteRedemption,
		arg.ID,
		arg.InviteID,
		arg.MediaServerID,
		arg.MediaUserID,
		arg.Username,
		arg.RedeemedAt,
	)
	return err
}

const inviteProvisioningFailureDepth = `-- name: InviteProvisioningFailureDepth :one
SELECT COUNT(*) FROM invite_provisioning_failures
`

func (q *Queries) InviteProvisioningFailureDepth(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, inviteProvisioningFailureDepth)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const inviteProvisioningFailureExists = `-- name: InviteProvisioningFailureExists :one
SELECT EXISTS (SELECT 1 FROM invite_provisioning_failures WHERE id = ?1)
`

func (q *Queries) InviteProvisioningFailureExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRowContext(ctx, inviteProvisioningFailureExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listInviteLibraries = `-- name: ListInviteLibraries :many
SELECT library_id
FROM invite_libraries
WHERE invite_id = ?1
ORDER BY library_id
`

func (q *Queries) ListInviteLibraries(ctx context.Context, inviteID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listInviteLibraries, inviteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var library_id string
		if err := rows.Scan(&library_id); err != nil {
			return nil, err
		}
		items = append(items, library_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInviteProvisioningFailures = `-- name: ListInviteProvisioningFailures :many
SELECT failure.id, failure.invite_id, failure.media_server_id, server.name AS media_server_name,
       failure.media_user_owned, failure.username, failure.reason, failure.attempts, failure.next_attempt_at,
       failure.last_error, failure.terminal, failure.created_at, failure.updated_at
FROM invite_provisioning_failures AS failure
JOIN media_servers AS server ON server.id = failure.media_server_id
WHERE CAST(?1 AS INTEGER) = 0
   OR failure.created_at < ?2
   OR (failure.created_at = ?2 AND failure.id < ?3)
ORDER BY failure.created_at DESC, failure.id DESC
LIMIT ?4
`

type ListInviteProvisioningFailuresParams struct {
	HasCursor      int64
	AfterCreatedAt string
	AfterID        string
	PageSize       int64
}

type ListInviteProvisioningFailuresRow struct {
	ID              string
	InviteID        string
	MediaServerID   string
	MediaServerName string
	MediaUserOwned  int64
	Username        string
	Reason          string
	Attempts        int64
	NextAttemptAt   string
	LastError       string
	Terminal        int64
	CreatedAt       string
	UpdatedAt       string
}

func (q *Queries) ListInviteProvisioningFailures(ctx context.Context, arg ListInviteProvisioningFailuresParams) ([]ListInviteProvisioningFailuresRow, error) {
	rows, err := q.db.QueryContext(ctx, listInviteProvisioningFailures,
		arg.HasCursor,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInviteProvisioningFailuresRow{}
	for rows.Next() {
		var i ListInviteProvisioningFailuresRow
		if err := rows.Scan(
			&i.ID,
			&i.InviteID,
			&i.MediaServerID,
			&i.MediaServerName,
			&i.MediaUserOwned,
			&i.Username,
			&i.Reason,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LastError,
			&i.Terminal,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvites = `-- name: ListInvites :many
SELECT id, media_server_id, created_by_account_id, label, expires_at,
       max_uses, use_count, revoked_at, created_at, updated_at
FROM invites
WHERE CAST(?1 AS INTEGER) = 0
   OR created_at < ?2
   OR (created_at = ?2 AND id < ?3)
ORDER BY created_at DESC, id DESC
LIMIT ?4
`

type ListInvitesParams struct {
	HasCursor      int64
	AfterCreatedAt string
	AfterID        string
	PageSize       int64
}

type ListInvitesRow struct {
	ID                 string
	MediaServerID      string
	CreatedByAccountID string
	Label              string
	ExpiresAt          sql.NullString
	MaxUses            sql.NullInt64
	UseCount           int64
	RevokedAt          sql.NullString
	CreatedAt          string
	UpdatedAt          string
}

func (q *Queries) ListInvites(ctx context.Context, arg ListInvitesParams) ([]ListInvitesRow, error) {
	rows, err := q.db.QueryContext(ctx, listInvites,
		arg.HasCursor,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvitesRow{}
	for rows.Next() {
		var i ListInvitesRow
		if err := rows.Scan(
			&i.ID,
			&i.MediaServerID,
			&i.CreatedByAccountID,
			&i.Label,
			&i.ExpiresAt,
			&i.MaxUses,
			&i.UseCount,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rescheduleInviteProvisioningFailure = `-- name: RescheduleInviteProvisioningFailure :execrows
UPDATE invite_provisioning_failures SET
    next_attempt_at = ?1, lease_token = '', lease_expires_at = NULL,
    last_error = ?2, terminal = ?3, updated_at = ?4
WHERE id = ?5 AND lease_token = ?6
`

type RescheduleInviteProvisioningFailureParams struct {
	NextAttemptAt string
	LastError     string
	Terminal      int64
	UpdatedAt     string
	ID            string
	LeaseToken    string
}

func (q *Queries) RescheduleInviteProvisioningFailure(ctx context.Context, arg RescheduleInviteProvisioningFailureParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, rescheduleInviteProvisioningFailure,
		arg.NextAttemptAt,
		arg.LastError,
		arg.Terminal,
		arg.UpdatedAt,
		arg.ID,
		arg.LeaseToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeInvite = `-- name: RevokeInvite :one
UPDATE invites
SET revoked_at = COALESCE(revoked_at, ?1),
    updated_at = ?2
WHERE id = ?3
RETURNING id, media_server_id, created_by_account_id, label, expires_at,
          max_uses, use_count, revoked_at, created_at, updated_at
`

type RevokeInviteParams struct {
	RevokedAt sql.NullString
	UpdatedAt string
	ID        string
}

type RevokeInviteRow struct {
	ID                 string
	MediaServerID      string
	CreatedByAccountID string
	Label              string
	ExpiresAt          sql.NullString
	MaxUses            sql.NullInt64
	UseCount           int64
	RevokedAt          sql.NullString
	CreatedAt          string
	UpdatedAt          string
}

func (q *Queries) RevokeInvite(ctx context.Context, arg RevokeInviteParams) (RevokeInviteRow, error) {
	row := q.db.QueryRowContext(ctx, revokeInvite, arg.RevokedAt, arg.UpdatedAt, arg.ID)
	var i RevokeInviteRow
	err := row.Scan(
		&i.ID,
		&i.MediaServerID,
		&i.CreatedByAccountID,
		&i.Label,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.UseCount,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
