// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlite

import (
	"database/sql"
)

type Account struct {
	ID           string
	Username     string
	CreatedAt    string
	PasswordHash sql.NullString
	Disabled     int64
	UsernameKey  string
}

type AccountIdentity struct {
	AccountID     string
	Provider      string
	Issuer        string
	Subject       string
	UsernameClaim string
	MappedRoles   string
	CreatedAt     string
	LastLoginAt   string
}

type AccountRequestQuota struct {
	AccountID           string
	MovieLimit          int64
	MoviePeriodSeconds  int64
	SeasonLimit         int64
	SeasonPeriodSeconds int64
}

type AccountRole struct {
	AccountID string
	RoleID    string
	Source    string
}

type AccountUsernameMigrationBackup struct {
	AccountID        string
	OriginalUsername string
}

type DownloadManager struct {
	ID                   string
	Kind                 string
	Name                 string
	NameKey              string
	BaseUrl              string
	AllowInsecure        int64
	CredentialCiphertext []byte
	KeyID                string
	CreatedAt            string
	UpdatedAt            string
}

type Invite struct {
	ID                 string
	MediaServerID      string
	CreatedByAccountID string
	CodeHash           []byte
	Label              string
	ExpiresAt          sql.NullString
	MaxUses            sql.NullInt64
	UseCount           int64
	RevokedAt          sql.NullString
	CreatedAt          string
	UpdatedAt          string
}

type InviteLibrary struct {
	InviteID  string
	LibraryID string
}

type InviteProvisioningFailure struct {
	ID            string
	InviteID      string
	MediaServerID string
	MediaUserID   sql.NullString
	Username      string
	Reason        string
	CreatedAt     string
	UpdatedAt     string
}

type InviteRedemption struct {
	ID            string
	InviteID      string
	MediaServerID string
	MediaUserID   string
	Username      string
	RedeemedAt    string
}

type MediaServer struct {
	ID                   string
	Kind                 string
	Name                 string
	NameKey              string
	BaseUrl              string
	AllowInsecure        int64
	CredentialCiphertext []byte
	CreatedAt            string
	UpdatedAt            string
}

type MetadataProvider struct {
	Kind                 string
	CredentialCiphertext []byte
	KeyID                string
	CreatedAt            string
	UpdatedAt            string
}

type Request struct {
	ID                      string
	Kind                    string
	Provider                string
	ProviderID              string
	Title                   string
	ReleaseYear             int64
	PosterPath              string
	RequesterAccountID      string
	ProfileID               string
	Status                  string
	DecisionReason          string
	DecidedByAccountID      sql.NullString
	DecidedAt               sql.NullString
	CreatedAt               string
	UpdatedAt               string
	DownloadManagerItemID   string
	FailureReason           string
	DownloadManagerID       string
	DispatchQualityProfile  string
	DispatchRootFolder      string
	DispatchTags            string
	DispatchLeaseExpiresAt  sql.NullString
	DispatchLeaseToken      string
	LastAvailabilityCheckAt sql.NullString
}

type RequestProfile struct {
	ID                      string
	Name                    string
	AcceptsMovies           int64
	AcceptsSeries           int64
	DownloadManagerKind     string
	DownloadManagerInstance string
	QualityProfile          string
	RootFolder              string
	CreatedAt               string
	UpdatedAt               string
}

type RequestProfileTag struct {
	ProfileID string
	Position  int64
	Tag       string
}

type RequestSeason struct {
	RequestID    string
	SeasonNumber int64
	Status       string
}

type Role struct {
	ID          string
	Name        string
	Description string
	BuiltIn     int64
	CreatedAt   string
}

type RolePermission struct {
	RoleID     string
	Permission string
}

type RoleRequestQuota struct {
	RoleID              string
	MovieLimit          int64
	MoviePeriodSeconds  int64
	SeasonLimit         int64
	SeasonPeriodSeconds int64
}

type Session struct {
	Token  string
	Data   []byte
	Expiry int64
}

type Watch struct {
	ID              string
	MediaServerID   string
	MediaUserID     string
	Username        string
	DeviceID        string
	DeviceName      string
	Client          string
	ServerSessionID string
	ItemID          string
	ItemName        string
	ItemType        string
	SeriesName      string
	SeasonNumber    sql.NullInt64
	EpisodeNumber   sql.NullInt64
	PlayMethod      string
	State           string
	StartedAt       string
	LastSeenAt      string
	EndedAt         sql.NullString
	ActiveSeconds   int64
	LastPositionMs  int64
	Source          string
	CreatedAt       string
	UpdatedAt       string
}

type WatchPosition struct {
	WatchID    string
	ObservedAt string
	PositionMs int64
	Paused     int64
	PlayMethod string
	Source     string
}

type WatchSegment struct {
	WatchID   string
	StartedAt string
	EndedAt   sql.NullString
	Source    string
}
