// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlite

import (
	"database/sql"
)

type Account struct {
	ID           string
	Username     string
	CreatedAt    string
	PasswordHash sql.NullString
	Disabled     int64
	UsernameKey  string
}

type AccountIdentity struct {
	AccountID     string
	Provider      string
	Issuer        string
	Subject       string
	UsernameClaim string
	MappedRoles   string
	CreatedAt     string
	LastLoginAt   string
}

type AccountMediaUser struct {
	AccountID     string
	MediaServerID string
	MediaUserID   string
	Username      string
	Source        string
	CreatedAt     string
	UpdatedAt     string
	SuppressedAt  sql.NullString
}

type AccountNotificationPreference struct {
	AccountID string
	EventType string
	Enabled   int64
}

type AccountRequestQuota struct {
	AccountID           string
	MovieLimit          int64
	MoviePeriodSeconds  int64
	SeasonLimit         int64
	SeasonPeriodSeconds int64
}

type AccountRole struct {
	AccountID string
	RoleID    string
	Source    string
}

type AccountUsernameMigrationBackup struct {
	AccountID        string
	OriginalUsername string
}

type DownloadManager struct {
	ID                   string
	Kind                 string
	Name                 string
	NameKey              string
	BaseUrl              string
	AllowInsecure        int64
	CredentialCiphertext []byte
	KeyID                string
	CreatedAt            string
	UpdatedAt            string
}

type Import struct {
	ID                     string
	MediaServerID          string
	State                  string
	Cursor                 string
	ReadCount              int64
	ImportedCount          int64
	SkippedCount           int64
	DuplicateCount         int64
	LastError              string
	LeaseToken             string
	LeaseExpiresAt         sql.NullString
	RequestedBy            string
	CreatedAt              string
	StartedAt              sql.NullString
	FinishedAt             sql.NullString
	UpdatedAt              string
	Source                 string
	UnresolvedLibraryCount int64
}

type ImportUpload struct {
	ID         string
	ImportID   sql.NullString
	ChunkIndex int64
	Bytes      []byte
	CreatedAt  string
}

type Invite struct {
	ID                 string
	MediaServerID      string
	CreatedByAccountID string
	CodeHash           []byte
	Label              string
	ExpiresAt          sql.NullString
	MaxUses            sql.NullInt64
	UseCount           int64
	RevokedAt          sql.NullString
	CreatedAt          string
	UpdatedAt          string
}

type InviteLibrary struct {
	InviteID  string
	LibraryID string
}

type InviteProvisioningFailure struct {
	ID             string
	InviteID       string
	MediaServerID  string
	MediaUserID    sql.NullString
	Username       string
	Reason         string
	CreatedAt      string
	UpdatedAt      string
	AccountID      sql.NullString
	MediaUserOwned int64
	Attempts       int64
	NextAttemptAt  string
	LeaseToken     string
	LeaseExpiresAt sql.NullString
	LastError      string
	Terminal       int64
}

type InviteRedemption struct {
	ID            string
	InviteID      string
	MediaServerID string
	MediaUserID   string
	Username      string
	RedeemedAt    string
}

type LibraryItem struct {
	MediaServerID   string
	ItemID          string
	LibraryID       string
	ParentID        string
	ItemType        string
	Name            string
	SeriesID        string
	SeriesName      string
	SeasonID        string
	SeasonNumber    sql.NullInt64
	IndexNumber     sql.NullInt64
	RuntimeMs       sql.NullInt64
	PremiereDate    sql.NullString
	ProductionYear  sql.NullInt64
	CommunityRating sql.NullFloat64
	Genres          string
	PrimaryImageTag string
	DateCreated     sql.NullString
	Archived        int64
	Plays           int64
	WatchSeconds    int64
	UniqueUsers     int64
	FirstPlayedAt   sql.NullString
	LastPlayedAt    sql.NullString
	FirstSeenAt     string
	LastSeenAt      string
	UpdatedAt       string
}

type LibraryItemGenre struct {
	MediaServerID string
	ItemID        string
	Genre         string
}

type LibrarySync struct {
	MediaServerID  string
	State          string
	Cursor         string
	SeenCount      int64
	UpsertedCount  int64
	ArchivedCount  int64
	LastError      string
	LeaseToken     string
	LeaseExpiresAt sql.NullString
	StartedAt      sql.NullString
	FinishedAt     sql.NullString
}

type MediaServer struct {
	ID                   string
	Kind                 string
	Name                 string
	NameKey              string
	BaseUrl              string
	AllowInsecure        int64
	CredentialCiphertext []byte
	CreatedAt            string
	UpdatedAt            string
}

type MediaServerExclusion struct {
	MediaServerID string
	Kind          string
	ExternalID    string
}

type MetadataProvider struct {
	Kind                 string
	CredentialCiphertext []byte
	KeyID                string
	CreatedAt            string
	UpdatedAt            string
}

type NotificationChannel struct {
	ID                  string
	Kind                string
	Name                string
	NameKey             string
	Target              string
	SettingsJson        string
	SecretCiphertext    []byte
	KeyID               string
	Enabled             int64
	DegradedAt          sql.NullString
	ConsecutiveFailures int64
	DeletedAt           sql.NullString
	CreatedAt           string
	UpdatedAt           string
}

type NotificationChannelSubscription struct {
	ChannelID string
	EventType string
}

type NotificationEvent struct {
	ID                string
	EventType         string
	RequestID         string
	RequesterID       string
	ActorID           string
	MediaKind         string
	Title             string
	RequestStatus     string
	Reason            string
	SourcePayloadJson string
	EventSequence     int64
	OccurredAt        string
	FannedAt          sql.NullString
	CreatedAt         string
}

type NotificationEventRecipient struct {
	EventID   string
	AccountID string
}

type NotificationOutbox struct {
	ID                 string
	EventID            string
	ChannelID          string
	RecipientAccountID sql.NullString
	ChannelKind        string
	EventType          string
	PayloadJson        string
	Status             string
	Attempts           int64
	NextAttemptAt      string
	LeaseToken         string
	LeaseExpiresAt     sql.NullString
	LastError          string
	SentAt             sql.NullString
	CreatedAt          string
	UpdatedAt          string
}

type PlaybackNotificationEmission struct {
	WatchID   string
	EmittedAt string
}

type Request struct {
	ID                      string
	Kind                    string
	Provider                string
	ProviderID              string
	Title                   string
	ReleaseYear             int64
	PosterPath              string
	RequesterAccountID      string
	ProfileID               string
	Status                  string
	DecisionReason          string
	DecidedByAccountID      sql.NullString
	DecidedAt               sql.NullString
	CreatedAt               string
	UpdatedAt               string
	DownloadManagerItemID   string
	FailureReason           string
	DownloadManagerID       string
	DispatchQualityProfile  string
	DispatchRootFolder      string
	DispatchTags            string
	DispatchLeaseExpiresAt  sql.NullString
	DispatchLeaseToken      string
	LastAvailabilityCheckAt sql.NullString
}

type RequestProfile struct {
	ID                      string
	Name                    string
	AcceptsMovies           int64
	AcceptsSeries           int64
	DownloadManagerKind     string
	DownloadManagerInstance string
	QualityProfile          string
	RootFolder              string
	CreatedAt               string
	UpdatedAt               string
}

type RequestProfileTag struct {
	ProfileID string
	Position  int64
	Tag       string
}

type RequestSeason struct {
	RequestID    string
	SeasonNumber int64
	Status       string
}

type Role struct {
	ID          string
	Name        string
	Description string
	BuiltIn     int64
	CreatedAt   string
}

type RolePermission struct {
	RoleID     string
	Permission string
}

type RoleRequestQuota struct {
	RoleID              string
	MovieLimit          int64
	MoviePeriodSeconds  int64
	SeasonLimit         int64
	SeasonPeriodSeconds int64
}

type Session struct {
	Token  string
	Data   []byte
	Expiry int64
}

type TitleAvailabilitySubscription struct {
	AccountID  string
	Provider   string
	ProviderID string
	CreatedAt  string
}

type Watch struct {
	ID                        string
	MediaServerID             string
	MediaUserID               string
	Username                  string
	DeviceID                  string
	DeviceName                string
	Client                    string
	ServerSessionID           string
	ItemID                    string
	ItemName                  string
	ItemType                  string
	SeriesName                string
	SeasonNumber              sql.NullInt64
	EpisodeNumber             sql.NullInt64
	PlayMethod                string
	State                     string
	StartedAt                 string
	LastSeenAt                string
	EndedAt                   sql.NullString
	ActiveSeconds             int64
	LastPositionMs            int64
	Source                    string
	CreatedAt                 string
	UpdatedAt                 string
	LibraryID                 string
	LibraryName               string
	StreamContainer           sql.NullString
	StreamVideoCodec          sql.NullString
	StreamAudioCodec          sql.NullString
	StreamBitrate             sql.NullInt64
	StreamWidth               sql.NullInt64
	StreamHeight              sql.NullInt64
	StreamFramerateHundredths sql.NullInt64
	StreamAudioChannels       sql.NullInt64
	StreamIsVideoDirect       sql.NullInt64
	StreamIsAudioDirect       sql.NullInt64
	StreamTranscodeReasons    sql.NullString
	RuntimeMs                 sql.NullInt64
	ImportRecordID            sql.NullString
	SeriesID                  sql.NullString
	ImportSource              sql.NullString
	ImportProvenanceGuard     sql.NullInt64
	ImportOriginRecordID      sql.NullString
}

type WatchPosition struct {
	WatchID                   string
	ObservedAt                string
	PositionMs                int64
	Paused                    int64
	PlayMethod                string
	Source                    string
	StreamContainer           sql.NullString
	StreamVideoCodec          sql.NullString
	StreamAudioCodec          sql.NullString
	StreamBitrate             sql.NullInt64
	StreamWidth               sql.NullInt64
	StreamHeight              sql.NullInt64
	StreamFramerateHundredths sql.NullInt64
	StreamAudioChannels       sql.NullInt64
	StreamIsVideoDirect       sql.NullInt64
	StreamIsAudioDirect       sql.NullInt64
	StreamTranscodeReasons    sql.NullString
	IsTransition              int64
}

type WatchSegment struct {
	WatchID   string
	StartedAt string
	EndedAt   sql.NullString
	Source    string
}
