// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package sqlite

import (
	"context"
	"database/sql"
)

const addNotificationSubscription = `-- name: AddNotificationSubscription :exec
INSERT INTO notification_channel_subscriptions (channel_id, event_type)
VALUES (?1, ?2)
`

type AddNotificationSubscriptionParams struct {
	ChannelID string
	EventType string
}

func (q *Queries) AddNotificationSubscription(ctx context.Context, arg AddNotificationSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, addNotificationSubscription, arg.ChannelID, arg.EventType)
	return err
}

const claimNotificationOutbox = `-- name: ClaimNotificationOutbox :one
UPDATE notification_outbox SET
    lease_token = ?1, lease_expires_at = ?2,
    attempts = attempts + 1, updated_at = ?3
WHERE id = (
	SELECT candidate.id FROM notification_outbox AS candidate
	JOIN notification_channels AS channel ON channel.id = candidate.channel_id
	WHERE candidate.channel_id = ?4
	  AND candidate.status = 'pending' AND candidate.next_attempt_at <= ?5
	  AND channel.enabled = TRUE AND channel.deleted_at IS NULL
	  AND candidate.attempts < 8
	  AND (candidate.lease_token = '' OR candidate.lease_expires_at <= ?5)
	ORDER BY candidate.next_attempt_at, candidate.created_at, candidate.id LIMIT 1
)
AND status = 'pending' AND next_attempt_at <= ?5
AND channel_id = ?4
AND attempts < 8
AND (lease_token = '' OR lease_expires_at <= ?5)
AND EXISTS (
	SELECT 1 FROM notification_channels AS channel
	WHERE channel.id = ?4 AND channel.enabled = TRUE AND channel.deleted_at IS NULL
)
RETURNING id, event_id, channel_id, channel_kind, event_type, payload_json, status, attempts,
          next_attempt_at, lease_token, lease_expires_at, last_error, sent_at, created_at, updated_at
`

type ClaimNotificationOutboxParams struct {
	LeaseToken     string
	LeaseExpiresAt sql.NullString
	UpdatedAt      string
	ChannelID      string
	DueAt          string
}

func (q *Queries) ClaimNotificationOutbox(ctx context.Context, arg ClaimNotificationOutboxParams) (NotificationOutbox, error) {
	row := q.db.QueryRowContext(ctx, claimNotificationOutbox,
		arg.LeaseToken,
		arg.LeaseExpiresAt,
		arg.UpdatedAt,
		arg.ChannelID,
		arg.DueAt,
	)
	var i NotificationOutbox
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.ChannelID,
		&i.ChannelKind,
		&i.EventType,
		&i.PayloadJson,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LeaseToken,
		&i.LeaseExpiresAt,
		&i.LastError,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeNotificationOutbox = `-- name: CompleteNotificationOutbox :execrows
UPDATE notification_outbox SET status = 'sent', sent_at = ?1,
    lease_token = '', lease_expires_at = NULL, last_error = '', updated_at = ?1
WHERE id = ?2 AND status = 'pending' AND lease_token = ?3
`

type CompleteNotificationOutboxParams struct {
	SentAt     sql.NullString
	ID         string
	LeaseToken string
}

func (q *Queries) CompleteNotificationOutbox(ctx context.Context, arg CompleteNotificationOutboxParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeNotificationOutbox, arg.SentAt, arg.ID, arg.LeaseToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createNotificationChannel = `-- name: CreateNotificationChannel :exec

INSERT INTO notification_channels (
    id, kind, name, name_key, target, settings_json, secret_ciphertext, key_id,
    enabled, degraded_at, consecutive_failures, created_at, updated_at
) VALUES (
    ?1, ?2, ?3, ?4, ?5,
    ?6, ?7, ?8, ?9,
    ?10, ?11, ?12, ?13
)
`

type CreateNotificationChannelParams struct {
	ID                  string
	Kind                string
	Name                string
	NameKey             string
	Target              string
	SettingsJson        string
	SecretCiphertext    []byte
	KeyID               string
	Enabled             int64
	DegradedAt          sql.NullString
	ConsecutiveFailures int64
	CreatedAt           string
	UpdatedAt           string
}

// Notification channel and durable outbox queries shared by both engines.
func (q *Queries) CreateNotificationChannel(ctx context.Context, arg CreateNotificationChannelParams) error {
	_, err := q.db.ExecContext(ctx, createNotificationChannel,
		arg.ID,
		arg.Kind,
		arg.Name,
		arg.NameKey,
		arg.Target,
		arg.SettingsJson,
		arg.SecretCiphertext,
		arg.KeyID,
		arg.Enabled,
		arg.DegradedAt,
		arg.ConsecutiveFailures,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createNotificationEvent = `-- name: CreateNotificationEvent :exec
INSERT INTO notification_events (
    id, event_type, request_id, requester_id, actor_id, media_kind, title,
    request_status, reason, event_sequence, occurred_at, fanned_at, created_at
) VALUES (
    ?1, ?2, ?3, ?4,
    ?5, ?6, ?7, ?8,
    ?9, ?10, ?11, NULL, ?12
)
`

type CreateNotificationEventParams struct {
	ID            string
	EventType     string
	RequestID     string
	RequesterID   string
	ActorID       string
	MediaKind     string
	Title         string
	RequestStatus string
	Reason        string
	EventSequence int64
	OccurredAt    string
	CreatedAt     string
}

func (q *Queries) CreateNotificationEvent(ctx context.Context, arg CreateNotificationEventParams) error {
	_, err := q.db.ExecContext(ctx, createNotificationEvent,
		arg.ID,
		arg.EventType,
		arg.RequestID,
		arg.RequesterID,
		arg.ActorID,
		arg.MediaKind,
		arg.Title,
		arg.RequestStatus,
		arg.Reason,
		arg.EventSequence,
		arg.OccurredAt,
		arg.CreatedAt,
	)
	return err
}

const createNotificationOutbox = `-- name: CreateNotificationOutbox :exec
INSERT INTO notification_outbox (
    id, event_id, channel_id, channel_kind, event_type, payload_json, status, attempts,
    next_attempt_at, lease_token, lease_expires_at, last_error, sent_at, created_at, updated_at
) VALUES (
    ?1, ?2, ?3, ?4, ?5,
    ?6, 'pending', 0, ?7, '', NULL, '', NULL,
    ?8, ?9
)
`

type CreateNotificationOutboxParams struct {
	ID            string
	EventID       string
	ChannelID     string
	ChannelKind   string
	EventType     string
	PayloadJson   string
	NextAttemptAt string
	CreatedAt     string
	UpdatedAt     string
}

func (q *Queries) CreateNotificationOutbox(ctx context.Context, arg CreateNotificationOutboxParams) error {
	_, err := q.db.ExecContext(ctx, createNotificationOutbox,
		arg.ID,
		arg.EventID,
		arg.ChannelID,
		arg.ChannelKind,
		arg.EventType,
		arg.PayloadJson,
		arg.NextAttemptAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteNotificationChannel = `-- name: DeleteNotificationChannel :execrows
UPDATE notification_channels SET enabled = FALSE, deleted_at = ?1,
    updated_at = ?1
WHERE id = ?2 AND deleted_at IS NULL
`

type DeleteNotificationChannelParams struct {
	DeletedAt sql.NullString
	ID        string
}

func (q *Queries) DeleteNotificationChannel(ctx context.Context, arg DeleteNotificationChannelParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteNotificationChannel, arg.DeletedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteNotificationSubscriptions = `-- name: DeleteNotificationSubscriptions :exec
DELETE FROM notification_channel_subscriptions WHERE channel_id = ?1
`

func (q *Queries) DeleteNotificationSubscriptions(ctx context.Context, channelID string) error {
	_, err := q.db.ExecContext(ctx, deleteNotificationSubscriptions, channelID)
	return err
}

const deleteTombstonedNotificationChannel = `-- name: DeleteTombstonedNotificationChannel :execrows
DELETE FROM notification_channels
WHERE notification_channels.id = ?1 AND notification_channels.deleted_at IS NOT NULL
  AND NOT EXISTS (
	SELECT 1 FROM notification_outbox AS delivery
	WHERE delivery.channel_id = notification_channels.id AND delivery.status = 'pending'
	  AND delivery.lease_token <> '' AND delivery.lease_expires_at > ?2
  )
`

type DeleteTombstonedNotificationChannelParams struct {
	ID string
	At sql.NullString
}

func (q *Queries) DeleteTombstonedNotificationChannel(ctx context.Context, arg DeleteTombstonedNotificationChannelParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTombstonedNotificationChannel, arg.ID, arg.At)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const failExpiredExhaustedNotificationOutbox = `-- name: FailExpiredExhaustedNotificationOutbox :execrows
UPDATE notification_outbox SET status = 'failed', lease_token = '', lease_expires_at = NULL,
    last_error = 'attempt limit reached', updated_at = ?1
WHERE status = 'pending' AND attempts >= 8
  AND (lease_token = '' OR lease_expires_at <= ?1)
`

func (q *Queries) FailExpiredExhaustedNotificationOutbox(ctx context.Context, updatedAt string) (int64, error) {
	result, err := q.db.ExecContext(ctx, failExpiredExhaustedNotificationOutbox, updatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const failPendingNotificationDeliveriesForChannel = `-- name: FailPendingNotificationDeliveriesForChannel :execrows
UPDATE notification_outbox SET status = 'failed', lease_token = '', lease_expires_at = NULL,
    last_error = 'channel disabled', updated_at = ?1
WHERE channel_id = ?2 AND status = 'pending'
  AND (lease_token = '' OR lease_expires_at <= ?1)
`

type FailPendingNotificationDeliveriesForChannelParams struct {
	UpdatedAt string
	ChannelID string
}

func (q *Queries) FailPendingNotificationDeliveriesForChannel(ctx context.Context, arg FailPendingNotificationDeliveriesForChannelParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, failPendingNotificationDeliveriesForChannel, arg.UpdatedAt, arg.ChannelID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getNotificationChannel = `-- name: GetNotificationChannel :one
SELECT id, kind, name, target, settings_json, secret_ciphertext, key_id, enabled,
       degraded_at, consecutive_failures, created_at, updated_at
FROM notification_channels WHERE id = ?1 AND deleted_at IS NULL
`

type GetNotificationChannelRow struct {
	ID                  string
	Kind                string
	Name                string
	Target              string
	SettingsJson        string
	SecretCiphertext    []byte
	KeyID               string
	Enabled             int64
	DegradedAt          sql.NullString
	ConsecutiveFailures int64
	CreatedAt           string
	UpdatedAt           string
}

func (q *Queries) GetNotificationChannel(ctx context.Context, id string) (GetNotificationChannelRow, error) {
	row := q.db.QueryRowContext(ctx, getNotificationChannel, id)
	var i GetNotificationChannelRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Target,
		&i.SettingsJson,
		&i.SecretCiphertext,
		&i.KeyID,
		&i.Enabled,
		&i.DegradedAt,
		&i.ConsecutiveFailures,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotificationSubscriptions = `-- name: GetNotificationSubscriptions :many
SELECT event_type FROM notification_channel_subscriptions
WHERE channel_id = ?1 ORDER BY event_type
`

func (q *Queries) GetNotificationSubscriptions(ctx context.Context, channelID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getNotificationSubscriptions, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var event_type string
		if err := rows.Scan(&event_type); err != nil {
			return nil, err
		}
		items = append(items, event_type)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnfannedNotificationEvent = `-- name: GetUnfannedNotificationEvent :one
SELECT id, event_type, request_id, requester_id, actor_id, media_kind, title,
       request_status, reason, event_sequence, occurred_at, fanned_at, created_at
FROM notification_events
WHERE fanned_at IS NULL
ORDER BY created_at, event_sequence, id LIMIT 1
`

func (q *Queries) GetUnfannedNotificationEvent(ctx context.Context) (NotificationEvent, error) {
	row := q.db.QueryRowContext(ctx, getUnfannedNotificationEvent)
	var i NotificationEvent
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.RequestID,
		&i.RequesterID,
		&i.ActorID,
		&i.MediaKind,
		&i.Title,
		&i.RequestStatus,
		&i.Reason,
		&i.EventSequence,
		&i.OccurredAt,
		&i.FannedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listNotificationChannels = `-- name: ListNotificationChannels :many
SELECT id, kind, name, target, settings_json, enabled, degraded_at,
       consecutive_failures, created_at, updated_at
FROM notification_channels
WHERE deleted_at IS NULL AND name_key > ?1
ORDER BY name_key, id LIMIT ?2
`

type ListNotificationChannelsParams struct {
	AfterNameKey string
	PageSize     int64
}

type ListNotificationChannelsRow struct {
	ID                  string
	Kind                string
	Name                string
	Target              string
	SettingsJson        string
	Enabled             int64
	DegradedAt          sql.NullString
	ConsecutiveFailures int64
	CreatedAt           string
	UpdatedAt           string
}

func (q *Queries) ListNotificationChannels(ctx context.Context, arg ListNotificationChannelsParams) ([]ListNotificationChannelsRow, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationChannels, arg.AfterNameKey, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotificationChannelsRow{}
	for rows.Next() {
		var i ListNotificationChannelsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.Target,
			&i.SettingsJson,
			&i.Enabled,
			&i.DegradedAt,
			&i.ConsecutiveFailures,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationDeliveries = `-- name: ListNotificationDeliveries :many
SELECT id, event_id, channel_id, channel_kind, event_type, payload_json, status, attempts,
       next_attempt_at, lease_token, lease_expires_at, last_error, sent_at, created_at, updated_at
FROM notification_outbox
WHERE channel_id = ?1
  AND (created_at < ?2
       OR (created_at = ?2 AND id < ?3))
ORDER BY created_at DESC, id DESC LIMIT ?4
`

type ListNotificationDeliveriesParams struct {
	ChannelID      string
	AfterCreatedAt string
	AfterID        string
	PageSize       int64
}

func (q *Queries) ListNotificationDeliveries(ctx context.Context, arg ListNotificationDeliveriesParams) ([]NotificationOutbox, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationDeliveries,
		arg.ChannelID,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationOutbox{}
	for rows.Next() {
		var i NotificationOutbox
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.ChannelID,
			&i.ChannelKind,
			&i.EventType,
			&i.PayloadJson,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LeaseToken,
			&i.LeaseExpiresAt,
			&i.LastError,
			&i.SentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscribedNotificationChannels = `-- name: ListSubscribedNotificationChannels :many
SELECT c.id, c.kind FROM notification_channels c
JOIN notification_channel_subscriptions s ON s.channel_id = c.id
WHERE c.enabled = ?1 AND c.deleted_at IS NULL
  AND s.event_type = ?2
ORDER BY c.id
`

type ListSubscribedNotificationChannelsParams struct {
	Enabled   int64
	EventType string
}

type ListSubscribedNotificationChannelsRow struct {
	ID   string
	Kind string
}

func (q *Queries) ListSubscribedNotificationChannels(ctx context.Context, arg ListSubscribedNotificationChannelsParams) ([]ListSubscribedNotificationChannelsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSubscribedNotificationChannels, arg.Enabled, arg.EventType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubscribedNotificationChannelsRow{}
	for rows.Next() {
		var i ListSubscribedNotificationChannelsRow
		if err := rows.Scan(&i.ID, &i.Kind); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationEventFanned = `-- name: MarkNotificationEventFanned :execrows
UPDATE notification_events SET fanned_at = ?1
WHERE id = ?2 AND fanned_at IS NULL
`

type MarkNotificationEventFannedParams struct {
	FannedAt sql.NullString
	ID       string
}

func (q *Queries) MarkNotificationEventFanned(ctx context.Context, arg MarkNotificationEventFannedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markNotificationEventFanned, arg.FannedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const notificationOutboxDepth = `-- name: NotificationOutboxDepth :one
SELECT COUNT(*) FROM notification_outbox WHERE status = 'pending'
`

func (q *Queries) NotificationOutboxDepth(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, notificationOutboxDepth)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const pruneNotificationEvents = `-- name: PruneNotificationEvents :execrows
DELETE FROM notification_events WHERE id IN (
	SELECT candidate.id FROM notification_events AS candidate
	WHERE candidate.fanned_at IS NOT NULL AND candidate.fanned_at < ?1
	  AND NOT EXISTS (SELECT 1 FROM notification_outbox AS delivery WHERE delivery.event_id = candidate.id)
	ORDER BY candidate.fanned_at, candidate.id LIMIT ?2
)
`

type PruneNotificationEventsParams struct {
	BeforeAt  sql.NullString
	BatchSize int64
}

func (q *Queries) PruneNotificationEvents(ctx context.Context, arg PruneNotificationEventsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneNotificationEvents, arg.BeforeAt, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const pruneNotificationOutbox = `-- name: PruneNotificationOutbox :execrows
DELETE FROM notification_outbox WHERE id IN (
	SELECT candidate.id FROM notification_outbox AS candidate
	WHERE candidate.status IN ('sent', 'failed') AND candidate.updated_at < ?1
	ORDER BY candidate.updated_at, candidate.id LIMIT ?2
)
`

type PruneNotificationOutboxParams struct {
	BeforeAt  string
	BatchSize int64
}

func (q *Queries) PruneNotificationOutbox(ctx context.Context, arg PruneNotificationOutboxParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneNotificationOutbox, arg.BeforeAt, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recordNotificationChannelSuccess = `-- name: RecordNotificationChannelSuccess :execrows
UPDATE notification_channels SET consecutive_failures = 0, degraded_at = NULL,
    updated_at = ?1 WHERE id = ?2
`

type RecordNotificationChannelSuccessParams struct {
	UpdatedAt string
	ID        string
}

func (q *Queries) RecordNotificationChannelSuccess(ctx context.Context, arg RecordNotificationChannelSuccessParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, recordNotificationChannelSuccess, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recordNotificationChannelTerminalFailure = `-- name: RecordNotificationChannelTerminalFailure :execrows
UPDATE notification_channels SET consecutive_failures = consecutive_failures + 1,
    degraded_at = CASE WHEN consecutive_failures + 1 >= ?1
        THEN COALESCE(degraded_at, ?2) ELSE degraded_at END,
    updated_at = ?2 WHERE id = ?3
`

type RecordNotificationChannelTerminalFailureParams struct {
	DegradedAfter int64
	UpdatedAt     string
	ID            string
}

func (q *Queries) RecordNotificationChannelTerminalFailure(ctx context.Context, arg RecordNotificationChannelTerminalFailureParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, recordNotificationChannelTerminalFailure, arg.DegradedAfter, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const rescheduleNotificationOutbox = `-- name: RescheduleNotificationOutbox :execrows
UPDATE notification_outbox SET status = ?1, next_attempt_at = ?2,
    lease_token = '', lease_expires_at = NULL, last_error = ?3,
    updated_at = ?4
WHERE id = ?5 AND status = 'pending' AND lease_token = ?6
`

type RescheduleNotificationOutboxParams struct {
	Status        string
	NextAttemptAt string
	LastError     string
	UpdatedAt     string
	ID            string
	LeaseToken    string
}

func (q *Queries) RescheduleNotificationOutbox(ctx context.Context, arg RescheduleNotificationOutboxParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, rescheduleNotificationOutbox,
		arg.Status,
		arg.NextAttemptAt,
		arg.LastError,
		arg.UpdatedAt,
		arg.ID,
		arg.LeaseToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateNotificationChannel = `-- name: UpdateNotificationChannel :execrows
UPDATE notification_channels SET
    kind = ?1, name = ?2, name_key = ?3,
    target = ?4, settings_json = ?5,
    secret_ciphertext = ?6, key_id = ?7,
    enabled = ?8, updated_at = ?9
WHERE id = ?10 AND deleted_at IS NULL
`

type UpdateNotificationChannelParams struct {
	Kind             string
	Name             string
	NameKey          string
	Target           string
	SettingsJson     string
	SecretCiphertext []byte
	KeyID            string
	Enabled          int64
	UpdatedAt        string
	ID               string
}

func (q *Queries) UpdateNotificationChannel(ctx context.Context, arg UpdateNotificationChannelParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateNotificationChannel,
		arg.Kind,
		arg.Name,
		arg.NameKey,
		arg.Target,
		arg.SettingsJson,
		arg.SecretCiphertext,
		arg.KeyID,
		arg.Enabled,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
