// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: playback.sql

package sqlite

import (
	"context"
	"database/sql"
)

const backfillWatchLibrary = `-- name: BackfillWatchLibrary :execrows
UPDATE watches
SET library_id = ?1, library_name = ?2
WHERE media_server_id = ?3
  AND item_id = ?4
  AND library_id = ''
`

type BackfillWatchLibraryParams struct {
	LibraryID     string
	LibraryName   string
	MediaServerID string
	ItemID        string
}

func (q *Queries) BackfillWatchLibrary(ctx context.Context, arg BackfillWatchLibraryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, backfillWatchLibrary,
		arg.LibraryID,
		arg.LibraryName,
		arg.MediaServerID,
		arg.ItemID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const closeOpenWatchSegment = `-- name: CloseOpenWatchSegment :execrows
UPDATE watch_segments
SET ended_at = ?1
WHERE watch_id = ?2 AND ended_at IS NULL
`

type CloseOpenWatchSegmentParams struct {
	EndedAt sql.NullString
	WatchID string
}

func (q *Queries) CloseOpenWatchSegment(ctx context.Context, arg CloseOpenWatchSegmentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, closeOpenWatchSegment, arg.EndedAt, arg.WatchID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createWatchSegment = `-- name: CreateWatchSegment :exec
INSERT INTO watch_segments (watch_id, started_at, ended_at, source)
VALUES (?1, ?2, NULL, ?3)
ON CONFLICT (watch_id, started_at) DO NOTHING
`

type CreateWatchSegmentParams struct {
	WatchID   string
	StartedAt string
	Source    string
}

func (q *Queries) CreateWatchSegment(ctx context.Context, arg CreateWatchSegmentParams) error {
	_, err := q.db.ExecContext(ctx, createWatchSegment, arg.WatchID, arg.StartedAt, arg.Source)
	return err
}

const findRecentPlaybackWatch = `-- name: FindRecentPlaybackWatch :one
SELECT w.id, w.media_server_id, w.media_user_id, w.username, w.device_id, w.device_name, w.client, w.server_session_id, w.item_id, w.item_name, w.item_type, w.series_name, w.season_number, w.episode_number, w.play_method, w.state, w.started_at, w.last_seen_at, w.ended_at, w.active_seconds, w.last_position_ms, w.source, w.created_at, w.updated_at, w.library_id, w.library_name, ms.name AS media_server_name
FROM watches w
JOIN media_servers ms ON ms.id = w.media_server_id
WHERE w.state = 'stopped'
  AND w.media_server_id = ?1
  AND w.media_user_id = ?2
  AND w.device_id = ?3
  AND w.item_id = ?4
  AND (w.server_session_id = ?5
       OR w.server_session_id = '' OR ?5 = '')
  AND w.ended_at >= ?6
ORDER BY w.ended_at DESC, w.id DESC
LIMIT 1
`

type FindRecentPlaybackWatchParams struct {
	MediaServerID   string
	MediaUserID     string
	DeviceID        string
	ItemID          string
	ServerSessionID string
	EndedAfter      sql.NullString
}

type FindRecentPlaybackWatchRow struct {
	ID              string
	MediaServerID   string
	MediaUserID     string
	Username        string
	DeviceID        string
	DeviceName      string
	Client          string
	ServerSessionID string
	ItemID          string
	ItemName        string
	ItemType        string
	SeriesName      string
	SeasonNumber    sql.NullInt64
	EpisodeNumber   sql.NullInt64
	PlayMethod      string
	State           string
	StartedAt       string
	LastSeenAt      string
	EndedAt         sql.NullString
	ActiveSeconds   int64
	LastPositionMs  int64
	Source          string
	CreatedAt       string
	UpdatedAt       string
	LibraryID       string
	LibraryName     string
	MediaServerName string
}

func (q *Queries) FindRecentPlaybackWatch(ctx context.Context, arg FindRecentPlaybackWatchParams) (FindRecentPlaybackWatchRow, error) {
	row := q.db.QueryRowContext(ctx, findRecentPlaybackWatch,
		arg.MediaServerID,
		arg.MediaUserID,
		arg.DeviceID,
		arg.ItemID,
		arg.ServerSessionID,
		arg.EndedAfter,
	)
	var i FindRecentPlaybackWatchRow
	err := row.Scan(
		&i.ID,
		&i.MediaServerID,
		&i.MediaUserID,
		&i.Username,
		&i.DeviceID,
		&i.DeviceName,
		&i.Client,
		&i.ServerSessionID,
		&i.ItemID,
		&i.ItemName,
		&i.ItemType,
		&i.SeriesName,
		&i.SeasonNumber,
		&i.EpisodeNumber,
		&i.PlayMethod,
		&i.State,
		&i.StartedAt,
		&i.LastSeenAt,
		&i.EndedAt,
		&i.ActiveSeconds,
		&i.LastPositionMs,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LibraryID,
		&i.LibraryName,
		&i.MediaServerName,
	)
	return i, err
}

const listNowPlaying = `-- name: ListNowPlaying :many
SELECT w.id, w.media_server_id, w.media_user_id, w.username, w.device_id, w.device_name, w.client, w.server_session_id, w.item_id, w.item_name, w.item_type, w.series_name, w.season_number, w.episode_number, w.play_method, w.state, w.started_at, w.last_seen_at, w.ended_at, w.active_seconds, w.last_position_ms, w.source, w.created_at, w.updated_at, w.library_id, w.library_name, ms.name AS media_server_name
FROM watches w
JOIN media_servers ms ON ms.id = w.media_server_id
WHERE w.state <> 'stopped'
  AND (w.started_at < ?1
       OR (w.started_at = ?1 AND w.id < ?2))
ORDER BY w.started_at DESC, w.id DESC
LIMIT ?3
`

type ListNowPlayingParams struct {
	BeforeStartedAt string
	BeforeID        string
	PageSize        int64
}

type ListNowPlayingRow struct {
	ID              string
	MediaServerID   string
	MediaUserID     string
	Username        string
	DeviceID        string
	DeviceName      string
	Client          string
	ServerSessionID string
	ItemID          string
	ItemName        string
	ItemType        string
	SeriesName      string
	SeasonNumber    sql.NullInt64
	EpisodeNumber   sql.NullInt64
	PlayMethod      string
	State           string
	StartedAt       string
	LastSeenAt      string
	EndedAt         sql.NullString
	ActiveSeconds   int64
	LastPositionMs  int64
	Source          string
	CreatedAt       string
	UpdatedAt       string
	LibraryID       string
	LibraryName     string
	MediaServerName string
}

func (q *Queries) ListNowPlaying(ctx context.Context, arg ListNowPlayingParams) ([]ListNowPlayingRow, error) {
	rows, err := q.db.QueryContext(ctx, listNowPlaying, arg.BeforeStartedAt, arg.BeforeID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNowPlayingRow{}
	for rows.Next() {
		var i ListNowPlayingRow
		if err := rows.Scan(
			&i.ID,
			&i.MediaServerID,
			&i.MediaUserID,
			&i.Username,
			&i.DeviceID,
			&i.DeviceName,
			&i.Client,
			&i.ServerSessionID,
			&i.ItemID,
			&i.ItemName,
			&i.ItemType,
			&i.SeriesName,
			&i.SeasonNumber,
			&i.EpisodeNumber,
			&i.PlayMethod,
			&i.State,
			&i.StartedAt,
			&i.LastSeenAt,
			&i.EndedAt,
			&i.ActiveSeconds,
			&i.LastPositionMs,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LibraryID,
			&i.LibraryName,
			&i.MediaServerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenPlaybackWatches = `-- name: ListOpenPlaybackWatches :many
SELECT w.id, w.media_server_id, w.media_user_id, w.username, w.device_id, w.device_name, w.client, w.server_session_id, w.item_id, w.item_name, w.item_type, w.series_name, w.season_number, w.episode_number, w.play_method, w.state, w.started_at, w.last_seen_at, w.ended_at, w.active_seconds, w.last_position_ms, w.source, w.created_at, w.updated_at, w.library_id, w.library_name, ms.name AS media_server_name
FROM watches w
JOIN media_servers ms ON ms.id = w.media_server_id
WHERE w.media_server_id = ?1 AND w.state <> 'stopped'
ORDER BY w.started_at, w.id
LIMIT 102400
`

type ListOpenPlaybackWatchesRow struct {
	ID              string
	MediaServerID   string
	MediaUserID     string
	Username        string
	DeviceID        string
	DeviceName      string
	Client          string
	ServerSessionID string
	ItemID          string
	ItemName        string
	ItemType        string
	SeriesName      string
	SeasonNumber    sql.NullInt64
	EpisodeNumber   sql.NullInt64
	PlayMethod      string
	State           string
	StartedAt       string
	LastSeenAt      string
	EndedAt         sql.NullString
	ActiveSeconds   int64
	LastPositionMs  int64
	Source          string
	CreatedAt       string
	UpdatedAt       string
	LibraryID       string
	LibraryName     string
	MediaServerName string
}

func (q *Queries) ListOpenPlaybackWatches(ctx context.Context, mediaServerID string) ([]ListOpenPlaybackWatchesRow, error) {
	rows, err := q.db.QueryContext(ctx, listOpenPlaybackWatches, mediaServerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenPlaybackWatchesRow{}
	for rows.Next() {
		var i ListOpenPlaybackWatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.MediaServerID,
			&i.MediaUserID,
			&i.Username,
			&i.DeviceID,
			&i.DeviceName,
			&i.Client,
			&i.ServerSessionID,
			&i.ItemID,
			&i.ItemName,
			&i.ItemType,
			&i.SeriesName,
			&i.SeasonNumber,
			&i.EpisodeNumber,
			&i.PlayMethod,
			&i.State,
			&i.StartedAt,
			&i.LastSeenAt,
			&i.EndedAt,
			&i.ActiveSeconds,
			&i.LastPositionMs,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LibraryID,
			&i.LibraryName,
			&i.MediaServerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaybackHistory = `-- name: ListPlaybackHistory :many
SELECT w.id, w.media_server_id, w.media_user_id, w.username, w.device_id, w.device_name, w.client, w.server_session_id, w.item_id, w.item_name, w.item_type, w.series_name, w.season_number, w.episode_number, w.play_method, w.state, w.started_at, w.last_seen_at, w.ended_at, w.active_seconds, w.last_position_ms, w.source, w.created_at, w.updated_at, w.library_id, w.library_name, ms.name AS media_server_name
FROM watches w
JOIN media_servers ms ON ms.id = w.media_server_id
WHERE w.state = 'stopped'
  AND (CAST(?1 AS TEXT) = ''
       OR w.media_server_id = CAST(?1 AS TEXT))
  AND (w.started_at < ?2
       OR (w.started_at = ?2 AND w.id < ?3))
ORDER BY w.started_at DESC, w.id DESC
LIMIT ?4
`

type ListPlaybackHistoryParams struct {
	MediaServerFilter string
	BeforeStartedAt   string
	BeforeID          string
	PageSize          int64
}

type ListPlaybackHistoryRow struct {
	ID              string
	MediaServerID   string
	MediaUserID     string
	Username        string
	DeviceID        string
	DeviceName      string
	Client          string
	ServerSessionID string
	ItemID          string
	ItemName        string
	ItemType        string
	SeriesName      string
	SeasonNumber    sql.NullInt64
	EpisodeNumber   sql.NullInt64
	PlayMethod      string
	State           string
	StartedAt       string
	LastSeenAt      string
	EndedAt         sql.NullString
	ActiveSeconds   int64
	LastPositionMs  int64
	Source          string
	CreatedAt       string
	UpdatedAt       string
	LibraryID       string
	LibraryName     string
	MediaServerName string
}

func (q *Queries) ListPlaybackHistory(ctx context.Context, arg ListPlaybackHistoryParams) ([]ListPlaybackHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlaybackHistory,
		arg.MediaServerFilter,
		arg.BeforeStartedAt,
		arg.BeforeID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlaybackHistoryRow{}
	for rows.Next() {
		var i ListPlaybackHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.MediaServerID,
			&i.MediaUserID,
			&i.Username,
			&i.DeviceID,
			&i.DeviceName,
			&i.Client,
			&i.ServerSessionID,
			&i.ItemID,
			&i.ItemName,
			&i.ItemType,
			&i.SeriesName,
			&i.SeasonNumber,
			&i.EpisodeNumber,
			&i.PlayMethod,
			&i.State,
			&i.StartedAt,
			&i.LastSeenAt,
			&i.EndedAt,
			&i.ActiveSeconds,
			&i.LastPositionMs,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LibraryID,
			&i.LibraryName,
			&i.MediaServerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentPlaybackWatches = `-- name: ListRecentPlaybackWatches :many
SELECT w.id, w.media_server_id, w.media_user_id, w.username, w.device_id, w.device_name, w.client, w.server_session_id, w.item_id, w.item_name, w.item_type, w.series_name, w.season_number, w.episode_number, w.play_method, w.state, w.started_at, w.last_seen_at, w.ended_at, w.active_seconds, w.last_position_ms, w.source, w.created_at, w.updated_at, w.library_id, w.library_name, ms.name AS media_server_name
FROM watches w
JOIN media_servers ms ON ms.id = w.media_server_id
WHERE w.state = 'stopped'
  AND w.media_server_id = ?1
  AND w.ended_at >= ?2
ORDER BY w.ended_at DESC, w.id DESC
LIMIT ?3
`

type ListRecentPlaybackWatchesParams struct {
	MediaServerID string
	EndedAfter    sql.NullString
	PageSize      int64
}

type ListRecentPlaybackWatchesRow struct {
	ID              string
	MediaServerID   string
	MediaUserID     string
	Username        string
	DeviceID        string
	DeviceName      string
	Client          string
	ServerSessionID string
	ItemID          string
	ItemName        string
	ItemType        string
	SeriesName      string
	SeasonNumber    sql.NullInt64
	EpisodeNumber   sql.NullInt64
	PlayMethod      string
	State           string
	StartedAt       string
	LastSeenAt      string
	EndedAt         sql.NullString
	ActiveSeconds   int64
	LastPositionMs  int64
	Source          string
	CreatedAt       string
	UpdatedAt       string
	LibraryID       string
	LibraryName     string
	MediaServerName string
}

func (q *Queries) ListRecentPlaybackWatches(ctx context.Context, arg ListRecentPlaybackWatchesParams) ([]ListRecentPlaybackWatchesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentPlaybackWatches, arg.MediaServerID, arg.EndedAfter, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentPlaybackWatchesRow{}
	for rows.Next() {
		var i ListRecentPlaybackWatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.MediaServerID,
			&i.MediaUserID,
			&i.Username,
			&i.DeviceID,
			&i.DeviceName,
			&i.Client,
			&i.ServerSessionID,
			&i.ItemID,
			&i.ItemName,
			&i.ItemType,
			&i.SeriesName,
			&i.SeasonNumber,
			&i.EpisodeNumber,
			&i.PlayMethod,
			&i.State,
			&i.StartedAt,
			&i.LastSeenAt,
			&i.EndedAt,
			&i.ActiveSeconds,
			&i.LastPositionMs,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LibraryID,
			&i.LibraryName,
			&i.MediaServerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnresolvedWatchItemIDs = `-- name: ListUnresolvedWatchItemIDs :many
SELECT w.item_id
FROM watches w
WHERE w.media_server_id = ?1 AND w.library_id = ''
GROUP BY w.item_id
ORDER BY MIN(w.started_at), w.item_id
LIMIT ?2
`

type ListUnresolvedWatchItemIDsParams struct {
	MediaServerID string
	RowLimit      int64
}

func (q *Queries) ListUnresolvedWatchItemIDs(ctx context.Context, arg ListUnresolvedWatchItemIDsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listUnresolvedWatchItemIDs, arg.MediaServerID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var item_id string
		if err := rows.Scan(&item_id); err != nil {
			return nil, err
		}
		items = append(items, item_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trimWatchPositions = `-- name: TrimWatchPositions :exec
DELETE FROM watch_positions
WHERE watch_positions.watch_id = ?1
  AND watch_positions.observed_at NOT IN (
      SELECT kept.observed_at
      FROM watch_positions AS kept
      WHERE kept.watch_id = ?1
      ORDER BY kept.observed_at DESC
      LIMIT 512
  )
`

func (q *Queries) TrimWatchPositions(ctx context.Context, watchID string) error {
	_, err := q.db.ExecContext(ctx, trimWatchPositions, watchID)
	return err
}

const upsertPlaybackWatch = `-- name: UpsertPlaybackWatch :exec

INSERT INTO watches (
    id, media_server_id, media_user_id, username, device_id, device_name, client,
    server_session_id, item_id, item_name, item_type, series_name, library_id,
    library_name, season_number,
    episode_number, play_method, state, started_at, last_seen_at, ended_at,
    active_seconds, last_position_ms, source, created_at, updated_at
) VALUES (
    ?1, ?2, ?3, ?4,
    ?5, ?6, ?7, ?8,
    ?9, ?10, ?11, ?12,
    ?13, ?14,
    ?15, ?16, ?17, ?18,
    ?19, ?20, ?21, ?22,
    ?23, ?24, ?25, ?26
)
ON CONFLICT (id) DO UPDATE SET
    username = excluded.username,
    device_name = excluded.device_name,
    client = excluded.client,
    server_session_id = excluded.server_session_id,
    item_name = excluded.item_name,
    item_type = excluded.item_type,
    series_name = excluded.series_name,
    library_id = CASE WHEN watches.library_id = '' THEN excluded.library_id ELSE watches.library_id END,
    library_name = CASE WHEN watches.library_id = '' THEN excluded.library_name ELSE watches.library_name END,
    season_number = excluded.season_number,
    episode_number = excluded.episode_number,
    play_method = excluded.play_method,
    state = excluded.state,
    last_seen_at = excluded.last_seen_at,
    ended_at = excluded.ended_at,
    active_seconds = excluded.active_seconds,
    last_position_ms = excluded.last_position_ms,
    updated_at = excluded.updated_at
`

type UpsertPlaybackWatchParams struct {
	ID              string
	MediaServerID   string
	MediaUserID     string
	Username        string
	DeviceID        string
	DeviceName      string
	Client          string
	ServerSessionID string
	ItemID          string
	ItemName        string
	ItemType        string
	SeriesName      string
	LibraryID       string
	LibraryName     string
	SeasonNumber    sql.NullInt64
	EpisodeNumber   sql.NullInt64
	PlayMethod      string
	State           string
	StartedAt       string
	LastSeenAt      string
	EndedAt         sql.NullString
	ActiveSeconds   int64
	LastPositionMs  int64
	Source          string
	CreatedAt       string
	UpdatedAt       string
}

// Playback queries are portable across SQLite and PostgreSQL.
func (q *Queries) UpsertPlaybackWatch(ctx context.Context, arg UpsertPlaybackWatchParams) error {
	_, err := q.db.ExecContext(ctx, upsertPlaybackWatch,
		arg.ID,
		arg.MediaServerID,
		arg.MediaUserID,
		arg.Username,
		arg.DeviceID,
		arg.DeviceName,
		arg.Client,
		arg.ServerSessionID,
		arg.ItemID,
		arg.ItemName,
		arg.ItemType,
		arg.SeriesName,
		arg.LibraryID,
		arg.LibraryName,
		arg.SeasonNumber,
		arg.EpisodeNumber,
		arg.PlayMethod,
		arg.State,
		arg.StartedAt,
		arg.LastSeenAt,
		arg.EndedAt,
		arg.ActiveSeconds,
		arg.LastPositionMs,
		arg.Source,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertWatchPosition = `-- name: UpsertWatchPosition :exec
INSERT INTO watch_positions (watch_id, observed_at, position_ms, paused, play_method, source)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
ON CONFLICT (watch_id, observed_at) DO UPDATE SET
    position_ms = excluded.position_ms,
    paused = excluded.paused,
    play_method = excluded.play_method,
    source = excluded.source
`

type UpsertWatchPositionParams struct {
	WatchID    string
	ObservedAt string
	PositionMs int64
	Paused     int64
	PlayMethod string
	Source     string
}

func (q *Queries) UpsertWatchPosition(ctx context.Context, arg UpsertWatchPositionParams) error {
	_, err := q.db.ExecContext(ctx, upsertWatchPosition,
		arg.WatchID,
		arg.ObservedAt,
		arg.PositionMs,
		arg.Paused,
		arg.PlayMethod,
		arg.Source,
	)
	return err
}
