// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlite

import (
	"context"
)

type Querier interface {
	// accounts.sql is the sqlc source of truth for the account store. It is SHARED
	// by both engines (ADR 0004 item 3): sqlc.yaml compiles it once against the
	// SQLite schema into internal/db/sqlite and once against the PostgreSQL schema
	// into internal/db/postgres. Only portable SQL belongs here; named parameters
	// (sqlc.arg) are used because both engines accept them, whereas $1 and ? are
	// engine-specific. Regenerate with: go tool sqlc generate.
	CreateAccount(ctx context.Context, arg CreateAccountParams) error
	GetAccount(ctx context.Context, id string) (GetAccountRow, error)
	GetAccountByUsername(ctx context.Context, usernameKey string) (GetAccountByUsernameRow, error)
	UpdateAccountPasswordHash(ctx context.Context, arg UpdateAccountPasswordHashParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
