// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: requests_sqlite.sql

package sqlite

import (
	"context"
)

const lockAccountRequestQuota = `-- name: LockAccountRequestQuota :exec
SELECT 1
FROM accounts
WHERE id = ?1
`

func (q *Queries) LockAccountRequestQuota(ctx context.Context, accountID string) error {
	_, err := q.db.ExecContext(ctx, lockAccountRequestQuota, accountID)
	return err
}
