// Package core holds Bloom's domain types and the contracts it consumes. It
// depends only on the standard library and narrowly scoped seams; it imports no
// transport or storage-implementation packages, per the handbook's
// foundations/package-design.md and the pluggable-boundaries principle in
// docs/requirements.md.
//
// Store interfaces are defined HERE, in the consumer, and name what the domain
// needs, not what an implementer is. Both engine adapters (SQLite and
// PostgreSQL, ADR 0004) live in internal/db and satisfy them structurally.
package core

import (
	"context"
	"errors"
	"time"
)

// Sentinel errors callers (notably the HTTP layer) branch on with errors.Is.
// They are part of the package contract.
var (
	// ErrNotFound is returned when a requested entity does not exist.
	ErrNotFound = errors.New("not found")
	// ErrAlreadyExists is returned when creating an entity whose unique key is
	// already taken (an account id or username).
	ErrAlreadyExists = errors.New("already exists")
	// ErrInvalidArgument is returned when input fails domain validation.
	ErrInvalidArgument = errors.New("invalid argument")
)

// Account is the Bloom principal (ADR 0006 item 1): every human or API caller
// is an account; media-server users are linked identities on it, never the
// account itself. This is the minimal shape needed to establish the two-engine
// storage pattern; credentials, roles, and linked identities arrive with the
// auth work.
type Account struct {
	// ID is a UUID string, generated by Bloom (NewID), never by the database, so
	// both engines store the same value and no engine-specific id type leaks.
	ID string
	// Username is unique across accounts.
	Username string
	// CreatedAt is the UTC creation instant at microsecond precision, which is
	// the finest resolution both engines round-trip without loss (ADR 0004
	// item 5): PostgreSQL TIMESTAMPTZ carries microseconds; the SQLite adapter
	// stores RFC 3339 text with six fractional digits.
	CreatedAt time.Time
}

// AccountStore is the persistence contract for accounts. It is intentionally
// narrow (interface-at-consumer, 1-3 methods per the handbook); implementations
// live in internal/db, one per engine, adapted from sqlc output.
type AccountStore interface {
	// CreateAccount persists a new account. It returns ErrAlreadyExists when the
	// id or the username is already stored.
	CreateAccount(ctx context.Context, a Account) error
	// GetAccount returns the account with the given id, or ErrNotFound.
	GetAccount(ctx context.Context, id string) (Account, error)
	// GetAccountByUsername returns the account with the given username, or
	// ErrNotFound.
	GetAccountByUsername(ctx context.Context, username string) (Account, error)
}

// Clock is the source of time for the domain so behavior is deterministic in
// tests. Production wires a real clock in internal/runtime; tests pass a fake.
type Clock interface {
	// Now returns the current time. Implementations return UTC.
	Now() time.Time
}

// TimestampPrecision is the resolution every stored timestamp is truncated to
// before it is written, so a value read back on either engine compares Equal to
// the value written. See Account.CreatedAt.
const TimestampPrecision = time.Microsecond

// NormalizeTime converts t to UTC and truncates it to TimestampPrecision. Every
// timestamp crosses into storage through this function.
func NormalizeTime(t time.Time) time.Time {
	return t.UTC().Truncate(TimestampPrecision)
}
