-- PostgreSQL migration 00001: accounts (ADR 0004, ADR 0006 item 1).
-- The SQLite twin lives at ../sqlite/00001_create_accounts.sql; the parity test
-- asserts both directories carry the same file names and that the resulting
-- tables expose the same columns.

-- +goose Up
-- +goose StatementBegin
CREATE TABLE accounts (
    -- UUID string generated by Bloom (core.NewID), so both engines store the
    -- same value and no engine-specific id type leaks into the domain. TEXT
    -- rather than the native uuid type keeps the column shape identical to
    -- SQLite's.
    id         TEXT PRIMARY KEY,
    username   TEXT NOT NULL UNIQUE,
    -- Timestamp representation (ADR 0004 item 5): TIMESTAMPTZ stores an absolute
    -- instant at microsecond precision. Bloom writes UTC values truncated to
    -- microseconds (core.NormalizeTime) so the value reads back Equal on both
    -- engines; the SQLite twin stores the same instant as RFC 3339 text.
    created_at TIMESTAMPTZ NOT NULL
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE accounts;
-- +goose StatementEnd
