// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package postgres

import (
	"context"
	"database/sql"
	"time"
)

const countAccounts = `-- name: CountAccounts :one
SELECT COUNT(*) FROM accounts
`

func (q *Queries) CountAccounts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAccounts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccount = `-- name: CreateAccount :exec

INSERT INTO accounts (id, username, username_key, password_hash, disabled, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateAccountParams struct {
	ID           string
	Username     string
	UsernameKey  string
	PasswordHash sql.NullString
	Disabled     bool
	CreatedAt    time.Time
}

// accounts.sql is the sqlc source of truth for the account store. It is SHARED
// by both engines (ADR 0004 item 3): sqlc.yaml compiles it once against the
// SQLite schema into internal/db/sqlite and once against the PostgreSQL schema
// into internal/db/postgres. Only portable SQL belongs here; named parameters
// (sqlc.arg) are used because both engines accept them, whereas $1 and ? are
// engine-specific. Regenerate with: go tool sqlc generate.
func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) error {
	_, err := q.db.ExecContext(ctx, createAccount,
		arg.ID,
		arg.Username,
		arg.UsernameKey,
		arg.PasswordHash,
		arg.Disabled,
		arg.CreatedAt,
	)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, username, password_hash, disabled, created_at
FROM accounts
WHERE id = $1
`

type GetAccountRow struct {
	ID           string
	Username     string
	PasswordHash sql.NullString
	Disabled     bool
	CreatedAt    time.Time
}

func (q *Queries) GetAccount(ctx context.Context, id string) (GetAccountRow, error) {
	row := q.db.QueryRowContext(ctx, getAccount, id)
	var i GetAccountRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Disabled,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountByUsername = `-- name: GetAccountByUsername :one
SELECT id, username, password_hash, disabled, created_at
FROM accounts
WHERE username_key = $1
`

type GetAccountByUsernameRow struct {
	ID           string
	Username     string
	PasswordHash sql.NullString
	Disabled     bool
	CreatedAt    time.Time
}

func (q *Queries) GetAccountByUsername(ctx context.Context, usernameKey string) (GetAccountByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getAccountByUsername, usernameKey)
	var i GetAccountByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Disabled,
		&i.CreatedAt,
	)
	return i, err
}

const updateAccountPasswordHash = `-- name: UpdateAccountPasswordHash :execrows
UPDATE accounts
SET password_hash = $1
WHERE id = $2
`

type UpdateAccountPasswordHashParams struct {
	PasswordHash sql.NullString
	ID           string
}

func (q *Queries) UpdateAccountPasswordHash(ctx context.Context, arg UpdateAccountPasswordHashParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAccountPasswordHash, arg.PasswordHash, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
