// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: download_managers.sql

package postgres

import (
	"context"
	"time"
)

const countRequestProfilesForDownloadManager = `-- name: CountRequestProfilesForDownloadManager :one
SELECT COUNT(*) FROM request_profiles
WHERE download_manager_kind = $1
  AND download_manager_instance = $2
`

type CountRequestProfilesForDownloadManagerParams struct {
	Kind string
	Name string
}

func (q *Queries) CountRequestProfilesForDownloadManager(ctx context.Context, arg CountRequestProfilesForDownloadManagerParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRequestProfilesForDownloadManager, arg.Kind, arg.Name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDownloadManager = `-- name: CreateDownloadManager :exec

INSERT INTO download_managers (
    id, kind, name, name_key, base_url, allow_insecure,
    credential_ciphertext, key_id, created_at, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10
)
`

type CreateDownloadManagerParams struct {
	ID                   string
	Kind                 string
	Name                 string
	NameKey              string
	BaseUrl              string
	AllowInsecure        bool
	CredentialCiphertext []byte
	KeyID                string
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

// Download-manager registration queries shared by both engines.
func (q *Queries) CreateDownloadManager(ctx context.Context, arg CreateDownloadManagerParams) error {
	_, err := q.db.ExecContext(ctx, createDownloadManager,
		arg.ID,
		arg.Kind,
		arg.Name,
		arg.NameKey,
		arg.BaseUrl,
		arg.AllowInsecure,
		arg.CredentialCiphertext,
		arg.KeyID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteDownloadManager = `-- name: DeleteDownloadManager :execrows
DELETE FROM download_managers WHERE id = $1
`

func (q *Queries) DeleteDownloadManager(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDownloadManager, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getDownloadManager = `-- name: GetDownloadManager :one
SELECT id, kind, name, base_url, allow_insecure, credential_ciphertext,
       key_id, created_at, updated_at
FROM download_managers WHERE id = $1
`

type GetDownloadManagerRow struct {
	ID                   string
	Kind                 string
	Name                 string
	BaseUrl              string
	AllowInsecure        bool
	CredentialCiphertext []byte
	KeyID                string
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

func (q *Queries) GetDownloadManager(ctx context.Context, id string) (GetDownloadManagerRow, error) {
	row := q.db.QueryRowContext(ctx, getDownloadManager, id)
	var i GetDownloadManagerRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.BaseUrl,
		&i.AllowInsecure,
		&i.CredentialCiphertext,
		&i.KeyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDownloadManagerByName = `-- name: GetDownloadManagerByName :one
SELECT id, kind, name, base_url, allow_insecure, credential_ciphertext,
       key_id, created_at, updated_at
FROM download_managers WHERE name_key = $1
`

type GetDownloadManagerByNameRow struct {
	ID                   string
	Kind                 string
	Name                 string
	BaseUrl              string
	AllowInsecure        bool
	CredentialCiphertext []byte
	KeyID                string
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

func (q *Queries) GetDownloadManagerByName(ctx context.Context, nameKey string) (GetDownloadManagerByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getDownloadManagerByName, nameKey)
	var i GetDownloadManagerByNameRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.BaseUrl,
		&i.AllowInsecure,
		&i.CredentialCiphertext,
		&i.KeyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDownloadManagers = `-- name: ListDownloadManagers :many
SELECT id, kind, name, base_url, allow_insecure, created_at, updated_at
FROM download_managers
WHERE name_key > $1
ORDER BY name_key, id
LIMIT $2
`

type ListDownloadManagersParams struct {
	AfterNameKey string
	PageSize     int32
}

type ListDownloadManagersRow struct {
	ID            string
	Kind          string
	Name          string
	BaseUrl       string
	AllowInsecure bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) ListDownloadManagers(ctx context.Context, arg ListDownloadManagersParams) ([]ListDownloadManagersRow, error) {
	rows, err := q.db.QueryContext(ctx, listDownloadManagers, arg.AfterNameKey, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDownloadManagersRow{}
	for rows.Next() {
		var i ListDownloadManagersRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.BaseUrl,
			&i.AllowInsecure,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
