// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: imports_postgres.sql

package postgres

import (
	"context"
	"database/sql"
	"time"
)

const claimImport = `-- name: ClaimImport :execrows
UPDATE imports
SET state = 'running', lease_token = $1, lease_expires_at = $2,
    started_at = COALESCE(started_at, $3), updated_at = $3
WHERE id = $4
  AND (state = 'pending' OR (state = 'running' AND lease_expires_at <= $3))
`

type ClaimImportParams struct {
	Token     string
	ExpiresAt sql.NullTime
	Now       time.Time
	ID        string
}

func (q *Queries) ClaimImport(ctx context.Context, arg ClaimImportParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimImport,
		arg.Token,
		arg.ExpiresAt,
		arg.Now,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const fenceImportBatch = `-- name: FenceImportBatch :one
SELECT id FROM imports
WHERE id = $1 AND state = 'running' AND lease_token = $2
FOR UPDATE
`

type FenceImportBatchParams struct {
	ID    string
	Token string
}

func (q *Queries) FenceImportBatch(ctx context.Context, arg FenceImportBatchParams) (string, error) {
	row := q.db.QueryRowContext(ctx, fenceImportBatch, arg.ID, arg.Token)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getImport = `-- name: GetImport :one
SELECT id, media_server_id, source, state, cursor, read_count, imported_count,
       skipped_count, duplicate_count, last_error, lease_token, lease_expires_at,
       requested_by, created_at, started_at, finished_at, updated_at, unresolved_library_count
FROM imports WHERE id = $1
`

func (q *Queries) GetImport(ctx context.Context, id string) (Import, error) {
	row := q.db.QueryRowContext(ctx, getImport, id)
	var i Import
	err := row.Scan(
		&i.ID,
		&i.MediaServerID,
		&i.Source,
		&i.State,
		&i.Cursor,
		&i.ReadCount,
		&i.ImportedCount,
		&i.SkippedCount,
		&i.DuplicateCount,
		&i.LastError,
		&i.LeaseToken,
		&i.LeaseExpiresAt,
		&i.RequestedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
		&i.UnresolvedLibraryCount,
	)
	return i, err
}

const listImports = `-- name: ListImports :many
SELECT id, media_server_id, source, state, cursor, read_count, imported_count,
       skipped_count, duplicate_count, last_error, lease_token, lease_expires_at,
       requested_by, created_at, started_at, finished_at, updated_at, unresolved_library_count
FROM imports
WHERE (CAST($1 AS TEXT) = ''
       OR media_server_id = CAST($1 AS TEXT))
  AND (created_at < $2
       OR (created_at = $2 AND id < $3))
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListImportsParams struct {
	MediaServerID   string
	BeforeCreatedAt time.Time
	BeforeID        string
	PageSize        int32
}

func (q *Queries) ListImports(ctx context.Context, arg ListImportsParams) ([]Import, error) {
	rows, err := q.db.QueryContext(ctx, listImports,
		arg.MediaServerID,
		arg.BeforeCreatedAt,
		arg.BeforeID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Import{}
	for rows.Next() {
		var i Import
		if err := rows.Scan(
			&i.ID,
			&i.MediaServerID,
			&i.Source,
			&i.State,
			&i.Cursor,
			&i.ReadCount,
			&i.ImportedCount,
			&i.SkippedCount,
			&i.DuplicateCount,
			&i.LastError,
			&i.LeaseToken,
			&i.LeaseExpiresAt,
			&i.RequestedBy,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.UpdatedAt,
			&i.UnresolvedLibraryCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockWatchDedup = `-- name: LockWatchDedup :exec
SELECT pg_advisory_xact_lock(hashtextextended($1, 0))
`

func (q *Queries) LockWatchDedup(ctx context.Context, lockKey string) error {
	_, err := q.db.ExecContext(ctx, lockWatchDedup, lockKey)
	return err
}

const selectClaimableImport = `-- name: SelectClaimableImport :one

SELECT id, media_server_id, source, state, cursor, read_count, imported_count,
       skipped_count, duplicate_count, last_error, lease_token, lease_expires_at,
       requested_by, created_at, started_at, finished_at, updated_at, unresolved_library_count
FROM imports
WHERE state = 'pending' OR (state = 'running' AND lease_expires_at <= $1)
ORDER BY created_at, id
LIMIT 1
FOR UPDATE SKIP LOCKED
`

// PostgreSQL claim serializes claimers without blocking unrelated jobs.
func (q *Queries) SelectClaimableImport(ctx context.Context, now sql.NullTime) (Import, error) {
	row := q.db.QueryRowContext(ctx, selectClaimableImport, now)
	var i Import
	err := row.Scan(
		&i.ID,
		&i.MediaServerID,
		&i.Source,
		&i.State,
		&i.Cursor,
		&i.ReadCount,
		&i.ImportedCount,
		&i.SkippedCount,
		&i.DuplicateCount,
		&i.LastError,
		&i.LeaseToken,
		&i.LeaseExpiresAt,
		&i.RequestedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
		&i.UnresolvedLibraryCount,
	)
	return i, err
}
