// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invites.sql

package postgres

import (
	"context"
	"database/sql"
	"time"
)

const createInvite = `-- name: CreateInvite :exec
INSERT INTO invites (
    id, media_server_id, created_by_account_id, code_hash, label,
    expires_at, max_uses, use_count, revoked_at, created_at, updated_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $7,
    0, NULL, $8, $9
)
`

type CreateInviteParams struct {
	ID                 string
	MediaServerID      string
	CreatedByAccountID string
	CodeHash           []byte
	Label              string
	ExpiresAt          sql.NullTime
	MaxUses            sql.NullInt32
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) error {
	_, err := q.db.ExecContext(ctx, createInvite,
		arg.ID,
		arg.MediaServerID,
		arg.CreatedByAccountID,
		arg.CodeHash,
		arg.Label,
		arg.ExpiresAt,
		arg.MaxUses,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createInviteLibrary = `-- name: CreateInviteLibrary :exec
INSERT INTO invite_libraries (invite_id, library_id)
VALUES ($1, $2)
`

type CreateInviteLibraryParams struct {
	InviteID  string
	LibraryID string
}

func (q *Queries) CreateInviteLibrary(ctx context.Context, arg CreateInviteLibraryParams) error {
	_, err := q.db.ExecContext(ctx, createInviteLibrary, arg.InviteID, arg.LibraryID)
	return err
}

const getInvite = `-- name: GetInvite :one
SELECT id, media_server_id, created_by_account_id, label, expires_at,
       max_uses, use_count, revoked_at, created_at, updated_at
FROM invites
WHERE id = $1
`

type GetInviteRow struct {
	ID                 string
	MediaServerID      string
	CreatedByAccountID string
	Label              string
	ExpiresAt          sql.NullTime
	MaxUses            sql.NullInt32
	UseCount           int32
	RevokedAt          sql.NullTime
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

func (q *Queries) GetInvite(ctx context.Context, id string) (GetInviteRow, error) {
	row := q.db.QueryRowContext(ctx, getInvite, id)
	var i GetInviteRow
	err := row.Scan(
		&i.ID,
		&i.MediaServerID,
		&i.CreatedByAccountID,
		&i.Label,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.UseCount,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInviteByCodeHash = `-- name: GetInviteByCodeHash :one
SELECT id, media_server_id, created_by_account_id, label, expires_at,
       max_uses, use_count, revoked_at, created_at, updated_at
FROM invites
WHERE code_hash = $1
  AND NOT EXISTS (
      SELECT 1 FROM invite_provisioning_failures
      WHERE invite_provisioning_failures.invite_id = invites.id
  )
`

type GetInviteByCodeHashRow struct {
	ID                 string
	MediaServerID      string
	CreatedByAccountID string
	Label              string
	ExpiresAt          sql.NullTime
	MaxUses            sql.NullInt32
	UseCount           int32
	RevokedAt          sql.NullTime
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

func (q *Queries) GetInviteByCodeHash(ctx context.Context, codeHash []byte) (GetInviteByCodeHashRow, error) {
	row := q.db.QueryRowContext(ctx, getInviteByCodeHash, codeHash)
	var i GetInviteByCodeHashRow
	err := row.Scan(
		&i.ID,
		&i.MediaServerID,
		&i.CreatedByAccountID,
		&i.Label,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.UseCount,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementInviteUse = `-- name: IncrementInviteUse :execrows
UPDATE invites
SET use_count = use_count + 1, updated_at = $1
WHERE id = $2
`

type IncrementInviteUseParams struct {
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) IncrementInviteUse(ctx context.Context, arg IncrementInviteUseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, incrementInviteUse, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertInviteProvisioningFailure = `-- name: InsertInviteProvisioningFailure :exec
INSERT INTO invite_provisioning_failures (
    id, invite_id, media_server_id, media_user_id, username, reason, created_at, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8
)
`

type InsertInviteProvisioningFailureParams struct {
	ID            string
	InviteID      string
	MediaServerID string
	MediaUserID   sql.NullString
	Username      string
	Reason        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) InsertInviteProvisioningFailure(ctx context.Context, arg InsertInviteProvisioningFailureParams) error {
	_, err := q.db.ExecContext(ctx, insertInviteProvisioningFailure,
		arg.ID,
		arg.InviteID,
		arg.MediaServerID,
		arg.MediaUserID,
		arg.Username,
		arg.Reason,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertInviteRedemption = `-- name: InsertInviteRedemption :exec
INSERT INTO invite_redemptions (
    id, invite_id, media_server_id, media_user_id, username, redeemed_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6
)
`

type InsertInviteRedemptionParams struct {
	ID            string
	InviteID      string
	MediaServerID string
	MediaUserID   string
	Username      string
	RedeemedAt    time.Time
}

func (q *Queries) InsertInviteRedemption(ctx context.Context, arg InsertInviteRedemptionParams) error {
	_, err := q.db.ExecContext(ctx, insertInviteRedemption,
		arg.ID,
		arg.InviteID,
		arg.MediaServerID,
		arg.MediaUserID,
		arg.Username,
		arg.RedeemedAt,
	)
	return err
}

const listInviteLibraries = `-- name: ListInviteLibraries :many
SELECT library_id
FROM invite_libraries
WHERE invite_id = $1
ORDER BY library_id
`

func (q *Queries) ListInviteLibraries(ctx context.Context, inviteID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listInviteLibraries, inviteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var library_id string
		if err := rows.Scan(&library_id); err != nil {
			return nil, err
		}
		items = append(items, library_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvites = `-- name: ListInvites :many
SELECT id, media_server_id, created_by_account_id, label, expires_at,
       max_uses, use_count, revoked_at, created_at, updated_at
FROM invites
WHERE CAST($1 AS INTEGER) = 0
   OR created_at < $2
   OR (created_at = $2 AND id < $3)
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListInvitesParams struct {
	HasCursor      int32
	AfterCreatedAt time.Time
	AfterID        string
	PageSize       int32
}

type ListInvitesRow struct {
	ID                 string
	MediaServerID      string
	CreatedByAccountID string
	Label              string
	ExpiresAt          sql.NullTime
	MaxUses            sql.NullInt32
	UseCount           int32
	RevokedAt          sql.NullTime
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

func (q *Queries) ListInvites(ctx context.Context, arg ListInvitesParams) ([]ListInvitesRow, error) {
	rows, err := q.db.QueryContext(ctx, listInvites,
		arg.HasCursor,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvitesRow{}
	for rows.Next() {
		var i ListInvitesRow
		if err := rows.Scan(
			&i.ID,
			&i.MediaServerID,
			&i.CreatedByAccountID,
			&i.Label,
			&i.ExpiresAt,
			&i.MaxUses,
			&i.UseCount,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeInvite = `-- name: RevokeInvite :one
UPDATE invites
SET revoked_at = COALESCE(revoked_at, $1),
    updated_at = $2
WHERE id = $3
RETURNING id, media_server_id, created_by_account_id, label, expires_at,
          max_uses, use_count, revoked_at, created_at, updated_at
`

type RevokeInviteParams struct {
	RevokedAt sql.NullTime
	UpdatedAt time.Time
	ID        string
}

type RevokeInviteRow struct {
	ID                 string
	MediaServerID      string
	CreatedByAccountID string
	Label              string
	ExpiresAt          sql.NullTime
	MaxUses            sql.NullInt32
	UseCount           int32
	RevokedAt          sql.NullTime
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

func (q *Queries) RevokeInvite(ctx context.Context, arg RevokeInviteParams) (RevokeInviteRow, error) {
	row := q.db.QueryRowContext(ctx, revokeInvite, arg.RevokedAt, arg.UpdatedAt, arg.ID)
	var i RevokeInviteRow
	err := row.Scan(
		&i.ID,
		&i.MediaServerID,
		&i.CreatedByAccountID,
		&i.Label,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.UseCount,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
