// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invites_postgres.sql

package postgres

import (
	"context"
	"database/sql"
	"time"
)

const inviteHasProvisioningFailure = `-- name: InviteHasProvisioningFailure :one
SELECT EXISTS (
    SELECT 1 FROM invite_provisioning_failures
    WHERE invite_id = $1
)
`

func (q *Queries) InviteHasProvisioningFailure(ctx context.Context, inviteID string) (bool, error) {
	row := q.db.QueryRowContext(ctx, inviteHasProvisioningFailure, inviteID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const lockInviteByCodeHash = `-- name: LockInviteByCodeHash :one
SELECT id, media_server_id, created_by_account_id, label, expires_at,
       max_uses, use_count, revoked_at, created_at, updated_at
FROM invites
WHERE code_hash = $1
FOR UPDATE
`

type LockInviteByCodeHashRow struct {
	ID                 string
	MediaServerID      string
	CreatedByAccountID string
	Label              string
	ExpiresAt          sql.NullTime
	MaxUses            sql.NullInt32
	UseCount           int32
	RevokedAt          sql.NullTime
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

func (q *Queries) LockInviteByCodeHash(ctx context.Context, codeHash []byte) (LockInviteByCodeHashRow, error) {
	row := q.db.QueryRowContext(ctx, lockInviteByCodeHash, codeHash)
	var i LockInviteByCodeHashRow
	err := row.Scan(
		&i.ID,
		&i.MediaServerID,
		&i.CreatedByAccountID,
		&i.Label,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.UseCount,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
