// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media_servers.sql

package postgres

import (
	"context"
	"time"
)

const createMediaServer = `-- name: CreateMediaServer :exec

INSERT INTO media_servers (id, kind, name, name_key, base_url, allow_insecure, credential_ciphertext, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateMediaServerParams struct {
	ID                   string
	Kind                 string
	Name                 string
	NameKey              string
	BaseUrl              string
	AllowInsecure        bool
	CredentialCiphertext []byte
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

// Media-server queries are portable across SQLite and PostgreSQL.
func (q *Queries) CreateMediaServer(ctx context.Context, arg CreateMediaServerParams) error {
	_, err := q.db.ExecContext(ctx, createMediaServer,
		arg.ID,
		arg.Kind,
		arg.Name,
		arg.NameKey,
		arg.BaseUrl,
		arg.AllowInsecure,
		arg.CredentialCiphertext,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteMediaServer = `-- name: DeleteMediaServer :execrows
DELETE FROM media_servers
WHERE id = $1
`

func (q *Queries) DeleteMediaServer(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMediaServer, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getMediaServer = `-- name: GetMediaServer :one
SELECT id, kind, name, base_url, allow_insecure, credential_ciphertext, created_at, updated_at
FROM media_servers
WHERE id = $1
`

type GetMediaServerRow struct {
	ID                   string
	Kind                 string
	Name                 string
	BaseUrl              string
	AllowInsecure        bool
	CredentialCiphertext []byte
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

func (q *Queries) GetMediaServer(ctx context.Context, id string) (GetMediaServerRow, error) {
	row := q.db.QueryRowContext(ctx, getMediaServer, id)
	var i GetMediaServerRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.BaseUrl,
		&i.AllowInsecure,
		&i.CredentialCiphertext,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMediaServers = `-- name: ListMediaServers :many
SELECT id, kind, name, base_url, allow_insecure, created_at, updated_at
FROM media_servers
WHERE name_key > $1
ORDER BY name_key, id
LIMIT $2
`

type ListMediaServersParams struct {
	AfterNameKey string
	PageSize     int32
}

type ListMediaServersRow struct {
	ID            string
	Kind          string
	Name          string
	BaseUrl       string
	AllowInsecure bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) ListMediaServers(ctx context.Context, arg ListMediaServersParams) ([]ListMediaServersRow, error) {
	rows, err := q.db.QueryContext(ctx, listMediaServers, arg.AfterNameKey, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMediaServersRow{}
	for rows.Next() {
		var i ListMediaServersRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.BaseUrl,
			&i.AllowInsecure,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
