// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"database/sql"
	"time"
)

type Account struct {
	ID           string
	Username     string
	CreatedAt    time.Time
	PasswordHash sql.NullString
	Disabled     bool
	UsernameKey  string
}

type AccountUsernameMigrationBackup struct {
	AccountID        string
	OriginalUsername string
}

type Session struct {
	Token  string
	Data   []byte
	Expiry time.Time
}
