// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"database/sql"
	"time"
)

type Account struct {
	ID           string
	Username     string
	CreatedAt    time.Time
	PasswordHash sql.NullString
	Disabled     bool
	UsernameKey  string
}

type AccountIdentity struct {
	AccountID     string
	Provider      string
	Issuer        string
	Subject       string
	UsernameClaim string
	MappedRoles   string
	CreatedAt     time.Time
	LastLoginAt   time.Time
}

type AccountRequestQuota struct {
	AccountID           string
	MovieLimit          int32
	MoviePeriodSeconds  int64
	SeasonLimit         int32
	SeasonPeriodSeconds int64
}

type AccountRole struct {
	AccountID string
	RoleID    string
	Source    string
}

type AccountUsernameMigrationBackup struct {
	AccountID        string
	OriginalUsername string
}

type Invite struct {
	ID                 string
	MediaServerID      string
	CreatedByAccountID string
	CodeHash           []byte
	Label              string
	ExpiresAt          sql.NullTime
	MaxUses            sql.NullInt32
	UseCount           int32
	RevokedAt          sql.NullTime
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type InviteLibrary struct {
	InviteID  string
	LibraryID string
}

type InviteProvisioningFailure struct {
	ID            string
	InviteID      string
	MediaServerID string
	MediaUserID   sql.NullString
	Username      string
	Reason        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type InviteRedemption struct {
	ID            string
	InviteID      string
	MediaServerID string
	MediaUserID   string
	Username      string
	RedeemedAt    time.Time
}

type MediaServer struct {
	ID                   string
	Kind                 string
	Name                 string
	NameKey              string
	BaseUrl              string
	AllowInsecure        bool
	CredentialCiphertext []byte
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type MetadataProvider struct {
	Kind                 string
	CredentialCiphertext []byte
	KeyID                string
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type Request struct {
	ID                 string
	Kind               string
	Provider           string
	ProviderID         string
	Title              string
	ReleaseYear        int32
	PosterPath         string
	RequesterAccountID string
	ProfileID          string
	Status             string
	DecisionReason     string
	DecidedByAccountID sql.NullString
	DecidedAt          sql.NullTime
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type RequestProfile struct {
	ID                      string
	Name                    string
	AcceptsMovies           bool
	AcceptsSeries           bool
	DownloadManagerKind     string
	DownloadManagerInstance string
	QualityProfile          string
	RootFolder              string
	CreatedAt               time.Time
	UpdatedAt               time.Time
}

type RequestProfileTag struct {
	ProfileID string
	Position  int32
	Tag       string
}

type RequestSeason struct {
	RequestID    string
	SeasonNumber int32
	Status       string
}

type Role struct {
	ID          string
	Name        string
	Description string
	BuiltIn     bool
	CreatedAt   time.Time
}

type RolePermission struct {
	RoleID     string
	Permission string
}

type RoleRequestQuota struct {
	RoleID              string
	MovieLimit          int32
	MoviePeriodSeconds  int64
	SeasonLimit         int32
	SeasonPeriodSeconds int64
}

type Session struct {
	Token  string
	Data   []byte
	Expiry time.Time
}

type Watch struct {
	ID              string
	MediaServerID   string
	MediaUserID     string
	Username        string
	DeviceID        string
	DeviceName      string
	Client          string
	ServerSessionID string
	ItemID          string
	ItemName        string
	ItemType        string
	SeriesName      string
	SeasonNumber    sql.NullInt32
	EpisodeNumber   sql.NullInt32
	PlayMethod      string
	State           string
	StartedAt       time.Time
	LastSeenAt      time.Time
	EndedAt         sql.NullTime
	ActiveSeconds   int64
	LastPositionMs  int64
	Source          string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type WatchPosition struct {
	WatchID    string
	ObservedAt time.Time
	PositionMs int64
	Paused     bool
	PlayMethod string
	Source     string
}

type WatchSegment struct {
	WatchID   string
	StartedAt time.Time
	EndedAt   sql.NullTime
	Source    string
}
