// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"database/sql"
	"time"
)

type Account struct {
	ID           string
	Username     string
	CreatedAt    time.Time
	PasswordHash sql.NullString
	Disabled     bool
	UsernameKey  string
}

type AccountIdentity struct {
	AccountID     string
	Provider      string
	Issuer        string
	Subject       string
	UsernameClaim string
	MappedRoles   string
	CreatedAt     time.Time
	LastLoginAt   time.Time
}

type AccountRole struct {
	AccountID string
	RoleID    string
	Source    string
}

type AccountUsernameMigrationBackup struct {
	AccountID        string
	OriginalUsername string
}

type Invite struct {
	ID                 string
	MediaServerID      string
	CreatedByAccountID string
	CodeHash           []byte
	Label              string
	ExpiresAt          sql.NullTime
	MaxUses            sql.NullInt32
	UseCount           int32
	RevokedAt          sql.NullTime
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type InviteLibrary struct {
	InviteID  string
	LibraryID string
}

type InviteProvisioningFailure struct {
	ID            string
	InviteID      string
	MediaServerID string
	MediaUserID   sql.NullString
	Username      string
	Reason        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type InviteRedemption struct {
	ID            string
	InviteID      string
	MediaServerID string
	MediaUserID   string
	Username      string
	RedeemedAt    time.Time
}

type MediaServer struct {
	ID                   string
	Kind                 string
	Name                 string
	NameKey              string
	BaseUrl              string
	AllowInsecure        bool
	CredentialCiphertext []byte
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type Role struct {
	ID          string
	Name        string
	Description string
	BuiltIn     bool
	CreatedAt   time.Time
}

type RolePermission struct {
	RoleID     string
	Permission string
}

type Session struct {
	Token  string
	Data   []byte
	Expiry time.Time
}
