// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications_postgres.sql

package postgres

import (
	"context"
	"database/sql"
	"time"
)

const lockNotificationChannelForClaim = `-- name: LockNotificationChannelForClaim :one

SELECT channel.id
FROM notification_outbox AS candidate
JOIN notification_channels AS channel ON channel.id = candidate.channel_id
WHERE candidate.status = 'pending' AND candidate.next_attempt_at <= $1
  AND candidate.attempts < 8
  AND (candidate.lease_token = '' OR candidate.lease_expires_at <= $1)
  AND channel.enabled = TRUE AND channel.deleted_at IS NULL
ORDER BY candidate.next_attempt_at, candidate.created_at, candidate.id
LIMIT 1
FOR UPDATE OF channel
`

// PostgreSQL notification row locks. Each lock is followed by a second
// statement in the same Read Committed transaction that re-checks eligibility.
func (q *Queries) LockNotificationChannelForClaim(ctx context.Context, dueAt time.Time) (string, error) {
	row := q.db.QueryRowContext(ctx, lockNotificationChannelForClaim, dueAt)
	var id string
	err := row.Scan(&id)
	return id, err
}

const lockTombstonedNotificationChannels = `-- name: LockTombstonedNotificationChannels :many
SELECT candidate.id
FROM notification_channels AS candidate
WHERE candidate.deleted_at IS NOT NULL
  AND NOT EXISTS (
	SELECT 1 FROM notification_outbox AS delivery
	WHERE delivery.channel_id = candidate.id AND delivery.status = 'pending'
	  AND delivery.lease_token <> '' AND delivery.lease_expires_at > $1
  )
ORDER BY candidate.deleted_at, candidate.id
LIMIT $2
FOR UPDATE OF candidate
`

type LockTombstonedNotificationChannelsParams struct {
	At        sql.NullTime
	BatchSize int32
}

func (q *Queries) LockTombstonedNotificationChannels(ctx context.Context, arg LockTombstonedNotificationChannelsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, lockTombstonedNotificationChannels, arg.At, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
