// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oidc.sql

package postgres

import (
	"context"
	"database/sql"
	"time"
)

const assignOIDCRoleIDToAccount = `-- name: AssignOIDCRoleIDToAccount :execrows
INSERT INTO account_roles (account_id, role_id, source)
VALUES ($1, $2, 'oidc')
ON CONFLICT DO NOTHING
`

type AssignOIDCRoleIDToAccountParams struct {
	AccountID string
	RoleID    string
}

func (q *Queries) AssignOIDCRoleIDToAccount(ctx context.Context, arg AssignOIDCRoleIDToAccountParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, assignOIDCRoleIDToAccount, arg.AccountID, arg.RoleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createAccountIdentity = `-- name: CreateAccountIdentity :exec
INSERT INTO account_identities (
    account_id, provider, issuer, subject, username_claim, mapped_roles, created_at, last_login_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8
)
`

type CreateAccountIdentityParams struct {
	AccountID     string
	Provider      string
	Issuer        string
	Subject       string
	UsernameClaim string
	MappedRoles   string
	CreatedAt     time.Time
	LastLoginAt   time.Time
}

func (q *Queries) CreateAccountIdentity(ctx context.Context, arg CreateAccountIdentityParams) error {
	_, err := q.db.ExecContext(ctx, createAccountIdentity,
		arg.AccountID,
		arg.Provider,
		arg.Issuer,
		arg.Subject,
		arg.UsernameClaim,
		arg.MappedRoles,
		arg.CreatedAt,
		arg.LastLoginAt,
	)
	return err
}

const getAccountIdentity = `-- name: GetAccountIdentity :one

SELECT ai.account_id, ai.provider, ai.issuer, ai.subject, ai.username_claim,
       ai.mapped_roles, ai.created_at, ai.last_login_at,
       a.username, a.password_hash, a.disabled, a.created_at AS account_created_at
FROM account_identities ai
JOIN accounts a ON a.id = ai.account_id
WHERE ai.issuer = $1 AND ai.subject = $2
`

type GetAccountIdentityParams struct {
	Issuer  string
	Subject string
}

type GetAccountIdentityRow struct {
	AccountID        string
	Provider         string
	Issuer           string
	Subject          string
	UsernameClaim    string
	MappedRoles      string
	CreatedAt        time.Time
	LastLoginAt      time.Time
	Username         string
	PasswordHash     sql.NullString
	Disabled         bool
	AccountCreatedAt time.Time
}

// OIDC identity queries are shared by SQLite and PostgreSQL.
func (q *Queries) GetAccountIdentity(ctx context.Context, arg GetAccountIdentityParams) (GetAccountIdentityRow, error) {
	row := q.db.QueryRowContext(ctx, getAccountIdentity, arg.Issuer, arg.Subject)
	var i GetAccountIdentityRow
	err := row.Scan(
		&i.AccountID,
		&i.Provider,
		&i.Issuer,
		&i.Subject,
		&i.UsernameClaim,
		&i.MappedRoles,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.Username,
		&i.PasswordHash,
		&i.Disabled,
		&i.AccountCreatedAt,
	)
	return i, err
}

const removeRoleIDFromAccount = `-- name: RemoveRoleIDFromAccount :execrows
DELETE FROM account_roles
WHERE account_id = $1 AND role_id = $2 AND source = 'oidc'
`

type RemoveRoleIDFromAccountParams struct {
	AccountID string
	RoleID    string
}

func (q *Queries) RemoveRoleIDFromAccount(ctx context.Context, arg RemoveRoleIDFromAccountParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, removeRoleIDFromAccount, arg.AccountID, arg.RoleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateAccountIdentityLogin = `-- name: UpdateAccountIdentityLogin :execrows
UPDATE account_identities
SET username_claim = $1,
    mapped_roles = $2,
    last_login_at = $3
WHERE issuer = $4 AND subject = $5
`

type UpdateAccountIdentityLoginParams struct {
	UsernameClaim string
	MappedRoles   string
	LastLoginAt   time.Time
	Issuer        string
	Subject       string
}

func (q *Queries) UpdateAccountIdentityLogin(ctx context.Context, arg UpdateAccountIdentityLoginParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAccountIdentityLogin,
		arg.UsernameClaim,
		arg.MappedRoles,
		arg.LastLoginAt,
		arg.Issuer,
		arg.Subject,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
