// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"context"
)

type Querier interface {
	AssignOIDCRoleIDToAccount(ctx context.Context, arg AssignOIDCRoleIDToAccountParams) (int64, error)
	AssignRoleIDToAccount(ctx context.Context, arg AssignRoleIDToAccountParams) (int64, error)
	CloseOpenWatchSegment(ctx context.Context, arg CloseOpenWatchSegmentParams) (int64, error)
	CountAccounts(ctx context.Context) (int64, error)
	// accounts.sql is the sqlc source of truth for the account store. It is SHARED
	// by both engines (ADR 0004 item 3): sqlc.yaml compiles it once against the
	// SQLite schema into internal/db/sqlite and once against the PostgreSQL schema
	// into internal/db/postgres. Only portable SQL belongs here; named parameters
	// (sqlc.arg) are used because both engines accept them, whereas $1 and ? are
	// engine-specific. Regenerate with: go tool sqlc generate.
	CreateAccount(ctx context.Context, arg CreateAccountParams) error
	CreateAccountIdentity(ctx context.Context, arg CreateAccountIdentityParams) error
	CreateInvite(ctx context.Context, arg CreateInviteParams) error
	CreateInviteLibrary(ctx context.Context, arg CreateInviteLibraryParams) error
	// Media-server queries are portable across SQLite and PostgreSQL.
	CreateMediaServer(ctx context.Context, arg CreateMediaServerParams) error
	CreateWatchSegment(ctx context.Context, arg CreateWatchSegmentParams) error
	DeleteMediaServer(ctx context.Context, id string) (int64, error)
	FindRecentPlaybackWatch(ctx context.Context, arg FindRecentPlaybackWatchParams) (FindRecentPlaybackWatchRow, error)
	GetAccount(ctx context.Context, id string) (GetAccountRow, error)
	GetAccountByUsername(ctx context.Context, usernameKey string) (GetAccountByUsernameRow, error)
	// OIDC identity queries are shared by SQLite and PostgreSQL.
	GetAccountIdentity(ctx context.Context, arg GetAccountIdentityParams) (GetAccountIdentityRow, error)
	GetAuthorizationSnapshot(ctx context.Context, accountID string) ([]GetAuthorizationSnapshotRow, error)
	GetInvite(ctx context.Context, id string) (GetInviteRow, error)
	GetInviteByCodeHash(ctx context.Context, codeHash []byte) (GetInviteByCodeHashRow, error)
	GetMediaServer(ctx context.Context, id string) (GetMediaServerRow, error)
	GetRoleIDByName(ctx context.Context, roleName string) (string, error)
	IncrementInviteUse(ctx context.Context, arg IncrementInviteUseParams) (int64, error)
	InsertInviteProvisioningFailure(ctx context.Context, arg InsertInviteProvisioningFailureParams) error
	InsertInviteRedemption(ctx context.Context, arg InsertInviteRedemptionParams) error
	InviteHasProvisioningFailure(ctx context.Context, inviteID string) (bool, error)
	// Authorization queries are shared by SQLite and PostgreSQL. Effective
	// permissions are computed from current database state for every request.
	ListAccountPermissions(ctx context.Context, accountID string) ([]string, error)
	ListInviteLibraries(ctx context.Context, inviteID string) ([]string, error)
	ListInvites(ctx context.Context, arg ListInvitesParams) ([]ListInvitesRow, error)
	ListMediaServers(ctx context.Context, arg ListMediaServersParams) ([]ListMediaServersRow, error)
	ListNowPlaying(ctx context.Context, arg ListNowPlayingParams) ([]ListNowPlayingRow, error)
	ListOpenPlaybackWatches(ctx context.Context, mediaServerID string) ([]ListOpenPlaybackWatchesRow, error)
	ListPlaybackHistory(ctx context.Context, arg ListPlaybackHistoryParams) ([]ListPlaybackHistoryRow, error)
	ListRecentPlaybackWatches(ctx context.Context, arg ListRecentPlaybackWatchesParams) ([]ListRecentPlaybackWatchesRow, error)
	ListRolesWithPermissions(ctx context.Context, arg ListRolesWithPermissionsParams) ([]ListRolesWithPermissionsRow, error)
	LockInviteByCodeHash(ctx context.Context, codeHash []byte) (LockInviteByCodeHashRow, error)
	RemoveRoleIDFromAccount(ctx context.Context, arg RemoveRoleIDFromAccountParams) (int64, error)
	RevokeInvite(ctx context.Context, arg RevokeInviteParams) (RevokeInviteRow, error)
	TrimWatchPositions(ctx context.Context, watchID string) error
	UpdateAccountIdentityLogin(ctx context.Context, arg UpdateAccountIdentityLoginParams) (int64, error)
	UpdateAccountPasswordHash(ctx context.Context, arg UpdateAccountPasswordHashParams) (int64, error)
	// Playback queries are portable across SQLite and PostgreSQL.
	UpsertPlaybackWatch(ctx context.Context, arg UpsertPlaybackWatchParams) error
	UpsertWatchPosition(ctx context.Context, arg UpsertWatchPositionParams) error
}

var _ Querier = (*Queries)(nil)
