// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: requests_postgres.sql

package postgres

import (
	"context"
)

const lockAccountRequestQuota = `-- name: LockAccountRequestQuota :exec
SELECT pg_advisory_xact_lock(hashtextextended($1, 0))
`

func (q *Queries) LockAccountRequestQuota(ctx context.Context, accountID string) error {
	_, err := q.db.ExecContext(ctx, lockAccountRequestQuota, accountID)
	return err
}

const lockRequestTitle = `-- name: LockRequestTitle :exec
SELECT pg_advisory_xact_lock(hashtextextended($1, 0))
`

func (q *Queries) LockRequestTitle(ctx context.Context, lockKey string) error {
	_, err := q.db.ExecContext(ctx, lockRequestTitle, lockKey)
	return err
}
