// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package postgres

import (
	"context"
	"database/sql"
	"time"
)

const statsBucketRows = `-- name: StatsBucketRows :many
SELECT w.started_at, w.active_seconds
FROM watches w
WHERE w.started_at >= $1
  AND w.started_at < $2
  AND (CAST($3 AS TEXT) = ''
       OR w.media_server_id = CAST($3 AS TEXT))
  AND (CAST($4 AS TEXT) = ''
       OR w.library_id = CAST($4 AS TEXT))
  AND (CAST($5 AS TEXT) = ''
       OR (w.media_server_id = CAST($5 AS TEXT)
           AND w.media_user_id = CAST($6 AS TEXT)))
ORDER BY w.started_at, w.id
LIMIT $7
`

type StatsBucketRowsParams struct {
	WindowStart       time.Time
	WindowEnd         time.Time
	MediaServerFilter string
	LibraryFilter     string
	UserServerFilter  string
	MediaUserFilter   string
	RowLimit          int32
}

type StatsBucketRowsRow struct {
	StartedAt     time.Time
	ActiveSeconds int64
}

func (q *Queries) StatsBucketRows(ctx context.Context, arg StatsBucketRowsParams) ([]StatsBucketRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, statsBucketRows,
		arg.WindowStart,
		arg.WindowEnd,
		arg.MediaServerFilter,
		arg.LibraryFilter,
		arg.UserServerFilter,
		arg.MediaUserFilter,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatsBucketRowsRow{}
	for rows.Next() {
		var i StatsBucketRowsRow
		if err := rows.Scan(&i.StartedAt, &i.ActiveSeconds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsClients = `-- name: StatsClients :many
SELECT w.client AS name, COUNT(*) AS plays,
       COALESCE(SUM(w.active_seconds), 0) AS watch_seconds
FROM watches w
WHERE w.started_at >= $1
  AND w.started_at < $2
  AND (CAST($3 AS TEXT) = ''
       OR w.media_server_id = CAST($3 AS TEXT))
  AND (CAST($4 AS TEXT) = ''
       OR w.library_id = CAST($4 AS TEXT))
  AND (CAST($5 AS TEXT) = ''
       OR (w.media_server_id = CAST($5 AS TEXT)
           AND w.media_user_id = CAST($6 AS TEXT)))
GROUP BY w.client
ORDER BY plays DESC, watch_seconds DESC, name ASC
LIMIT 1024
`

type StatsClientsParams struct {
	WindowStart       time.Time
	WindowEnd         time.Time
	MediaServerFilter string
	LibraryFilter     string
	UserServerFilter  string
	MediaUserFilter   string
}

type StatsClientsRow struct {
	Name         string
	Plays        int64
	WatchSeconds interface{}
}

func (q *Queries) StatsClients(ctx context.Context, arg StatsClientsParams) ([]StatsClientsRow, error) {
	rows, err := q.db.QueryContext(ctx, statsClients,
		arg.WindowStart,
		arg.WindowEnd,
		arg.MediaServerFilter,
		arg.LibraryFilter,
		arg.UserServerFilter,
		arg.MediaUserFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatsClientsRow{}
	for rows.Next() {
		var i StatsClientsRow
		if err := rows.Scan(&i.Name, &i.Plays, &i.WatchSeconds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsDevices = `-- name: StatsDevices :many
SELECT w.device_name AS name, COUNT(*) AS plays,
       COALESCE(SUM(w.active_seconds), 0) AS watch_seconds
FROM watches w
WHERE w.started_at >= $1
  AND w.started_at < $2
  AND (CAST($3 AS TEXT) = ''
       OR w.media_server_id = CAST($3 AS TEXT))
  AND (CAST($4 AS TEXT) = ''
       OR w.library_id = CAST($4 AS TEXT))
  AND (CAST($5 AS TEXT) = ''
       OR (w.media_server_id = CAST($5 AS TEXT)
           AND w.media_user_id = CAST($6 AS TEXT)))
GROUP BY w.device_name
ORDER BY plays DESC, watch_seconds DESC, name ASC
LIMIT 1024
`

type StatsDevicesParams struct {
	WindowStart       time.Time
	WindowEnd         time.Time
	MediaServerFilter string
	LibraryFilter     string
	UserServerFilter  string
	MediaUserFilter   string
}

type StatsDevicesRow struct {
	Name         string
	Plays        int64
	WatchSeconds interface{}
}

func (q *Queries) StatsDevices(ctx context.Context, arg StatsDevicesParams) ([]StatsDevicesRow, error) {
	rows, err := q.db.QueryContext(ctx, statsDevices,
		arg.WindowStart,
		arg.WindowEnd,
		arg.MediaServerFilter,
		arg.LibraryFilter,
		arg.UserServerFilter,
		arg.MediaUserFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatsDevicesRow{}
	for rows.Next() {
		var i StatsDevicesRow
		if err := rows.Scan(&i.Name, &i.Plays, &i.WatchSeconds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsLibraries = `-- name: StatsLibraries :many
SELECT w.media_server_id, w.library_id, MAX(w.library_name) AS library_name,
       COUNT(*) AS plays, COALESCE(SUM(w.active_seconds), 0) AS watch_seconds,
       COUNT(DISTINCT w.media_user_id) AS unique_users,
       COUNT(DISTINCT (
           CASE
               WHEN LOWER(w.item_type) = 'movie' THEN 'movie:' || w.item_id
               WHEN w.series_name <> '' THEN 'series:' || w.series_name
               ELSE 'other:' || w.item_type
           END
       )) AS unique_titles,
       MAX(w.started_at) AS last_watched_at
FROM watches w
WHERE w.started_at >= $1
  AND w.started_at < $2
  AND (CAST($3 AS TEXT) = ''
       OR w.media_server_id = CAST($3 AS TEXT))
  AND (CAST($4 AS TEXT) = ''
       OR w.library_id = CAST($4 AS TEXT))
GROUP BY w.media_server_id, w.library_id
ORDER BY plays DESC, watch_seconds DESC, library_name ASC, w.library_id ASC, w.media_server_id ASC
LIMIT $5
`

type StatsLibrariesParams struct {
	WindowStart       time.Time
	WindowEnd         time.Time
	MediaServerFilter string
	LibraryFilter     string
	RowLimit          int32
}

type StatsLibrariesRow struct {
	MediaServerID string
	LibraryID     string
	LibraryName   interface{}
	Plays         int64
	WatchSeconds  interface{}
	UniqueUsers   int64
	UniqueTitles  int64
	LastWatchedAt interface{}
}

func (q *Queries) StatsLibraries(ctx context.Context, arg StatsLibrariesParams) ([]StatsLibrariesRow, error) {
	rows, err := q.db.QueryContext(ctx, statsLibraries,
		arg.WindowStart,
		arg.WindowEnd,
		arg.MediaServerFilter,
		arg.LibraryFilter,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatsLibrariesRow{}
	for rows.Next() {
		var i StatsLibrariesRow
		if err := rows.Scan(
			&i.MediaServerID,
			&i.LibraryID,
			&i.LibraryName,
			&i.Plays,
			&i.WatchSeconds,
			&i.UniqueUsers,
			&i.UniqueTitles,
			&i.LastWatchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsMovieTitles = `-- name: StatsMovieTitles :many
SELECT w.media_server_id, w.item_id AS title_key, MAX(w.item_name) AS title_name,
       COUNT(*) AS plays, COALESCE(SUM(w.active_seconds), 0) AS watch_seconds,
       MAX(w.started_at) AS last_watched_at
FROM watches w
WHERE w.started_at >= $1
  AND w.started_at < $2
  AND LOWER(w.item_type) = 'movie'
  AND (CAST($3 AS TEXT) = ''
       OR w.media_server_id = CAST($3 AS TEXT))
  AND (CAST($4 AS TEXT) = ''
       OR w.library_id = CAST($4 AS TEXT))
  AND (CAST($5 AS TEXT) = ''
       OR (w.media_server_id = CAST($5 AS TEXT)
           AND w.media_user_id = CAST($6 AS TEXT)))
GROUP BY w.media_server_id, w.item_id
ORDER BY plays DESC, watch_seconds DESC, title_key ASC, w.media_server_id ASC
LIMIT $7
`

type StatsMovieTitlesParams struct {
	WindowStart       time.Time
	WindowEnd         time.Time
	MediaServerFilter string
	LibraryFilter     string
	UserServerFilter  string
	MediaUserFilter   string
	RowLimit          int32
}

type StatsMovieTitlesRow struct {
	MediaServerID string
	TitleKey      string
	TitleName     interface{}
	Plays         int64
	WatchSeconds  interface{}
	LastWatchedAt interface{}
}

func (q *Queries) StatsMovieTitles(ctx context.Context, arg StatsMovieTitlesParams) ([]StatsMovieTitlesRow, error) {
	rows, err := q.db.QueryContext(ctx, statsMovieTitles,
		arg.WindowStart,
		arg.WindowEnd,
		arg.MediaServerFilter,
		arg.LibraryFilter,
		arg.UserServerFilter,
		arg.MediaUserFilter,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatsMovieTitlesRow{}
	for rows.Next() {
		var i StatsMovieTitlesRow
		if err := rows.Scan(
			&i.MediaServerID,
			&i.TitleKey,
			&i.TitleName,
			&i.Plays,
			&i.WatchSeconds,
			&i.LastWatchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsOtherTitles = `-- name: StatsOtherTitles :many
SELECT w.media_server_id, w.item_type AS title_key, w.item_type AS title_name,
       COUNT(*) AS plays, COALESCE(SUM(w.active_seconds), 0) AS watch_seconds,
       MAX(w.started_at) AS last_watched_at
FROM watches w
WHERE w.started_at >= $1
  AND w.started_at < $2
  AND LOWER(w.item_type) <> 'movie'
  AND w.series_name = ''
  AND (CAST($3 AS TEXT) = ''
       OR w.media_server_id = CAST($3 AS TEXT))
  AND (CAST($4 AS TEXT) = ''
       OR w.library_id = CAST($4 AS TEXT))
  AND (CAST($5 AS TEXT) = ''
       OR (w.media_server_id = CAST($5 AS TEXT)
           AND w.media_user_id = CAST($6 AS TEXT)))
GROUP BY w.media_server_id, w.item_type
ORDER BY plays DESC, watch_seconds DESC, title_key ASC, w.media_server_id ASC
LIMIT $7
`

type StatsOtherTitlesParams struct {
	WindowStart       time.Time
	WindowEnd         time.Time
	MediaServerFilter string
	LibraryFilter     string
	UserServerFilter  string
	MediaUserFilter   string
	RowLimit          int32
}

type StatsOtherTitlesRow struct {
	MediaServerID string
	TitleKey      string
	TitleName     string
	Plays         int64
	WatchSeconds  interface{}
	LastWatchedAt interface{}
}

func (q *Queries) StatsOtherTitles(ctx context.Context, arg StatsOtherTitlesParams) ([]StatsOtherTitlesRow, error) {
	rows, err := q.db.QueryContext(ctx, statsOtherTitles,
		arg.WindowStart,
		arg.WindowEnd,
		arg.MediaServerFilter,
		arg.LibraryFilter,
		arg.UserServerFilter,
		arg.MediaUserFilter,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatsOtherTitlesRow{}
	for rows.Next() {
		var i StatsOtherTitlesRow
		if err := rows.Scan(
			&i.MediaServerID,
			&i.TitleKey,
			&i.TitleName,
			&i.Plays,
			&i.WatchSeconds,
			&i.LastWatchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsPlayMethods = `-- name: StatsPlayMethods :many
SELECT w.play_method AS name, COUNT(*) AS plays,
       COALESCE(SUM(w.active_seconds), 0) AS watch_seconds
FROM watches w
WHERE w.started_at >= $1
  AND w.started_at < $2
  AND (CAST($3 AS TEXT) = ''
       OR w.media_server_id = CAST($3 AS TEXT))
  AND (CAST($4 AS TEXT) = ''
       OR w.library_id = CAST($4 AS TEXT))
  AND (CAST($5 AS TEXT) = ''
       OR (w.media_server_id = CAST($5 AS TEXT)
           AND w.media_user_id = CAST($6 AS TEXT)))
GROUP BY w.play_method
ORDER BY plays DESC, watch_seconds DESC, name ASC
LIMIT 8
`

type StatsPlayMethodsParams struct {
	WindowStart       time.Time
	WindowEnd         time.Time
	MediaServerFilter string
	LibraryFilter     string
	UserServerFilter  string
	MediaUserFilter   string
}

type StatsPlayMethodsRow struct {
	Name         string
	Plays        int64
	WatchSeconds interface{}
}

func (q *Queries) StatsPlayMethods(ctx context.Context, arg StatsPlayMethodsParams) ([]StatsPlayMethodsRow, error) {
	rows, err := q.db.QueryContext(ctx, statsPlayMethods,
		arg.WindowStart,
		arg.WindowEnd,
		arg.MediaServerFilter,
		arg.LibraryFilter,
		arg.UserServerFilter,
		arg.MediaUserFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatsPlayMethodsRow{}
	for rows.Next() {
		var i StatsPlayMethodsRow
		if err := rows.Scan(&i.Name, &i.Plays, &i.WatchSeconds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsSeriesTitles = `-- name: StatsSeriesTitles :many
SELECT w.media_server_id, w.series_name AS title_key, w.series_name AS title_name,
       COUNT(*) AS plays, COALESCE(SUM(w.active_seconds), 0) AS watch_seconds,
       MAX(w.started_at) AS last_watched_at
FROM watches w
WHERE w.started_at >= $1
  AND w.started_at < $2
  AND LOWER(w.item_type) <> 'movie'
  AND w.series_name <> ''
  AND (CAST($3 AS TEXT) = ''
       OR w.media_server_id = CAST($3 AS TEXT))
  AND (CAST($4 AS TEXT) = ''
       OR w.library_id = CAST($4 AS TEXT))
  AND (CAST($5 AS TEXT) = ''
       OR (w.media_server_id = CAST($5 AS TEXT)
           AND w.media_user_id = CAST($6 AS TEXT)))
GROUP BY w.media_server_id, w.series_name
ORDER BY plays DESC, watch_seconds DESC, title_key ASC, w.media_server_id ASC
LIMIT $7
`

type StatsSeriesTitlesParams struct {
	WindowStart       time.Time
	WindowEnd         time.Time
	MediaServerFilter string
	LibraryFilter     string
	UserServerFilter  string
	MediaUserFilter   string
	RowLimit          int32
}

type StatsSeriesTitlesRow struct {
	MediaServerID string
	TitleKey      string
	TitleName     string
	Plays         int64
	WatchSeconds  interface{}
	LastWatchedAt interface{}
}

func (q *Queries) StatsSeriesTitles(ctx context.Context, arg StatsSeriesTitlesParams) ([]StatsSeriesTitlesRow, error) {
	rows, err := q.db.QueryContext(ctx, statsSeriesTitles,
		arg.WindowStart,
		arg.WindowEnd,
		arg.MediaServerFilter,
		arg.LibraryFilter,
		arg.UserServerFilter,
		arg.MediaUserFilter,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatsSeriesTitlesRow{}
	for rows.Next() {
		var i StatsSeriesTitlesRow
		if err := rows.Scan(
			&i.MediaServerID,
			&i.TitleKey,
			&i.TitleName,
			&i.Plays,
			&i.WatchSeconds,
			&i.LastWatchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsTotals = `-- name: StatsTotals :one

SELECT
    COUNT(*) AS plays,
    COALESCE(SUM(w.active_seconds), 0) AS watch_seconds,
    COUNT(DISTINCT (w.media_server_id || ':' || w.media_user_id)) AS unique_users,
    COUNT(DISTINCT (
        w.media_server_id || ':' ||
        CASE
            WHEN LOWER(w.item_type) = 'movie' THEN 'movie:' || w.item_id
            WHEN w.series_name <> '' THEN 'series:' || w.series_name
            ELSE 'other:' || w.item_type
        END
    )) AS unique_titles
FROM watches w
WHERE w.started_at >= $1
  AND w.started_at < $2
  AND (CAST($3 AS TEXT) = ''
       OR w.media_server_id = CAST($3 AS TEXT))
  AND (CAST($4 AS TEXT) = ''
       OR w.library_id = CAST($4 AS TEXT))
  AND (CAST($5 AS TEXT) = ''
       OR (w.media_server_id = CAST($5 AS TEXT)
           AND w.media_user_id = CAST($6 AS TEXT)))
`

type StatsTotalsParams struct {
	WindowStart       time.Time
	WindowEnd         time.Time
	MediaServerFilter string
	LibraryFilter     string
	UserServerFilter  string
	MediaUserFilter   string
}

type StatsTotalsRow struct {
	Plays        int64
	WatchSeconds interface{}
	UniqueUsers  int64
	UniqueTitles int64
}

// Statistics queries are portable across SQLite and PostgreSQL.
func (q *Queries) StatsTotals(ctx context.Context, arg StatsTotalsParams) (StatsTotalsRow, error) {
	row := q.db.QueryRowContext(ctx, statsTotals,
		arg.WindowStart,
		arg.WindowEnd,
		arg.MediaServerFilter,
		arg.LibraryFilter,
		arg.UserServerFilter,
		arg.MediaUserFilter,
	)
	var i StatsTotalsRow
	err := row.Scan(
		&i.Plays,
		&i.WatchSeconds,
		&i.UniqueUsers,
		&i.UniqueTitles,
	)
	return i, err
}

const statsUserRecentWatches = `-- name: StatsUserRecentWatches :many
SELECT w.id, w.media_server_id, w.media_user_id, w.username, w.device_id, w.device_name, w.client, w.server_session_id, w.item_id, w.item_name, w.item_type, w.series_name, w.season_number, w.episode_number, w.play_method, w.state, w.started_at, w.last_seen_at, w.ended_at, w.active_seconds, w.last_position_ms, w.source, w.created_at, w.updated_at, w.library_id, w.library_name, w.stream_container, w.stream_video_codec, w.stream_audio_codec, w.stream_bitrate, w.stream_width, w.stream_height, w.stream_framerate_hundredths, w.stream_audio_channels, w.stream_is_video_direct, w.stream_is_audio_direct, w.stream_transcode_reasons, ms.name AS media_server_name
FROM watches w
JOIN media_servers ms ON ms.id = w.media_server_id
WHERE w.started_at >= $1
  AND w.started_at < $2
  AND w.media_server_id = $3
  AND w.media_user_id = $4
  AND (CAST($5 AS TEXT) = ''
       OR w.library_id = CAST($5 AS TEXT))
ORDER BY w.started_at DESC, w.id DESC
LIMIT 20
`

type StatsUserRecentWatchesParams struct {
	WindowStart   time.Time
	WindowEnd     time.Time
	UserServerID  string
	MediaUserID   string
	LibraryFilter string
}

type StatsUserRecentWatchesRow struct {
	ID                        string
	MediaServerID             string
	MediaUserID               string
	Username                  string
	DeviceID                  string
	DeviceName                string
	Client                    string
	ServerSessionID           string
	ItemID                    string
	ItemName                  string
	ItemType                  string
	SeriesName                string
	SeasonNumber              sql.NullInt32
	EpisodeNumber             sql.NullInt32
	PlayMethod                string
	State                     string
	StartedAt                 time.Time
	LastSeenAt                time.Time
	EndedAt                   sql.NullTime
	ActiveSeconds             int64
	LastPositionMs            int64
	Source                    string
	CreatedAt                 time.Time
	UpdatedAt                 time.Time
	LibraryID                 string
	LibraryName               string
	StreamContainer           sql.NullString
	StreamVideoCodec          sql.NullString
	StreamAudioCodec          sql.NullString
	StreamBitrate             sql.NullInt64
	StreamWidth               sql.NullInt32
	StreamHeight              sql.NullInt32
	StreamFramerateHundredths sql.NullInt32
	StreamAudioChannels       sql.NullInt32
	StreamIsVideoDirect       sql.NullBool
	StreamIsAudioDirect       sql.NullBool
	StreamTranscodeReasons    sql.NullString
	MediaServerName           string
}

func (q *Queries) StatsUserRecentWatches(ctx context.Context, arg StatsUserRecentWatchesParams) ([]StatsUserRecentWatchesRow, error) {
	rows, err := q.db.QueryContext(ctx, statsUserRecentWatches,
		arg.WindowStart,
		arg.WindowEnd,
		arg.UserServerID,
		arg.MediaUserID,
		arg.LibraryFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatsUserRecentWatchesRow{}
	for rows.Next() {
		var i StatsUserRecentWatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.MediaServerID,
			&i.MediaUserID,
			&i.Username,
			&i.DeviceID,
			&i.DeviceName,
			&i.Client,
			&i.ServerSessionID,
			&i.ItemID,
			&i.ItemName,
			&i.ItemType,
			&i.SeriesName,
			&i.SeasonNumber,
			&i.EpisodeNumber,
			&i.PlayMethod,
			&i.State,
			&i.StartedAt,
			&i.LastSeenAt,
			&i.EndedAt,
			&i.ActiveSeconds,
			&i.LastPositionMs,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LibraryID,
			&i.LibraryName,
			&i.StreamContainer,
			&i.StreamVideoCodec,
			&i.StreamAudioCodec,
			&i.StreamBitrate,
			&i.StreamWidth,
			&i.StreamHeight,
			&i.StreamFramerateHundredths,
			&i.StreamAudioChannels,
			&i.StreamIsVideoDirect,
			&i.StreamIsAudioDirect,
			&i.StreamTranscodeReasons,
			&i.MediaServerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsUsers = `-- name: StatsUsers :many
SELECT w.media_server_id, w.media_user_id, MAX(w.username) AS username,
       COUNT(*) AS plays, COALESCE(SUM(w.active_seconds), 0) AS watch_seconds,
       MAX(w.started_at) AS last_watched_at
FROM watches w
WHERE w.started_at >= $1
  AND w.started_at < $2
  AND (CAST($3 AS TEXT) = ''
       OR w.media_server_id = CAST($3 AS TEXT))
  AND (CAST($4 AS TEXT) = ''
       OR w.library_id = CAST($4 AS TEXT))
GROUP BY w.media_server_id, w.media_user_id
ORDER BY plays DESC, watch_seconds DESC, w.media_user_id ASC, w.media_server_id ASC
LIMIT $5
`

type StatsUsersParams struct {
	WindowStart       time.Time
	WindowEnd         time.Time
	MediaServerFilter string
	LibraryFilter     string
	RowLimit          int32
}

type StatsUsersRow struct {
	MediaServerID string
	MediaUserID   string
	Username      interface{}
	Plays         int64
	WatchSeconds  interface{}
	LastWatchedAt interface{}
}

func (q *Queries) StatsUsers(ctx context.Context, arg StatsUsersParams) ([]StatsUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, statsUsers,
		arg.WindowStart,
		arg.WindowEnd,
		arg.MediaServerFilter,
		arg.LibraryFilter,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatsUsersRow{}
	for rows.Next() {
		var i StatsUsersRow
		if err := rows.Scan(
			&i.MediaServerID,
			&i.MediaUserID,
			&i.Username,
			&i.Plays,
			&i.WatchSeconds,
			&i.LastWatchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
