-- SQLite migration 00001: accounts (ADR 0004, ADR 0006 item 1).
-- The PostgreSQL twin lives at ../postgres/00001_create_accounts.sql; the parity
-- test asserts both directories carry the same file names and that the
-- resulting tables expose the same columns.

-- +goose Up
-- +goose StatementBegin
CREATE TABLE accounts (
    -- UUID string generated by Bloom (core.NewID), so both engines store the
    -- same value and no engine-specific id type leaks into the domain.
    id         TEXT PRIMARY KEY NOT NULL,
    username   TEXT NOT NULL UNIQUE,
    -- Timestamp representation (ADR 0004 item 5): SQLite has no datetime type,
    -- so created_at is TEXT holding RFC 3339 in UTC with exactly six fractional
    -- digits, e.g. 2026-09-22T10:30:00.123456Z. That is (a) lossless against
    -- PostgreSQL's microsecond TIMESTAMPTZ, (b) lexically sortable, and (c) a
    -- format SQLite's date/time functions accept directly. The Go adapter
    -- formats and parses it explicitly; no driver-level time magic is relied on.
    created_at TEXT NOT NULL
) STRICT;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE accounts;
-- +goose StatementEnd
