// Package jellyfinapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package jellyfinapi

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AudioSpatialFormat.
const (
	AudioSpatialFormatDTSX       AudioSpatialFormat = "DTSX"
	AudioSpatialFormatDolbyAtmos AudioSpatialFormat = "DolbyAtmos"
	AudioSpatialFormatNone       AudioSpatialFormat = "None"
)

// Valid indicates whether the value is a known member of the AudioSpatialFormat enum.
func (e AudioSpatialFormat) Valid() bool {
	switch e {
	case AudioSpatialFormatDTSX:
		return true
	case AudioSpatialFormatDolbyAtmos:
		return true
	case AudioSpatialFormatNone:
		return true
	default:
		return false
	}
}

// Defines values for BaseItemKind.
const (
	BaseItemKindAggregateFolder       BaseItemKind = "AggregateFolder"
	BaseItemKindAudio                 BaseItemKind = "Audio"
	BaseItemKindAudioBook             BaseItemKind = "AudioBook"
	BaseItemKindBasePluginFolder      BaseItemKind = "BasePluginFolder"
	BaseItemKindBook                  BaseItemKind = "Book"
	BaseItemKindBoxSet                BaseItemKind = "BoxSet"
	BaseItemKindChannel               BaseItemKind = "Channel"
	BaseItemKindChannelFolderItem     BaseItemKind = "ChannelFolderItem"
	BaseItemKindCollectionFolder      BaseItemKind = "CollectionFolder"
	BaseItemKindEpisode               BaseItemKind = "Episode"
	BaseItemKindFolder                BaseItemKind = "Folder"
	BaseItemKindGenre                 BaseItemKind = "Genre"
	BaseItemKindLiveTvChannel         BaseItemKind = "LiveTvChannel"
	BaseItemKindLiveTvProgram         BaseItemKind = "LiveTvProgram"
	BaseItemKindManualPlaylistsFolder BaseItemKind = "ManualPlaylistsFolder"
	BaseItemKindMovie                 BaseItemKind = "Movie"
	BaseItemKindMusicAlbum            BaseItemKind = "MusicAlbum"
	BaseItemKindMusicArtist           BaseItemKind = "MusicArtist"
	BaseItemKindMusicGenre            BaseItemKind = "MusicGenre"
	BaseItemKindMusicVideo            BaseItemKind = "MusicVideo"
	BaseItemKindPerson                BaseItemKind = "Person"
	BaseItemKindPhoto                 BaseItemKind = "Photo"
	BaseItemKindPhotoAlbum            BaseItemKind = "PhotoAlbum"
	BaseItemKindPlaylist              BaseItemKind = "Playlist"
	BaseItemKindPlaylistsFolder       BaseItemKind = "PlaylistsFolder"
	BaseItemKindProgram               BaseItemKind = "Program"
	BaseItemKindRecording             BaseItemKind = "Recording"
	BaseItemKindSeason                BaseItemKind = "Season"
	BaseItemKindSeries                BaseItemKind = "Series"
	BaseItemKindStudio                BaseItemKind = "Studio"
	BaseItemKindTrailer               BaseItemKind = "Trailer"
	BaseItemKindTvChannel             BaseItemKind = "TvChannel"
	BaseItemKindTvProgram             BaseItemKind = "TvProgram"
	BaseItemKindUserRootFolder        BaseItemKind = "UserRootFolder"
	BaseItemKindUserView              BaseItemKind = "UserView"
	BaseItemKindVideo                 BaseItemKind = "Video"
	BaseItemKindYear                  BaseItemKind = "Year"
)

// Valid indicates whether the value is a known member of the BaseItemKind enum.
func (e BaseItemKind) Valid() bool {
	switch e {
	case BaseItemKindAggregateFolder:
		return true
	case BaseItemKindAudio:
		return true
	case BaseItemKindAudioBook:
		return true
	case BaseItemKindBasePluginFolder:
		return true
	case BaseItemKindBook:
		return true
	case BaseItemKindBoxSet:
		return true
	case BaseItemKindChannel:
		return true
	case BaseItemKindChannelFolderItem:
		return true
	case BaseItemKindCollectionFolder:
		return true
	case BaseItemKindEpisode:
		return true
	case BaseItemKindFolder:
		return true
	case BaseItemKindGenre:
		return true
	case BaseItemKindLiveTvChannel:
		return true
	case BaseItemKindLiveTvProgram:
		return true
	case BaseItemKindManualPlaylistsFolder:
		return true
	case BaseItemKindMovie:
		return true
	case BaseItemKindMusicAlbum:
		return true
	case BaseItemKindMusicArtist:
		return true
	case BaseItemKindMusicGenre:
		return true
	case BaseItemKindMusicVideo:
		return true
	case BaseItemKindPerson:
		return true
	case BaseItemKindPhoto:
		return true
	case BaseItemKindPhotoAlbum:
		return true
	case BaseItemKindPlaylist:
		return true
	case BaseItemKindPlaylistsFolder:
		return true
	case BaseItemKindProgram:
		return true
	case BaseItemKindRecording:
		return true
	case BaseItemKindSeason:
		return true
	case BaseItemKindSeries:
		return true
	case BaseItemKindStudio:
		return true
	case BaseItemKindTrailer:
		return true
	case BaseItemKindTvChannel:
		return true
	case BaseItemKindTvProgram:
		return true
	case BaseItemKindUserRootFolder:
		return true
	case BaseItemKindUserView:
		return true
	case BaseItemKindVideo:
		return true
	case BaseItemKindYear:
		return true
	default:
		return false
	}
}

// Defines values for ChannelType.
const (
	Radio ChannelType = "Radio"
	TV    ChannelType = "TV"
)

// Valid indicates whether the value is a known member of the ChannelType enum.
func (e ChannelType) Valid() bool {
	switch e {
	case Radio:
		return true
	case TV:
		return true
	default:
		return false
	}
}

// Defines values for CollectionType.
const (
	CollectionTypeBooks       CollectionType = "books"
	CollectionTypeBoxsets     CollectionType = "boxsets"
	CollectionTypeFolders     CollectionType = "folders"
	CollectionTypeHomevideos  CollectionType = "homevideos"
	CollectionTypeLivetv      CollectionType = "livetv"
	CollectionTypeMovies      CollectionType = "movies"
	CollectionTypeMusic       CollectionType = "music"
	CollectionTypeMusicvideos CollectionType = "musicvideos"
	CollectionTypePhotos      CollectionType = "photos"
	CollectionTypePlaylists   CollectionType = "playlists"
	CollectionTypeTrailers    CollectionType = "trailers"
	CollectionTypeTvshows     CollectionType = "tvshows"
	CollectionTypeUnknown     CollectionType = "unknown"
)

// Valid indicates whether the value is a known member of the CollectionType enum.
func (e CollectionType) Valid() bool {
	switch e {
	case CollectionTypeBooks:
		return true
	case CollectionTypeBoxsets:
		return true
	case CollectionTypeFolders:
		return true
	case CollectionTypeHomevideos:
		return true
	case CollectionTypeLivetv:
		return true
	case CollectionTypeMovies:
		return true
	case CollectionTypeMusic:
		return true
	case CollectionTypeMusicvideos:
		return true
	case CollectionTypePhotos:
		return true
	case CollectionTypePlaylists:
		return true
	case CollectionTypeTrailers:
		return true
	case CollectionTypeTvshows:
		return true
	case CollectionTypeUnknown:
		return true
	default:
		return false
	}
}

// Defines values for CollectionTypeOptions.
const (
	CollectionTypeOptionsBooks       CollectionTypeOptions = "books"
	CollectionTypeOptionsBoxsets     CollectionTypeOptions = "boxsets"
	CollectionTypeOptionsHomevideos  CollectionTypeOptions = "homevideos"
	CollectionTypeOptionsMixed       CollectionTypeOptions = "mixed"
	CollectionTypeOptionsMovies      CollectionTypeOptions = "movies"
	CollectionTypeOptionsMusic       CollectionTypeOptions = "music"
	CollectionTypeOptionsMusicvideos CollectionTypeOptions = "musicvideos"
	CollectionTypeOptionsTvshows     CollectionTypeOptions = "tvshows"
)

// Valid indicates whether the value is a known member of the CollectionTypeOptions enum.
func (e CollectionTypeOptions) Valid() bool {
	switch e {
	case CollectionTypeOptionsBooks:
		return true
	case CollectionTypeOptionsBoxsets:
		return true
	case CollectionTypeOptionsHomevideos:
		return true
	case CollectionTypeOptionsMixed:
		return true
	case CollectionTypeOptionsMovies:
		return true
	case CollectionTypeOptionsMusic:
		return true
	case CollectionTypeOptionsMusicvideos:
		return true
	case CollectionTypeOptionsTvshows:
		return true
	default:
		return false
	}
}

// Defines values for DayOfWeek.
const (
	Friday    DayOfWeek = "Friday"
	Monday    DayOfWeek = "Monday"
	Saturday  DayOfWeek = "Saturday"
	Sunday    DayOfWeek = "Sunday"
	Thursday  DayOfWeek = "Thursday"
	Tuesday   DayOfWeek = "Tuesday"
	Wednesday DayOfWeek = "Wednesday"
)

// Valid indicates whether the value is a known member of the DayOfWeek enum.
func (e DayOfWeek) Valid() bool {
	switch e {
	case Friday:
		return true
	case Monday:
		return true
	case Saturday:
		return true
	case Sunday:
		return true
	case Thursday:
		return true
	case Tuesday:
		return true
	case Wednesday:
		return true
	default:
		return false
	}
}

// Defines values for EmbeddedSubtitleOptions.
const (
	AllowAll   EmbeddedSubtitleOptions = "AllowAll"
	AllowImage EmbeddedSubtitleOptions = "AllowImage"
	AllowNone  EmbeddedSubtitleOptions = "AllowNone"
	AllowText  EmbeddedSubtitleOptions = "AllowText"
)

// Valid indicates whether the value is a known member of the EmbeddedSubtitleOptions enum.
func (e EmbeddedSubtitleOptions) Valid() bool {
	switch e {
	case AllowAll:
		return true
	case AllowImage:
		return true
	case AllowNone:
		return true
	case AllowText:
		return true
	default:
		return false
	}
}

// Defines values for ExtraType.
const (
	ExtraTypeBehindTheScenes ExtraType = "BehindTheScenes"
	ExtraTypeClip            ExtraType = "Clip"
	ExtraTypeDeletedScene    ExtraType = "DeletedScene"
	ExtraTypeFeaturette      ExtraType = "Featurette"
	ExtraTypeInterview       ExtraType = "Interview"
	ExtraTypeSample          ExtraType = "Sample"
	ExtraTypeScene           ExtraType = "Scene"
	ExtraTypeShort           ExtraType = "Short"
	ExtraTypeThemeSong       ExtraType = "ThemeSong"
	ExtraTypeThemeVideo      ExtraType = "ThemeVideo"
	ExtraTypeTrailer         ExtraType = "Trailer"
	ExtraTypeUnknown         ExtraType = "Unknown"
)

// Valid indicates whether the value is a known member of the ExtraType enum.
func (e ExtraType) Valid() bool {
	switch e {
	case ExtraTypeBehindTheScenes:
		return true
	case ExtraTypeClip:
		return true
	case ExtraTypeDeletedScene:
		return true
	case ExtraTypeFeaturette:
		return true
	case ExtraTypeInterview:
		return true
	case ExtraTypeSample:
		return true
	case ExtraTypeScene:
		return true
	case ExtraTypeShort:
		return true
	case ExtraTypeThemeSong:
		return true
	case ExtraTypeThemeVideo:
		return true
	case ExtraTypeTrailer:
		return true
	case ExtraTypeUnknown:
		return true
	default:
		return false
	}
}

// Defines values for ImageOrientation.
const (
	BottomLeft  ImageOrientation = "BottomLeft"
	BottomRight ImageOrientation = "BottomRight"
	LeftBottom  ImageOrientation = "LeftBottom"
	LeftTop     ImageOrientation = "LeftTop"
	RightBottom ImageOrientation = "RightBottom"
	RightTop    ImageOrientation = "RightTop"
	TopLeft     ImageOrientation = "TopLeft"
	TopRight    ImageOrientation = "TopRight"
)

// Valid indicates whether the value is a known member of the ImageOrientation enum.
func (e ImageOrientation) Valid() bool {
	switch e {
	case BottomLeft:
		return true
	case BottomRight:
		return true
	case LeftBottom:
		return true
	case LeftTop:
		return true
	case RightBottom:
		return true
	case RightTop:
		return true
	case TopLeft:
		return true
	case TopRight:
		return true
	default:
		return false
	}
}

// Defines values for ImageType.
const (
	Art        ImageType = "Art"
	Backdrop   ImageType = "Backdrop"
	Banner     ImageType = "Banner"
	Box        ImageType = "Box"
	BoxRear    ImageType = "BoxRear"
	Chapter    ImageType = "Chapter"
	Disc       ImageType = "Disc"
	Logo       ImageType = "Logo"
	Menu       ImageType = "Menu"
	Primary    ImageType = "Primary"
	Profile    ImageType = "Profile"
	Screenshot ImageType = "Screenshot"
	Thumb      ImageType = "Thumb"
)

// Valid indicates whether the value is a known member of the ImageType enum.
func (e ImageType) Valid() bool {
	switch e {
	case Art:
		return true
	case Backdrop:
		return true
	case Banner:
		return true
	case Box:
		return true
	case BoxRear:
		return true
	case Chapter:
		return true
	case Disc:
		return true
	case Logo:
		return true
	case Menu:
		return true
	case Primary:
		return true
	case Profile:
		return true
	case Screenshot:
		return true
	case Thumb:
		return true
	default:
		return false
	}
}

// Defines values for IsoType.
const (
	IsoTypeBluRay IsoType = "BluRay"
	IsoTypeDvd    IsoType = "Dvd"
)

// Valid indicates whether the value is a known member of the IsoType enum.
func (e IsoType) Valid() bool {
	switch e {
	case IsoTypeBluRay:
		return true
	case IsoTypeDvd:
		return true
	default:
		return false
	}
}

// Defines values for LocationType.
const (
	FileSystem LocationType = "FileSystem"
	Offline    LocationType = "Offline"
	Remote     LocationType = "Remote"
	Virtual    LocationType = "Virtual"
)

// Valid indicates whether the value is a known member of the LocationType enum.
func (e LocationType) Valid() bool {
	switch e {
	case FileSystem:
		return true
	case Offline:
		return true
	case Remote:
		return true
	case Virtual:
		return true
	default:
		return false
	}
}

// Defines values for MediaProtocol.
const (
	MediaProtocolFile MediaProtocol = "File"
	MediaProtocolFtp  MediaProtocol = "Ftp"
	MediaProtocolHttp MediaProtocol = "Http"
	MediaProtocolRtmp MediaProtocol = "Rtmp"
	MediaProtocolRtp  MediaProtocol = "Rtp"
	MediaProtocolRtsp MediaProtocol = "Rtsp"
	MediaProtocolUdp  MediaProtocol = "Udp"
)

// Valid indicates whether the value is a known member of the MediaProtocol enum.
func (e MediaProtocol) Valid() bool {
	switch e {
	case MediaProtocolFile:
		return true
	case MediaProtocolFtp:
		return true
	case MediaProtocolHttp:
		return true
	case MediaProtocolRtmp:
		return true
	case MediaProtocolRtp:
		return true
	case MediaProtocolRtsp:
		return true
	case MediaProtocolUdp:
		return true
	default:
		return false
	}
}

// Defines values for MediaSourceType.
const (
	Default     MediaSourceType = "Default"
	Grouping    MediaSourceType = "Grouping"
	Placeholder MediaSourceType = "Placeholder"
)

// Valid indicates whether the value is a known member of the MediaSourceType enum.
func (e MediaSourceType) Valid() bool {
	switch e {
	case Default:
		return true
	case Grouping:
		return true
	case Placeholder:
		return true
	default:
		return false
	}
}

// Defines values for MediaStreamProtocol.
const (
	MediaStreamProtocolHls  MediaStreamProtocol = "hls"
	MediaStreamProtocolHttp MediaStreamProtocol = "http"
)

// Valid indicates whether the value is a known member of the MediaStreamProtocol enum.
func (e MediaStreamProtocol) Valid() bool {
	switch e {
	case MediaStreamProtocolHls:
		return true
	case MediaStreamProtocolHttp:
		return true
	default:
		return false
	}
}

// Defines values for MediaStreamType.
const (
	MediaStreamTypeAudio         MediaStreamType = "Audio"
	MediaStreamTypeData          MediaStreamType = "Data"
	MediaStreamTypeEmbeddedImage MediaStreamType = "EmbeddedImage"
	MediaStreamTypeLyric         MediaStreamType = "Lyric"
	MediaStreamTypeSubtitle      MediaStreamType = "Subtitle"
	MediaStreamTypeVideo         MediaStreamType = "Video"
)

// Valid indicates whether the value is a known member of the MediaStreamType enum.
func (e MediaStreamType) Valid() bool {
	switch e {
	case MediaStreamTypeAudio:
		return true
	case MediaStreamTypeData:
		return true
	case MediaStreamTypeEmbeddedImage:
		return true
	case MediaStreamTypeLyric:
		return true
	case MediaStreamTypeSubtitle:
		return true
	case MediaStreamTypeVideo:
		return true
	default:
		return false
	}
}

// Defines values for MediaType.
const (
	MediaTypeAudio   MediaType = "Audio"
	MediaTypeBook    MediaType = "Book"
	MediaTypePhoto   MediaType = "Photo"
	MediaTypeUnknown MediaType = "Unknown"
	MediaTypeVideo   MediaType = "Video"
)

// Valid indicates whether the value is a known member of the MediaType enum.
func (e MediaType) Valid() bool {
	switch e {
	case MediaTypeAudio:
		return true
	case MediaTypeBook:
		return true
	case MediaTypePhoto:
		return true
	case MediaTypeUnknown:
		return true
	case MediaTypeVideo:
		return true
	default:
		return false
	}
}

// Defines values for MetadataField.
const (
	Cast                MetadataField = "Cast"
	Genres              MetadataField = "Genres"
	Name                MetadataField = "Name"
	OfficialRating      MetadataField = "OfficialRating"
	Overview            MetadataField = "Overview"
	ProductionLocations MetadataField = "ProductionLocations"
	Runtime             MetadataField = "Runtime"
	Studios             MetadataField = "Studios"
	Tags                MetadataField = "Tags"
)

// Valid indicates whether the value is a known member of the MetadataField enum.
func (e MetadataField) Valid() bool {
	switch e {
	case Cast:
		return true
	case Genres:
		return true
	case Name:
		return true
	case OfficialRating:
		return true
	case Overview:
		return true
	case ProductionLocations:
		return true
	case Runtime:
		return true
	case Studios:
		return true
	case Tags:
		return true
	default:
		return false
	}
}

// Defines values for PersonKind.
const (
	PersonKindActor       PersonKind = "Actor"
	PersonKindAlbumArtist PersonKind = "AlbumArtist"
	PersonKindArranger    PersonKind = "Arranger"
	PersonKindArtist      PersonKind = "Artist"
	PersonKindAuthor      PersonKind = "Author"
	PersonKindColorist    PersonKind = "Colorist"
	PersonKindComposer    PersonKind = "Composer"
	PersonKindConductor   PersonKind = "Conductor"
	PersonKindCoverArtist PersonKind = "CoverArtist"
	PersonKindCreator     PersonKind = "Creator"
	PersonKindDirector    PersonKind = "Director"
	PersonKindEditor      PersonKind = "Editor"
	PersonKindEngineer    PersonKind = "Engineer"
	PersonKindGuestStar   PersonKind = "GuestStar"
	PersonKindIllustrator PersonKind = "Illustrator"
	PersonKindInker       PersonKind = "Inker"
	PersonKindLetterer    PersonKind = "Letterer"
	PersonKindLyricist    PersonKind = "Lyricist"
	PersonKindMixer       PersonKind = "Mixer"
	PersonKindNarrator    PersonKind = "Narrator"
	PersonKindPenciller   PersonKind = "Penciller"
	PersonKindProducer    PersonKind = "Producer"
	PersonKindRemixer     PersonKind = "Remixer"
	PersonKindTranslator  PersonKind = "Translator"
	PersonKindUnknown     PersonKind = "Unknown"
	PersonKindWriter      PersonKind = "Writer"
)

// Valid indicates whether the value is a known member of the PersonKind enum.
func (e PersonKind) Valid() bool {
	switch e {
	case PersonKindActor:
		return true
	case PersonKindAlbumArtist:
		return true
	case PersonKindArranger:
		return true
	case PersonKindArtist:
		return true
	case PersonKindAuthor:
		return true
	case PersonKindColorist:
		return true
	case PersonKindComposer:
		return true
	case PersonKindConductor:
		return true
	case PersonKindCoverArtist:
		return true
	case PersonKindCreator:
		return true
	case PersonKindDirector:
		return true
	case PersonKindEditor:
		return true
	case PersonKindEngineer:
		return true
	case PersonKindGuestStar:
		return true
	case PersonKindIllustrator:
		return true
	case PersonKindInker:
		return true
	case PersonKindLetterer:
		return true
	case PersonKindLyricist:
		return true
	case PersonKindMixer:
		return true
	case PersonKindNarrator:
		return true
	case PersonKindPenciller:
		return true
	case PersonKindProducer:
		return true
	case PersonKindRemixer:
		return true
	case PersonKindTranslator:
		return true
	case PersonKindUnknown:
		return true
	case PersonKindWriter:
		return true
	default:
		return false
	}
}

// Defines values for PlayAccess.
const (
	PlayAccessFull PlayAccess = "Full"
	PlayAccessNone PlayAccess = "None"
)

// Valid indicates whether the value is a known member of the PlayAccess enum.
func (e PlayAccess) Valid() bool {
	switch e {
	case PlayAccessFull:
		return true
	case PlayAccessNone:
		return true
	default:
		return false
	}
}

// Defines values for ProgramAudio.
const (
	Atmos        ProgramAudio = "Atmos"
	Dolby        ProgramAudio = "Dolby"
	DolbyDigital ProgramAudio = "DolbyDigital"
	Mono         ProgramAudio = "Mono"
	Stereo       ProgramAudio = "Stereo"
	Thx          ProgramAudio = "Thx"
)

// Valid indicates whether the value is a known member of the ProgramAudio enum.
func (e ProgramAudio) Valid() bool {
	switch e {
	case Atmos:
		return true
	case Dolby:
		return true
	case DolbyDigital:
		return true
	case Mono:
		return true
	case Stereo:
		return true
	case Thx:
		return true
	default:
		return false
	}
}

// Defines values for SubtitleDeliveryMethod.
const (
	SubtitleDeliveryMethodDrop     SubtitleDeliveryMethod = "Drop"
	SubtitleDeliveryMethodEmbed    SubtitleDeliveryMethod = "Embed"
	SubtitleDeliveryMethodEncode   SubtitleDeliveryMethod = "Encode"
	SubtitleDeliveryMethodExternal SubtitleDeliveryMethod = "External"
	SubtitleDeliveryMethodHls      SubtitleDeliveryMethod = "Hls"
)

// Valid indicates whether the value is a known member of the SubtitleDeliveryMethod enum.
func (e SubtitleDeliveryMethod) Valid() bool {
	switch e {
	case SubtitleDeliveryMethodDrop:
		return true
	case SubtitleDeliveryMethodEmbed:
		return true
	case SubtitleDeliveryMethodEncode:
		return true
	case SubtitleDeliveryMethodExternal:
		return true
	case SubtitleDeliveryMethodHls:
		return true
	default:
		return false
	}
}

// Defines values for TransportStreamTimestamp.
const (
	TransportStreamTimestampNone  TransportStreamTimestamp = "None"
	TransportStreamTimestampValid TransportStreamTimestamp = "Valid"
	TransportStreamTimestampZero  TransportStreamTimestamp = "Zero"
)

// Valid indicates whether the value is a known member of the TransportStreamTimestamp enum.
func (e TransportStreamTimestamp) Valid() bool {
	switch e {
	case TransportStreamTimestampNone:
		return true
	case TransportStreamTimestampValid:
		return true
	case TransportStreamTimestampZero:
		return true
	default:
		return false
	}
}

// Defines values for Video3DFormat.
const (
	FullSideBySide   Video3DFormat = "FullSideBySide"
	FullTopAndBottom Video3DFormat = "FullTopAndBottom"
	HalfSideBySide   Video3DFormat = "HalfSideBySide"
	HalfTopAndBottom Video3DFormat = "HalfTopAndBottom"
	MVC              Video3DFormat = "MVC"
)

// Valid indicates whether the value is a known member of the Video3DFormat enum.
func (e Video3DFormat) Valid() bool {
	switch e {
	case FullSideBySide:
		return true
	case FullTopAndBottom:
		return true
	case HalfSideBySide:
		return true
	case HalfTopAndBottom:
		return true
	case MVC:
		return true
	default:
		return false
	}
}

// Defines values for VideoRange.
const (
	VideoRangeHDR     VideoRange = "HDR"
	VideoRangeSDR     VideoRange = "SDR"
	VideoRangeUnknown VideoRange = "Unknown"
)

// Valid indicates whether the value is a known member of the VideoRange enum.
func (e VideoRange) Valid() bool {
	switch e {
	case VideoRangeHDR:
		return true
	case VideoRangeSDR:
		return true
	case VideoRangeUnknown:
		return true
	default:
		return false
	}
}

// Defines values for VideoRangeType.
const (
	VideoRangeTypeDOVI                VideoRangeType = "DOVI"
	VideoRangeTypeDOVIInvalid         VideoRangeType = "DOVIInvalid"
	VideoRangeTypeDOVIWithEL          VideoRangeType = "DOVIWithEL"
	VideoRangeTypeDOVIWithELHDR10Plus VideoRangeType = "DOVIWithELHDR10Plus"
	VideoRangeTypeDOVIWithHDR10       VideoRangeType = "DOVIWithHDR10"
	VideoRangeTypeDOVIWithHDR10Plus   VideoRangeType = "DOVIWithHDR10Plus"
	VideoRangeTypeDOVIWithHLG         VideoRangeType = "DOVIWithHLG"
	VideoRangeTypeDOVIWithSDR         VideoRangeType = "DOVIWithSDR"
	VideoRangeTypeHDR10               VideoRangeType = "HDR10"
	VideoRangeTypeHDR10Plus           VideoRangeType = "HDR10Plus"
	VideoRangeTypeHLG                 VideoRangeType = "HLG"
	VideoRangeTypeSDR                 VideoRangeType = "SDR"
	VideoRangeTypeUnknown             VideoRangeType = "Unknown"
)

// Valid indicates whether the value is a known member of the VideoRangeType enum.
func (e VideoRangeType) Valid() bool {
	switch e {
	case VideoRangeTypeDOVI:
		return true
	case VideoRangeTypeDOVIInvalid:
		return true
	case VideoRangeTypeDOVIWithEL:
		return true
	case VideoRangeTypeDOVIWithELHDR10Plus:
		return true
	case VideoRangeTypeDOVIWithHDR10:
		return true
	case VideoRangeTypeDOVIWithHDR10Plus:
		return true
	case VideoRangeTypeDOVIWithHLG:
		return true
	case VideoRangeTypeDOVIWithSDR:
		return true
	case VideoRangeTypeHDR10:
		return true
	case VideoRangeTypeHDR10Plus:
		return true
	case VideoRangeTypeHLG:
		return true
	case VideoRangeTypeSDR:
		return true
	case VideoRangeTypeUnknown:
		return true
	default:
		return false
	}
}

// Defines values for VideoType.
const (
	VideoTypeBluRay    VideoType = "BluRay"
	VideoTypeDvd       VideoType = "Dvd"
	VideoTypeIso       VideoType = "Iso"
	VideoTypeVideoFile VideoType = "VideoFile"
)

// Valid indicates whether the value is a known member of the VideoType enum.
func (e VideoType) Valid() bool {
	switch e {
	case VideoTypeBluRay:
		return true
	case VideoTypeDvd:
		return true
	case VideoTypeIso:
		return true
	case VideoTypeVideoFile:
		return true
	default:
		return false
	}
}

// AudioSpatialFormat An enum representing formats of spatial audio.
type AudioSpatialFormat string

// BaseItemDto This is strictly used as a data transfer object from the api layer.
// This holds information about a BaseItem in a format that is convenient for the client.
type BaseItemDto struct {
	// AirDays Gets or sets the air days.
	AirDays *[]DayOfWeek `json:"AirDays,omitempty"`

	// AirTime Gets or sets the air time.
	AirTime                 *string `json:"AirTime,omitempty"`
	AirsAfterSeasonNumber   *int32  `json:"AirsAfterSeasonNumber,omitempty"`
	AirsBeforeEpisodeNumber *int32  `json:"AirsBeforeEpisodeNumber,omitempty"`
	AirsBeforeSeasonNumber  *int32  `json:"AirsBeforeSeasonNumber,omitempty"`

	// Album Gets or sets the album.
	Album *string `json:"Album,omitempty"`

	// AlbumArtist Gets or sets the album artist.
	AlbumArtist *string `json:"AlbumArtist,omitempty"`

	// AlbumArtists Gets or sets the album artists.
	AlbumArtists *[]NameGuidPair `json:"AlbumArtists,omitempty"`

	// AlbumCount Gets or sets the album count.
	AlbumCount *int32 `json:"AlbumCount,omitempty"`

	// AlbumId Gets or sets the album id.
	AlbumId *openapi_types.UUID `json:"AlbumId,omitempty"`

	// AlbumNormalizationGain Gets or sets the gain required for audio normalization. This field is inherited from music album normalization gain.
	AlbumNormalizationGain *float32 `json:"AlbumNormalizationGain,omitempty"`

	// AlbumPrimaryImageTag Gets or sets the album image tag.
	AlbumPrimaryImageTag *string  `json:"AlbumPrimaryImageTag,omitempty"`
	Altitude             *float64 `json:"Altitude,omitempty"`
	Aperture             *float64 `json:"Aperture,omitempty"`
	ArtistCount          *int32   `json:"ArtistCount,omitempty"`

	// ArtistItems Gets or sets the artist items.
	ArtistItems *[]NameGuidPair `json:"ArtistItems,omitempty"`

	// Artists Gets or sets the artists.
	Artists *[]string `json:"Artists,omitempty"`

	// AspectRatio Gets or sets the aspect ratio.
	AspectRatio *string `json:"AspectRatio,omitempty"`

	// Audio Gets or sets the audio.
	Audio *ProgramAudio `json:"Audio,omitempty"`

	// BackdropImageTags Gets or sets the backdrop image tags.
	BackdropImageTags *[]string `json:"BackdropImageTags,omitempty"`
	CameraMake        *string   `json:"CameraMake,omitempty"`
	CameraModel       *string   `json:"CameraModel,omitempty"`
	CanDelete         *bool     `json:"CanDelete,omitempty"`
	CanDownload       *bool     `json:"CanDownload,omitempty"`

	// ChannelId Gets or sets the channel identifier.
	ChannelId     *openapi_types.UUID `json:"ChannelId,omitempty"`
	ChannelName   *string             `json:"ChannelName,omitempty"`
	ChannelNumber *string             `json:"ChannelNumber,omitempty"`

	// ChannelPrimaryImageTag Gets or sets the channel primary image tag.
	ChannelPrimaryImageTag *string `json:"ChannelPrimaryImageTag,omitempty"`

	// ChannelType Gets or sets the type of the channel.
	ChannelType *ChannelType `json:"ChannelType,omitempty"`

	// Chapters Gets or sets the chapters.
	Chapters *[]ChapterInfo `json:"Chapters,omitempty"`

	// ChildCount Gets or sets the child count.
	ChildCount *int32 `json:"ChildCount,omitempty"`

	// CollectionType Gets or sets the type of the collection.
	CollectionType *CollectionType `json:"CollectionType,omitempty"`

	// CommunityRating Gets or sets the community rating.
	CommunityRating *float32 `json:"CommunityRating,omitempty"`

	// CompletionPercentage Gets or sets the completion percentage.
	CompletionPercentage *float64 `json:"CompletionPercentage,omitempty"`
	Container            *string  `json:"Container,omitempty"`

	// CriticRating Gets or sets the critic rating.
	CriticRating *float32 `json:"CriticRating,omitempty"`

	// CumulativeRunTimeTicks Gets or sets the cumulative run time ticks.
	CumulativeRunTimeTicks *int64 `json:"CumulativeRunTimeTicks,omitempty"`

	// CurrentProgram Gets or sets the current program.
	CurrentProgram *BaseItemDto `json:"CurrentProgram,omitempty"`

	// CustomRating Gets or sets the custom rating.
	CustomRating *string `json:"CustomRating,omitempty"`

	// DateCreated Gets or sets the date created.
	DateCreated        *time.Time `json:"DateCreated,omitempty"`
	DateLastMediaAdded *time.Time `json:"DateLastMediaAdded,omitempty"`

	// DisplayOrder Gets or sets the display order.
	DisplayOrder *string `json:"DisplayOrder,omitempty"`

	// DisplayPreferencesId Gets or sets the display preferences id.
	DisplayPreferencesId     *string `json:"DisplayPreferencesId,omitempty"`
	EnableMediaSourceDisplay *bool   `json:"EnableMediaSourceDisplay,omitempty"`

	// EndDate Gets or sets the end date.
	EndDate *time.Time `json:"EndDate,omitempty"`

	// EpisodeCount Gets or sets the episode count.
	EpisodeCount *int32 `json:"EpisodeCount,omitempty"`

	// EpisodeTitle Gets or sets the episode title.
	EpisodeTitle *string `json:"EpisodeTitle,omitempty"`

	// Etag Gets or sets the etag.
	Etag         *string  `json:"Etag,omitempty"`
	ExposureTime *float64 `json:"ExposureTime,omitempty"`

	// ExternalUrls Gets or sets the external urls.
	ExternalUrls   *[]ExternalUrl  `json:"ExternalUrls,omitempty"`
	ExtraType      *ExtraType      `json:"ExtraType,omitempty"`
	FocalLength    *float64        `json:"FocalLength,omitempty"`
	ForcedSortName *string         `json:"ForcedSortName,omitempty"`
	GenreItems     *[]NameGuidPair `json:"GenreItems,omitempty"`

	// Genres Gets or sets the genres.
	Genres       *[]string `json:"Genres,omitempty"`
	HasLyrics    *bool     `json:"HasLyrics,omitempty"`
	HasSubtitles *bool     `json:"HasSubtitles,omitempty"`
	Height       *int32    `json:"Height,omitempty"`

	// Id Gets or sets the id.
	Id *openapi_types.UUID `json:"Id,omitempty"`

	// ImageBlurHashes Gets or sets the blurhashes for the image tags.
	// Maps image type to dictionary mapping image tag to blurhash value.
	ImageBlurHashes *struct {
		Art        *map[string]*string `json:"Art,omitempty"`
		Backdrop   *map[string]*string `json:"Backdrop,omitempty"`
		Banner     *map[string]*string `json:"Banner,omitempty"`
		Box        *map[string]*string `json:"Box,omitempty"`
		BoxRear    *map[string]*string `json:"BoxRear,omitempty"`
		Chapter    *map[string]*string `json:"Chapter,omitempty"`
		Disc       *map[string]*string `json:"Disc,omitempty"`
		Logo       *map[string]*string `json:"Logo,omitempty"`
		Menu       *map[string]*string `json:"Menu,omitempty"`
		Primary    *map[string]*string `json:"Primary,omitempty"`
		Profile    *map[string]*string `json:"Profile,omitempty"`
		Screenshot *map[string]*string `json:"Screenshot,omitempty"`
		Thumb      *map[string]*string `json:"Thumb,omitempty"`
	} `json:"ImageBlurHashes,omitempty"`
	ImageOrientation *ImageOrientation `json:"ImageOrientation,omitempty"`

	// ImageTags Gets or sets the image tags.
	ImageTags *map[string]*string `json:"ImageTags,omitempty"`

	// IndexNumber Gets or sets the index number.
	IndexNumber *int32 `json:"IndexNumber,omitempty"`

	// IndexNumberEnd Gets or sets the index number end.
	IndexNumberEnd *int32 `json:"IndexNumberEnd,omitempty"`

	// IsFolder Gets or sets a value indicating whether this instance is folder.
	IsFolder *bool `json:"IsFolder,omitempty"`

	// IsHD Gets or sets a value indicating whether this instance is HD.
	IsHD *bool `json:"IsHD,omitempty"`

	// IsKids Gets or sets a value indicating whether this instance is kids.
	IsKids *bool `json:"IsKids,omitempty"`

	// IsLive Gets or sets a value indicating whether this instance is live.
	IsLive *bool `json:"IsLive,omitempty"`

	// IsMovie Gets or sets a value indicating whether this instance is movie.
	IsMovie *bool `json:"IsMovie,omitempty"`

	// IsNews Gets or sets a value indicating whether this instance is news.
	IsNews *bool `json:"IsNews,omitempty"`

	// IsPlaceHolder Gets or sets a value indicating whether this instance is place holder.
	IsPlaceHolder *bool `json:"IsPlaceHolder,omitempty"`

	// IsPremiere Gets or sets a value indicating whether this instance is premiere.
	IsPremiere *bool `json:"IsPremiere,omitempty"`

	// IsRepeat Gets or sets a value indicating whether this instance is repeat.
	IsRepeat *bool `json:"IsRepeat,omitempty"`

	// IsSeries Gets or sets a value indicating whether this instance is series.
	IsSeries *bool `json:"IsSeries,omitempty"`

	// IsSports Gets or sets a value indicating whether this instance is sports.
	IsSports       *bool  `json:"IsSports,omitempty"`
	IsoSpeedRating *int32 `json:"IsoSpeedRating,omitempty"`

	// IsoType Gets or sets the type of the iso.
	IsoType  *IsoType `json:"IsoType,omitempty"`
	Latitude *float64 `json:"Latitude,omitempty"`

	// LocalTrailerCount Gets or sets the local trailer count.
	LocalTrailerCount *int32 `json:"LocalTrailerCount,omitempty"`

	// LocationType Gets or sets the type of the location.
	LocationType *LocationType `json:"LocationType,omitempty"`

	// LockData Gets or sets a value indicating whether [enable internet providers].
	LockData *bool `json:"LockData,omitempty"`

	// LockedFields Gets or sets the locked fields.
	LockedFields     *[]MetadataField `json:"LockedFields,omitempty"`
	Longitude        *float64         `json:"Longitude,omitempty"`
	MediaSourceCount *int32           `json:"MediaSourceCount,omitempty"`

	// MediaSources Gets or sets the media versions.
	MediaSources *[]MediaSourceInfo `json:"MediaSources,omitempty"`

	// MediaStreams Gets or sets the media streams.
	MediaStreams *[]MediaStream `json:"MediaStreams,omitempty"`

	// MediaType Media types.
	MediaType *MediaType `json:"MediaType,omitempty"`

	// MovieCount Gets or sets the movie count.
	MovieCount *int32 `json:"MovieCount,omitempty"`

	// MusicVideoCount Gets or sets the music video count.
	MusicVideoCount *int32 `json:"MusicVideoCount,omitempty"`

	// Name Gets or sets the name.
	Name *string `json:"Name,omitempty"`

	// NormalizationGain Gets or sets the gain required for audio normalization.
	NormalizationGain *float32 `json:"NormalizationGain,omitempty"`

	// Number Gets or sets the number.
	Number *string `json:"Number,omitempty"`

	// OfficialRating Gets or sets the official rating.
	OfficialRating   *string `json:"OfficialRating,omitempty"`
	OriginalLanguage *string `json:"OriginalLanguage,omitempty"`
	OriginalTitle    *string `json:"OriginalTitle,omitempty"`

	// Overview Gets or sets the overview.
	Overview *string `json:"Overview,omitempty"`

	// ParentArtImageTag Gets or sets the parent art image tag.
	ParentArtImageTag *string `json:"ParentArtImageTag,omitempty"`

	// ParentArtItemId Gets or sets whether the item has fan art, this will hold the Id of the Parent that has one.
	ParentArtItemId *openapi_types.UUID `json:"ParentArtItemId,omitempty"`

	// ParentBackdropImageTags Gets or sets the parent backdrop image tags.
	ParentBackdropImageTags *[]string `json:"ParentBackdropImageTags,omitempty"`

	// ParentBackdropItemId Gets or sets whether the item has any backdrops, this will hold the Id of the Parent that has one.
	ParentBackdropItemId *openapi_types.UUID `json:"ParentBackdropItemId,omitempty"`

	// ParentId Gets or sets the parent id.
	ParentId *openapi_types.UUID `json:"ParentId,omitempty"`

	// ParentIndexNumber Gets or sets the parent index number.
	ParentIndexNumber *int32 `json:"ParentIndexNumber,omitempty"`

	// ParentLogoImageTag Gets or sets the parent logo image tag.
	ParentLogoImageTag *string `json:"ParentLogoImageTag,omitempty"`

	// ParentLogoItemId Gets or sets whether the item has a logo, this will hold the Id of the Parent that has one.
	ParentLogoItemId *openapi_types.UUID `json:"ParentLogoItemId,omitempty"`

	// ParentPrimaryImageItemId Gets or sets the parent primary image item identifier.
	ParentPrimaryImageItemId *openapi_types.UUID `json:"ParentPrimaryImageItemId,omitempty"`

	// ParentPrimaryImageTag Gets or sets the parent primary image tag.
	ParentPrimaryImageTag *string `json:"ParentPrimaryImageTag,omitempty"`

	// ParentThumbImageTag Gets or sets the parent thumb image tag.
	ParentThumbImageTag *string `json:"ParentThumbImageTag,omitempty"`

	// ParentThumbItemId Gets or sets the parent thumb item id.
	ParentThumbItemId *openapi_types.UUID `json:"ParentThumbItemId,omitempty"`

	// PartCount Gets or sets the part count.
	PartCount *int32 `json:"PartCount,omitempty"`

	// Path Gets or sets the path.
	Path *string `json:"Path,omitempty"`

	// People Gets or sets the people.
	People *[]BaseItemPerson `json:"People,omitempty"`

	// PlayAccess Gets or sets the play access.
	PlayAccess *PlayAccess `json:"PlayAccess,omitempty"`

	// PlaylistItemId Gets or sets the playlist item identifier.
	PlaylistItemId               *string `json:"PlaylistItemId,omitempty"`
	PreferredMetadataCountryCode *string `json:"PreferredMetadataCountryCode,omitempty"`
	PreferredMetadataLanguage    *string `json:"PreferredMetadataLanguage,omitempty"`

	// PremiereDate Gets or sets the premiere date.
	PremiereDate *time.Time `json:"PremiereDate,omitempty"`

	// PrimaryImageAspectRatio Gets or sets the primary image aspect ratio, after image enhancements.
	PrimaryImageAspectRatio *float64  `json:"PrimaryImageAspectRatio,omitempty"`
	ProductionLocations     *[]string `json:"ProductionLocations,omitempty"`

	// ProductionYear Gets or sets the production year.
	ProductionYear *int32 `json:"ProductionYear,omitempty"`
	ProgramCount   *int32 `json:"ProgramCount,omitempty"`

	// ProgramId Gets or sets the program identifier.
	ProgramId *string `json:"ProgramId,omitempty"`

	// ProviderIds Gets or sets the provider ids.
	ProviderIds *map[string]*string `json:"ProviderIds,omitempty"`

	// RecursiveItemCount Gets or sets the recursive item count.
	RecursiveItemCount *int32 `json:"RecursiveItemCount,omitempty"`

	// RemoteTrailers Gets or sets the trailer urls.
	RemoteTrailers *[]MediaUrl `json:"RemoteTrailers,omitempty"`

	// RunTimeTicks Gets or sets the run time ticks.
	RunTimeTicks *int64 `json:"RunTimeTicks,omitempty"`

	// ScreenshotImageTags Gets or sets the screenshot image tags.
	ScreenshotImageTags *[]string `json:"ScreenshotImageTags,omitempty"`

	// SeasonId Gets or sets the season identifier.
	SeasonId *openapi_types.UUID `json:"SeasonId,omitempty"`

	// SeasonName Gets or sets the name of the season.
	SeasonName *string `json:"SeasonName,omitempty"`

	// SeriesCount Gets or sets the series count.
	SeriesCount *int32 `json:"SeriesCount,omitempty"`

	// SeriesId Gets or sets the series id.
	SeriesId *openapi_types.UUID `json:"SeriesId,omitempty"`

	// SeriesName Gets or sets the name of the series.
	SeriesName *string `json:"SeriesName,omitempty"`

	// SeriesPrimaryImageTag Gets or sets the series primary image tag.
	SeriesPrimaryImageTag *string `json:"SeriesPrimaryImageTag,omitempty"`

	// SeriesStudio Gets or sets the series studio.
	SeriesStudio *string `json:"SeriesStudio,omitempty"`

	// SeriesThumbImageTag Gets or sets the series thumb image tag.
	SeriesThumbImageTag *string `json:"SeriesThumbImageTag,omitempty"`

	// SeriesTimerId Gets or sets the series timer identifier.
	SeriesTimerId *string `json:"SeriesTimerId,omitempty"`

	// ServerId Gets or sets the server identifier.
	ServerId     *string  `json:"ServerId,omitempty"`
	ShutterSpeed *float64 `json:"ShutterSpeed,omitempty"`
	Software     *string  `json:"Software,omitempty"`

	// SongCount Gets or sets the song count.
	SongCount *int32 `json:"SongCount,omitempty"`

	// SortName Gets or sets the name of the sort.
	SortName *string `json:"SortName,omitempty"`

	// SourceType Gets or sets the type of the source.
	SourceType *string `json:"SourceType,omitempty"`

	// SpecialFeatureCount Gets or sets the special feature count.
	SpecialFeatureCount *int32 `json:"SpecialFeatureCount,omitempty"`

	// StartDate Gets or sets the start date of the recording, in UTC.
	StartDate *time.Time `json:"StartDate,omitempty"`

	// Status Gets or sets the status.
	Status *string `json:"Status,omitempty"`

	// Studios Gets or sets the studios.
	Studios *[]NameGuidPair `json:"Studios,omitempty"`

	// Taglines Gets or sets the taglines.
	Taglines *[]string `json:"Taglines,omitempty"`

	// Tags Gets or sets the tags.
	Tags *[]string `json:"Tags,omitempty"`

	// TimerId Gets or sets the timer identifier.
	TimerId *string `json:"TimerId,omitempty"`

	// TrailerCount Gets or sets the trailer count.
	TrailerCount *int32 `json:"TrailerCount,omitempty"`

	// Trickplay Gets or sets the trickplay manifest.
	Trickplay *map[string]*map[string]TrickplayInfoDto `json:"Trickplay,omitempty"`

	// Type The base item kind.
	Type *BaseItemKind `json:"Type,omitempty"`

	// UserData Gets or sets the user data for this item based on the user it's being requested for.
	UserData *UserItemDataDto `json:"UserData,omitempty"`

	// Video3DFormat Gets or sets the video3 D format.
	Video3DFormat *Video3DFormat `json:"Video3DFormat,omitempty"`

	// VideoType Gets or sets the type of the video.
	VideoType *VideoType `json:"VideoType,omitempty"`
	Width     *int32     `json:"Width,omitempty"`
}

// BaseItemKind The base item kind.
type BaseItemKind string

// BaseItemPerson This is used by the api to get information about a Person within a BaseItem.
type BaseItemPerson struct {
	// Id Gets or sets the identifier.
	Id *openapi_types.UUID `json:"Id,omitempty"`

	// ImageBlurHashes Gets or sets the primary image blurhash.
	ImageBlurHashes *struct {
		Art        *map[string]*string `json:"Art,omitempty"`
		Backdrop   *map[string]*string `json:"Backdrop,omitempty"`
		Banner     *map[string]*string `json:"Banner,omitempty"`
		Box        *map[string]*string `json:"Box,omitempty"`
		BoxRear    *map[string]*string `json:"BoxRear,omitempty"`
		Chapter    *map[string]*string `json:"Chapter,omitempty"`
		Disc       *map[string]*string `json:"Disc,omitempty"`
		Logo       *map[string]*string `json:"Logo,omitempty"`
		Menu       *map[string]*string `json:"Menu,omitempty"`
		Primary    *map[string]*string `json:"Primary,omitempty"`
		Profile    *map[string]*string `json:"Profile,omitempty"`
		Screenshot *map[string]*string `json:"Screenshot,omitempty"`
		Thumb      *map[string]*string `json:"Thumb,omitempty"`
	} `json:"ImageBlurHashes,omitempty"`

	// Name Gets or sets the name.
	Name *string `json:"Name,omitempty"`

	// PrimaryImageTag Gets or sets the primary image tag.
	PrimaryImageTag *string `json:"PrimaryImageTag,omitempty"`

	// Role Gets or sets the role.
	Role *string `json:"Role,omitempty"`

	// Type The person kind.
	Type *PersonKind `json:"Type,omitempty"`
}

// CastReceiverApplication The cast receiver application model.
type CastReceiverApplication struct {
	// Id Gets or sets the cast receiver application id.
	Id string `json:"Id"`

	// Name Gets or sets the cast receiver application name.
	Name string `json:"Name"`
}

// ChannelType Enum ChannelType.
type ChannelType string

// ChapterInfo Class ChapterInfo.
type ChapterInfo struct {
	ImageDateModified *time.Time `json:"ImageDateModified,omitempty"`

	// ImagePath Gets or sets the image path.
	ImagePath *string `json:"ImagePath,omitempty"`
	ImageTag  *string `json:"ImageTag,omitempty"`

	// Name Gets or sets the name.
	Name *string `json:"Name,omitempty"`

	// StartPositionTicks Gets or sets the start position ticks.
	StartPositionTicks *int64 `json:"StartPositionTicks,omitempty"`
}

// CollectionType Collection type.
type CollectionType string

// CollectionTypeOptions The collection type options.
type CollectionTypeOptions string

// DayOfWeek defines model for DayOfWeek.
type DayOfWeek string

// EmbeddedSubtitleOptions An enum representing the options to disable embedded subs.
type EmbeddedSubtitleOptions string

// ExternalUrl defines model for ExternalUrl.
type ExternalUrl struct {
	// Name Gets or sets the name.
	Name *string `json:"Name,omitempty"`

	// Url Gets or sets the type of the item.
	Url *string `json:"Url,omitempty"`
}

// ExtraType defines model for ExtraType.
type ExtraType string

// ImageOption defines model for ImageOption.
type ImageOption struct {
	// Limit Gets or sets the limit.
	Limit *int32 `json:"Limit,omitempty"`

	// MinWidth Gets or sets the minimum width.
	MinWidth *int32 `json:"MinWidth,omitempty"`

	// Type Gets or sets the type.
	Type *ImageType `json:"Type,omitempty"`
}

// ImageOrientation defines model for ImageOrientation.
type ImageOrientation string

// ImageType Enum ImageType.
type ImageType string

// InstallationInfo Class InstallationInfo.
type InstallationInfo struct {
	// Changelog Gets or sets the changelog for this version.
	Changelog *string `json:"Changelog,omitempty"`

	// Checksum Gets or sets a checksum for the binary.
	Checksum *string `json:"Checksum,omitempty"`

	// Guid Gets or sets the Id.
	Guid *openapi_types.UUID `json:"Guid,omitempty"`

	// Name Gets or sets the name.
	Name *string `json:"Name,omitempty"`

	// PackageInfo Gets or sets package information for the installation.
	PackageInfo *PackageInfo `json:"PackageInfo,omitempty"`

	// SourceUrl Gets or sets the source URL.
	SourceUrl *string `json:"SourceUrl,omitempty"`

	// Version Gets or sets the version.
	Version *string `json:"Version,omitempty"`
}

// IsoType Enum IsoType.
type IsoType string

// LibraryOptions defines model for LibraryOptions.
type LibraryOptions struct {
	// AllowEmbeddedSubtitles An enum representing the options to disable embedded subs.
	AllowEmbeddedSubtitles        *EmbeddedSubtitleOptions `json:"AllowEmbeddedSubtitles,omitempty"`
	AutomaticRefreshIntervalDays  *int32                   `json:"AutomaticRefreshIntervalDays,omitempty"`
	AutomaticallyAddToCollection  *bool                    `json:"AutomaticallyAddToCollection,omitempty"`
	CustomTagDelimiters           *[]string                `json:"CustomTagDelimiters,omitempty"`
	DelimiterWhitelist            *[]string                `json:"DelimiterWhitelist,omitempty"`
	DisabledLocalMetadataReaders  *[]string                `json:"DisabledLocalMetadataReaders,omitempty"`
	DisabledLyricFetchers         *[]string                `json:"DisabledLyricFetchers,omitempty"`
	DisabledMediaSegmentProviders *[]string                `json:"DisabledMediaSegmentProviders,omitempty"`
	DisabledSubtitleFetchers      *[]string                `json:"DisabledSubtitleFetchers,omitempty"`
	EnableAutomaticSeriesGrouping *bool                    `json:"EnableAutomaticSeriesGrouping,omitempty"`
	EnableChapterImageExtraction  *bool                    `json:"EnableChapterImageExtraction,omitempty"`
	EnableEmbeddedEpisodeInfos    *bool                    `json:"EnableEmbeddedEpisodeInfos,omitempty"`
	EnableEmbeddedExtrasTitles    *bool                    `json:"EnableEmbeddedExtrasTitles,omitempty"`
	EnableEmbeddedTitles          *bool                    `json:"EnableEmbeddedTitles,omitempty"`
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	EnableInternetProviders                 *bool     `json:"EnableInternetProviders,omitempty"`
	EnableLUFSScan                          *bool     `json:"EnableLUFSScan,omitempty"`
	EnablePhotos                            *bool     `json:"EnablePhotos,omitempty"`
	EnableRealtimeMonitor                   *bool     `json:"EnableRealtimeMonitor,omitempty"`
	EnableTrickplayImageExtraction          *bool     `json:"EnableTrickplayImageExtraction,omitempty"`
	Enabled                                 *bool     `json:"Enabled,omitempty"`
	ExtractChapterImagesDuringLibraryScan   *bool     `json:"ExtractChapterImagesDuringLibraryScan,omitempty"`
	ExtractTrickplayImagesDuringLibraryScan *bool     `json:"ExtractTrickplayImagesDuringLibraryScan,omitempty"`
	LocalMetadataReaderOrder                *[]string `json:"LocalMetadataReaderOrder,omitempty"`
	LyricFetcherOrder                       *[]string `json:"LyricFetcherOrder,omitempty"`
	MediaSegmentProviderOrder               *[]string `json:"MediaSegmentProviderOrder,omitempty"`

	// MetadataCountryCode Gets or sets the metadata country code.
	MetadataCountryCode         *string          `json:"MetadataCountryCode,omitempty"`
	MetadataSavers              *[]string        `json:"MetadataSavers,omitempty"`
	PathInfos                   *[]MediaPathInfo `json:"PathInfos,omitempty"`
	PreferNonstandardArtistsTag *bool            `json:"PreferNonstandardArtistsTag,omitempty"`

	// PreferredMetadataLanguage Gets or sets the preferred metadata language.
	PreferredMetadataLanguage               *string        `json:"PreferredMetadataLanguage,omitempty"`
	RequirePerfectSubtitleMatch             *bool          `json:"RequirePerfectSubtitleMatch,omitempty"`
	SaveLocalMetadata                       *bool          `json:"SaveLocalMetadata,omitempty"`
	SaveLyricsWithMedia                     *bool          `json:"SaveLyricsWithMedia,omitempty"`
	SaveSubtitlesWithMedia                  *bool          `json:"SaveSubtitlesWithMedia,omitempty"`
	SaveTrickplayWithMedia                  *bool          `json:"SaveTrickplayWithMedia,omitempty"`
	SeasonZeroDisplayName                   *string        `json:"SeasonZeroDisplayName,omitempty"`
	SkipSubtitlesIfAudioTrackMatches        *bool          `json:"SkipSubtitlesIfAudioTrackMatches,omitempty"`
	SkipSubtitlesIfEmbeddedSubtitlesPresent *bool          `json:"SkipSubtitlesIfEmbeddedSubtitlesPresent,omitempty"`
	SubtitleDownloadLanguages               *[]string      `json:"SubtitleDownloadLanguages,omitempty"`
	SubtitleFetcherOrder                    *[]string      `json:"SubtitleFetcherOrder,omitempty"`
	TypeOptions                             *[]TypeOptions `json:"TypeOptions,omitempty"`
	UseCustomTagDelimiters                  *bool          `json:"UseCustomTagDelimiters,omitempty"`
}

// LocationType Enum LocationType.
type LocationType string

// MediaAttachment Class MediaAttachment.
type MediaAttachment struct {
	// Codec Gets or sets the codec.
	Codec *string `json:"Codec,omitempty"`

	// CodecTag Gets or sets the codec tag.
	CodecTag *string `json:"CodecTag,omitempty"`

	// Comment Gets or sets the comment.
	Comment *string `json:"Comment,omitempty"`

	// DeliveryUrl Gets or sets the delivery URL.
	DeliveryUrl *string `json:"DeliveryUrl,omitempty"`

	// FileName Gets or sets the filename.
	FileName *string `json:"FileName,omitempty"`

	// Index Gets or sets the index.
	Index *int32 `json:"Index,omitempty"`

	// MimeType Gets or sets the MIME type.
	MimeType *string `json:"MimeType,omitempty"`
}

// MediaPathInfo defines model for MediaPathInfo.
type MediaPathInfo struct {
	Path *string `json:"Path,omitempty"`
}

// MediaProtocol defines model for MediaProtocol.
type MediaProtocol string

// MediaSourceInfo defines model for MediaSourceInfo.
type MediaSourceInfo struct {
	AnalyzeDurationMs           *int32         `json:"AnalyzeDurationMs,omitempty"`
	Bitrate                     *int32         `json:"Bitrate,omitempty"`
	BufferMs                    *int32         `json:"BufferMs,omitempty"`
	Container                   *string        `json:"Container,omitempty"`
	DefaultAudioStreamIndex     *int32         `json:"DefaultAudioStreamIndex,omitempty"`
	DefaultSubtitleStreamIndex  *int32         `json:"DefaultSubtitleStreamIndex,omitempty"`
	ETag                        *string        `json:"ETag,omitempty"`
	EncoderPath                 *string        `json:"EncoderPath,omitempty"`
	EncoderProtocol             *MediaProtocol `json:"EncoderProtocol,omitempty"`
	FallbackMaxStreamingBitrate *int32         `json:"FallbackMaxStreamingBitrate,omitempty"`
	Formats                     *[]string      `json:"Formats,omitempty"`
	GenPtsInput                 *bool          `json:"GenPtsInput,omitempty"`
	HasSegments                 *bool          `json:"HasSegments,omitempty"`
	Id                          *string        `json:"Id,omitempty"`
	IgnoreDts                   *bool          `json:"IgnoreDts,omitempty"`
	IgnoreIndex                 *bool          `json:"IgnoreIndex,omitempty"`
	IsInfiniteStream            *bool          `json:"IsInfiniteStream,omitempty"`

	// IsRemote Gets or sets a value indicating whether the media is remote.
	// Differentiate internet url vs local network.
	IsRemote              *bool                     `json:"IsRemote,omitempty"`
	IsoType               *IsoType                  `json:"IsoType,omitempty"`
	LiveStreamId          *string                   `json:"LiveStreamId,omitempty"`
	MediaAttachments      *[]MediaAttachment        `json:"MediaAttachments,omitempty"`
	MediaStreams          *[]MediaStream            `json:"MediaStreams,omitempty"`
	Name                  *string                   `json:"Name,omitempty"`
	OpenToken             *string                   `json:"OpenToken,omitempty"`
	Path                  *string                   `json:"Path,omitempty"`
	Protocol              *MediaProtocol            `json:"Protocol,omitempty"`
	ReadAtNativeFramerate *bool                     `json:"ReadAtNativeFramerate,omitempty"`
	RequiredHttpHeaders   *map[string]*string       `json:"RequiredHttpHeaders,omitempty"`
	RequiresClosing       *bool                     `json:"RequiresClosing,omitempty"`
	RequiresLooping       *bool                     `json:"RequiresLooping,omitempty"`
	RequiresOpening       *bool                     `json:"RequiresOpening,omitempty"`
	RunTimeTicks          *int64                    `json:"RunTimeTicks,omitempty"`
	Size                  *int64                    `json:"Size,omitempty"`
	SupportsDirectPlay    *bool                     `json:"SupportsDirectPlay,omitempty"`
	SupportsDirectStream  *bool                     `json:"SupportsDirectStream,omitempty"`
	SupportsProbing       *bool                     `json:"SupportsProbing,omitempty"`
	SupportsTranscoding   *bool                     `json:"SupportsTranscoding,omitempty"`
	Timestamp             *TransportStreamTimestamp `json:"Timestamp,omitempty"`
	TranscodingContainer  *string                   `json:"TranscodingContainer,omitempty"`

	// TranscodingSubProtocol Media streaming protocol.
	// Lowercase for backwards compatibility.
	TranscodingSubProtocol *MediaStreamProtocol `json:"TranscodingSubProtocol,omitempty"`
	TranscodingUrl         *string              `json:"TranscodingUrl,omitempty"`

	// Type The type of a media source.
	Type                                *MediaSourceType `json:"Type,omitempty"`
	UseMostCompatibleTranscodingProfile *bool            `json:"UseMostCompatibleTranscodingProfile,omitempty"`
	Video3DFormat                       *Video3DFormat   `json:"Video3DFormat,omitempty"`
	VideoType                           *VideoType       `json:"VideoType,omitempty"`
}

// MediaSourceType The type of a media source.
type MediaSourceType string

// MediaStream Class MediaStream.
type MediaStream struct {
	// AspectRatio Gets or sets the aspect ratio.
	AspectRatio *string `json:"AspectRatio,omitempty"`

	// AudioSpatialFormat An enum representing formats of spatial audio.
	AudioSpatialFormat *AudioSpatialFormat `json:"AudioSpatialFormat,omitempty"`

	// AverageFrameRate Gets or sets the average frame rate.
	AverageFrameRate *float32 `json:"AverageFrameRate,omitempty"`

	// BitDepth Gets or sets the bit depth.
	BitDepth *int32 `json:"BitDepth,omitempty"`

	// BitRate Gets or sets the bit rate.
	BitRate *int32 `json:"BitRate,omitempty"`

	// BlPresentFlag Gets or sets the Dolby Vision bl present flag.
	BlPresentFlag *int32 `json:"BlPresentFlag,omitempty"`

	// ChannelLayout Gets or sets the channel layout.
	ChannelLayout *string `json:"ChannelLayout,omitempty"`

	// Channels Gets or sets the channels.
	Channels *int32 `json:"Channels,omitempty"`

	// Codec Gets or sets the codec.
	Codec *string `json:"Codec,omitempty"`

	// CodecTag Gets or sets the codec tag.
	CodecTag *string `json:"CodecTag,omitempty"`

	// CodecTimeBase Gets or sets the codec time base.
	CodecTimeBase *string `json:"CodecTimeBase,omitempty"`

	// ColorPrimaries Gets or sets the color primaries.
	ColorPrimaries *string `json:"ColorPrimaries,omitempty"`

	// ColorRange Gets or sets the color range.
	ColorRange *string `json:"ColorRange,omitempty"`

	// ColorSpace Gets or sets the color space.
	ColorSpace *string `json:"ColorSpace,omitempty"`

	// ColorTransfer Gets or sets the color transfer.
	ColorTransfer *string `json:"ColorTransfer,omitempty"`

	// Comment Gets or sets the comment.
	Comment *string `json:"Comment,omitempty"`

	// DeliveryMethod Gets or sets the method.
	DeliveryMethod *SubtitleDeliveryMethod `json:"DeliveryMethod,omitempty"`

	// DeliveryUrl Gets or sets the delivery URL.
	DeliveryUrl  *string `json:"DeliveryUrl,omitempty"`
	DisplayTitle *string `json:"DisplayTitle,omitempty"`

	// DvBlSignalCompatibilityId Gets or sets the Dolby Vision bl signal compatibility id.
	DvBlSignalCompatibilityId *int32 `json:"DvBlSignalCompatibilityId,omitempty"`

	// DvLevel Gets or sets the Dolby Vision level.
	DvLevel *int32 `json:"DvLevel,omitempty"`

	// DvProfile Gets or sets the Dolby Vision profile.
	DvProfile *int32 `json:"DvProfile,omitempty"`

	// DvVersionMajor Gets or sets the Dolby Vision version major.
	DvVersionMajor *int32 `json:"DvVersionMajor,omitempty"`

	// DvVersionMinor Gets or sets the Dolby Vision version minor.
	DvVersionMinor *int32 `json:"DvVersionMinor,omitempty"`

	// ElPresentFlag Gets or sets the Dolby Vision el present flag.
	ElPresentFlag        *int32 `json:"ElPresentFlag,omitempty"`
	Hdr10PlusPresentFlag *bool  `json:"Hdr10PlusPresentFlag,omitempty"`

	// Height Gets or sets the height.
	Height *int32 `json:"Height,omitempty"`

	// Index Gets or sets the index.
	Index *int32 `json:"Index,omitempty"`
	IsAVC *bool  `json:"IsAVC,omitempty"`

	// IsAnamorphic Gets or sets whether this instance is anamorphic.
	IsAnamorphic *bool `json:"IsAnamorphic,omitempty"`

	// IsDefault Gets or sets a value indicating whether this instance is default.
	IsDefault *bool `json:"IsDefault,omitempty"`

	// IsExternal Gets or sets a value indicating whether this instance is external.
	IsExternal *bool `json:"IsExternal,omitempty"`

	// IsExternalUrl Gets or sets a value indicating whether this instance is external URL.
	IsExternalUrl *bool `json:"IsExternalUrl,omitempty"`

	// IsForced Gets or sets a value indicating whether this instance is forced.
	IsForced *bool `json:"IsForced,omitempty"`

	// IsHearingImpaired Gets or sets a value indicating whether this instance is for the hearing impaired.
	IsHearingImpaired *bool `json:"IsHearingImpaired,omitempty"`

	// IsInterlaced Gets or sets a value indicating whether this instance is interlaced.
	IsInterlaced *bool `json:"IsInterlaced,omitempty"`

	// IsOriginal Gets or sets a value indicating whether this instance is original.
	IsOriginal           *bool `json:"IsOriginal,omitempty"`
	IsTextSubtitleStream *bool `json:"IsTextSubtitleStream,omitempty"`

	// Language Gets or sets the language.
	Language *string `json:"Language,omitempty"`

	// Level Gets or sets the level.
	Level                    *float64 `json:"Level,omitempty"`
	LocalizedDefault         *string  `json:"LocalizedDefault,omitempty"`
	LocalizedExternal        *string  `json:"LocalizedExternal,omitempty"`
	LocalizedForced          *string  `json:"LocalizedForced,omitempty"`
	LocalizedHearingImpaired *string  `json:"LocalizedHearingImpaired,omitempty"`
	LocalizedLanguage        *string  `json:"LocalizedLanguage,omitempty"`
	LocalizedOriginal        *string  `json:"LocalizedOriginal,omitempty"`
	LocalizedUndefined       *string  `json:"LocalizedUndefined,omitempty"`
	NalLengthSize            *string  `json:"NalLengthSize,omitempty"`

	// PacketLength Gets or sets the length of the packet.
	PacketLength *int32 `json:"PacketLength,omitempty"`

	// Path Gets or sets the filename.
	Path *string `json:"Path,omitempty"`

	// PixelFormat Gets or sets the pixel format.
	PixelFormat *string `json:"PixelFormat,omitempty"`

	// Profile Gets or sets the profile.
	Profile *string `json:"Profile,omitempty"`

	// RealFrameRate Gets or sets the real frame rate.
	RealFrameRate *float32 `json:"RealFrameRate,omitempty"`

	// RefFrames Gets or sets the reference frames.
	RefFrames *int32 `json:"RefFrames,omitempty"`

	// ReferenceFrameRate Gets the framerate used as reference.
	// Prefer AverageFrameRate, if that is null or an unrealistic value
	// then fallback to RealFrameRate.
	ReferenceFrameRate *float32 `json:"ReferenceFrameRate,omitempty"`

	// Rotation Gets or sets the Rotation in degrees.
	Rotation *int32 `json:"Rotation,omitempty"`

	// RpuPresentFlag Gets or sets the Dolby Vision rpu present flag.
	RpuPresentFlag *int32 `json:"RpuPresentFlag,omitempty"`

	// SampleRate Gets or sets the sample rate.
	SampleRate *int32 `json:"SampleRate,omitempty"`

	// Score Gets or sets the score.
	Score *int32 `json:"Score,omitempty"`

	// SupportsExternalStream Gets or sets a value indicating whether [supports external stream].
	SupportsExternalStream *bool `json:"SupportsExternalStream,omitempty"`

	// TimeBase Gets or sets the time base.
	TimeBase *string `json:"TimeBase,omitempty"`

	// Title Gets or sets the title.
	Title *string `json:"Title,omitempty"`

	// Type Gets or sets the type.
	Type *MediaStreamType `json:"Type,omitempty"`

	// VideoDoViTitle Gets the video dovi title.
	VideoDoViTitle *string `json:"VideoDoViTitle,omitempty"`

	// VideoRange An enum representing video ranges.
	VideoRange *VideoRange `json:"VideoRange,omitempty"`

	// VideoRangeType An enum representing types of video ranges.
	VideoRangeType *VideoRangeType `json:"VideoRangeType,omitempty"`

	// Width Gets or sets the width.
	Width *int32 `json:"Width,omitempty"`
}

// MediaStreamProtocol Media streaming protocol.
// Lowercase for backwards compatibility.
type MediaStreamProtocol string

// MediaStreamType Enum MediaStreamType.
type MediaStreamType string

// MediaType Media types.
type MediaType string

// MediaUrl defines model for MediaUrl.
type MediaUrl struct {
	Name *string `json:"Name,omitempty"`
	Url  *string `json:"Url,omitempty"`
}

// MetadataField Enum MetadataFields.
type MetadataField string

// NameGuidPair defines model for NameGuidPair.
type NameGuidPair struct {
	Id   *openapi_types.UUID `json:"Id,omitempty"`
	Name *string             `json:"Name,omitempty"`
}

// PackageInfo Class PackageInfo.
type PackageInfo struct {
	// Category Gets or sets the category.
	Category *string `json:"category,omitempty"`

	// Description Gets or sets a long description of the plugin containing features or helpful explanations.
	Description *string `json:"description,omitempty"`

	// Guid Gets or sets the guid of the assembly associated with this plugin.
	// This is used to identify the proper item for automatic updates.
	Guid *openapi_types.UUID `json:"guid,omitempty"`

	// ImageUrl Gets or sets the image url for the package.
	ImageUrl *string `json:"imageUrl,omitempty"`

	// Name Gets or sets the name.
	Name *string `json:"name,omitempty"`

	// Overview Gets or sets a short overview of what the plugin does.
	Overview *string `json:"overview,omitempty"`

	// Owner Gets or sets the owner.
	Owner *string `json:"owner,omitempty"`

	// Versions Gets or sets the versions.
	Versions *[]VersionInfo `json:"versions,omitempty"`
}

// PersonKind The person kind.
type PersonKind string

// PlayAccess The play access of an item.
type PlayAccess string

// ProblemDetails defines model for ProblemDetails.
type ProblemDetails struct {
	Detail               *string                `json:"detail,omitempty"`
	Instance             *string                `json:"instance,omitempty"`
	Status               *int32                 `json:"status,omitempty"`
	Title                *string                `json:"title,omitempty"`
	Type                 *string                `json:"type,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ProgramAudio defines model for ProgramAudio.
type ProgramAudio string

// RemoteSearchResult defines model for RemoteSearchResult.
type RemoteSearchResult struct {
	AlbumArtist    *RemoteSearchResult   `json:"AlbumArtist,omitempty"`
	Artists        *[]RemoteSearchResult `json:"Artists,omitempty"`
	ImageUrl       *string               `json:"ImageUrl,omitempty"`
	IndexNumber    *int32                `json:"IndexNumber,omitempty"`
	IndexNumberEnd *int32                `json:"IndexNumberEnd,omitempty"`

	// Name Gets or sets the name.
	Name              *string    `json:"Name,omitempty"`
	Overview          *string    `json:"Overview,omitempty"`
	ParentIndexNumber *int32     `json:"ParentIndexNumber,omitempty"`
	PremiereDate      *time.Time `json:"PremiereDate,omitempty"`

	// ProductionYear Gets or sets the year.
	ProductionYear *int32 `json:"ProductionYear,omitempty"`

	// ProviderIds Gets or sets the provider ids.
	ProviderIds        *map[string]string `json:"ProviderIds,omitempty"`
	SearchProviderName *string            `json:"SearchProviderName,omitempty"`
}

// SubtitleDeliveryMethod Delivery method to use during playback of a specific subtitle format.
type SubtitleDeliveryMethod string

// SystemInfo Class SystemInfo.
type SystemInfo struct {
	// CachePath Gets or sets the cache path.
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	CachePath *string `json:"CachePath,omitempty"`
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	CanLaunchWebBrowser *bool `json:"CanLaunchWebBrowser,omitempty"`

	// CanSelfRestart Gets or sets a value indicating whether this instance can self restart.
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	CanSelfRestart *bool `json:"CanSelfRestart,omitempty"`

	// CastReceiverApplications Gets or sets the list of cast receiver applications.
	CastReceiverApplications *[]CastReceiverApplication `json:"CastReceiverApplications,omitempty"`

	// CompletedInstallations Gets or sets the completed installations.
	CompletedInstallations *[]InstallationInfo `json:"CompletedInstallations,omitempty"`
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	EncoderLocation *string `json:"EncoderLocation,omitempty"`

	// HasPendingRestart Gets or sets a value indicating whether this instance has pending restart.
	HasPendingRestart *bool `json:"HasPendingRestart,omitempty"`

	// HasUpdateAvailable Gets or sets a value indicating whether this instance has update available.
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	HasUpdateAvailable *bool `json:"HasUpdateAvailable,omitempty"`

	// Id Gets or sets the id.
	Id *string `json:"Id,omitempty"`

	// InternalMetadataPath Gets or sets the internal metadata path.
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	InternalMetadataPath *string `json:"InternalMetadataPath,omitempty"`
	IsShuttingDown       *bool   `json:"IsShuttingDown,omitempty"`

	// ItemsByNamePath Gets or sets the items by name path.
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	ItemsByNamePath *string `json:"ItemsByNamePath,omitempty"`

	// LocalAddress Gets or sets the local address.
	LocalAddress *string `json:"LocalAddress,omitempty"`

	// LogPath Gets or sets the log path.
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	LogPath *string `json:"LogPath,omitempty"`

	// OperatingSystem Gets or sets the operating system.
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	OperatingSystem *string `json:"OperatingSystem,omitempty"`

	// OperatingSystemDisplayName Gets or sets the display name of the operating system.
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	OperatingSystemDisplayName *string `json:"OperatingSystemDisplayName,omitempty"`

	// PackageName Gets or sets the package name.
	PackageName *string `json:"PackageName,omitempty"`

	// ProductName Gets or sets the product name. This is the AssemblyProduct name.
	ProductName *string `json:"ProductName,omitempty"`

	// ProgramDataPath Gets or sets the program data path.
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	ProgramDataPath *string `json:"ProgramDataPath,omitempty"`

	// ServerName Gets or sets the name of the server.
	ServerName *string `json:"ServerName,omitempty"`

	// StartupWizardCompleted Gets or sets a value indicating whether the startup wizard is completed.
	StartupWizardCompleted *bool `json:"StartupWizardCompleted,omitempty"`

	// SupportsLibraryMonitor Gets or sets a value indicating whether [supports library monitor].
	SupportsLibraryMonitor *bool `json:"SupportsLibraryMonitor,omitempty"`
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	SystemArchitecture *string `json:"SystemArchitecture,omitempty"`

	// TranscodingTempPath Gets or sets the transcode path.
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	TranscodingTempPath *string `json:"TranscodingTempPath,omitempty"`

	// Version Gets or sets the server version.
	Version *string `json:"Version,omitempty"`

	// WebPath Gets or sets the web UI resources path.
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	WebPath *string `json:"WebPath,omitempty"`

	// WebSocketPortNumber Gets or sets the web socket port number.
	WebSocketPortNumber *int32 `json:"WebSocketPortNumber,omitempty"`
}

// TransportStreamTimestamp The type of timestamps used in a transport stream.
type TransportStreamTimestamp string

// TrickplayInfoDto The trickplay api model.
type TrickplayInfoDto struct {
	// Bandwidth Gets the peak bandwidth usage in bits per second.
	Bandwidth *int32 `json:"Bandwidth,omitempty"`

	// Height Gets the height of an individual thumbnail.
	Height *int32 `json:"Height,omitempty"`

	// Interval Gets the interval in milliseconds between each trickplay thumbnail.
	Interval *int32 `json:"Interval,omitempty"`

	// ThumbnailCount Gets the total amount of non-black thumbnails.
	ThumbnailCount *int32 `json:"ThumbnailCount,omitempty"`

	// TileHeight Gets the amount of thumbnails per column.
	TileHeight *int32 `json:"TileHeight,omitempty"`

	// TileWidth Gets the amount of thumbnails per row.
	TileWidth *int32 `json:"TileWidth,omitempty"`

	// Width Gets the width of an individual thumbnail.
	Width *int32 `json:"Width,omitempty"`
}

// TypeOptions defines model for TypeOptions.
type TypeOptions struct {
	ImageFetcherOrder        *[]string      `json:"ImageFetcherOrder,omitempty"`
	ImageFetchers            *[]string      `json:"ImageFetchers,omitempty"`
	ImageOptions             *[]ImageOption `json:"ImageOptions,omitempty"`
	MetadataFetcherOrder     *[]string      `json:"MetadataFetcherOrder,omitempty"`
	MetadataFetchers         *[]string      `json:"MetadataFetchers,omitempty"`
	SimilarItemProviderOrder *[]string      `json:"SimilarItemProviderOrder,omitempty"`
	SimilarItemProviders     *[]string      `json:"SimilarItemProviders,omitempty"`
	Type                     *string        `json:"Type,omitempty"`
}

// UserItemDataDto Class UserItemDataDto.
type UserItemDataDto struct {
	// IsFavorite Gets or sets a value indicating whether this instance is favorite.
	IsFavorite *bool `json:"IsFavorite,omitempty"`

	// ItemId Gets or sets the item identifier.
	ItemId *openapi_types.UUID `json:"ItemId,omitempty"`

	// Key Gets or sets the key.
	Key string `json:"Key"`

	// LastPlayedDate Gets or sets the last played date.
	LastPlayedDate *time.Time `json:"LastPlayedDate,omitempty"`

	// Likes Gets or sets a value indicating whether this MediaBrowser.Model.Dto.UserItemDataDto is likes.
	Likes *bool `json:"Likes,omitempty"`

	// PlayCount Gets or sets the play count.
	PlayCount *int32 `json:"PlayCount,omitempty"`

	// PlaybackPositionTicks Gets or sets the playback position ticks.
	PlaybackPositionTicks *int64 `json:"PlaybackPositionTicks,omitempty"`

	// Played Gets or sets a value indicating whether this MediaBrowser.Model.Dto.UserItemDataDto is played.
	Played *bool `json:"Played,omitempty"`

	// PlayedPercentage Gets or sets the played percentage.
	PlayedPercentage *float64 `json:"PlayedPercentage,omitempty"`

	// Rating Gets or sets the rating.
	Rating *float64 `json:"Rating,omitempty"`

	// UnplayedItemCount Gets or sets the unplayed item count.
	UnplayedItemCount *int32 `json:"UnplayedItemCount,omitempty"`
}

// VersionInfo Defines the MediaBrowser.Model.Updates.VersionInfo class.
type VersionInfo struct {
	// VersionNumber Gets the version as a System.Version.
	VersionNumber *string `json:"VersionNumber,omitempty"`

	// Changelog Gets or sets the changelog for this version.
	Changelog *string `json:"changelog,omitempty"`

	// Checksum Gets or sets a checksum for the binary.
	Checksum *string `json:"checksum,omitempty"`

	// RepositoryName Gets or sets the repository name.
	RepositoryName *string `json:"repositoryName,omitempty"`

	// RepositoryUrl Gets or sets the repository url.
	RepositoryUrl *string `json:"repositoryUrl,omitempty"`

	// SourceUrl Gets or sets the source URL.
	SourceUrl *string `json:"sourceUrl,omitempty"`

	// TargetAbi Gets or sets the ABI that this version was built against.
	TargetAbi *string `json:"targetAbi,omitempty"`

	// Timestamp Gets or sets a timestamp of when the binary was built.
	Timestamp *string `json:"timestamp,omitempty"`

	// Version Gets or sets the version.
	Version *string `json:"version,omitempty"`
}

// Video3DFormat defines model for Video3DFormat.
type Video3DFormat string

// VideoRange An enum representing video ranges.
type VideoRange string

// VideoRangeType An enum representing types of video ranges.
type VideoRangeType string

// VideoType Enum VideoType.
type VideoType string

// VirtualFolderInfo Used to hold information about a user's list of configured virtual folders.
type VirtualFolderInfo struct {
	// CollectionType Gets or sets the type of the collection.
	CollectionType *CollectionTypeOptions `json:"CollectionType,omitempty"`

	// ItemId Gets or sets the item identifier.
	ItemId         *string         `json:"ItemId,omitempty"`
	LibraryOptions *LibraryOptions `json:"LibraryOptions,omitempty"`

	// Locations Gets or sets the locations.
	Locations *[]string `json:"Locations,omitempty"`

	// Name Gets or sets the name.
	Name *string `json:"Name,omitempty"`

	// PrimaryImageItemId Gets or sets the primary image item identifier.
	PrimaryImageItemId *string  `json:"PrimaryImageItemId,omitempty"`
	RefreshProgress    *float64 `json:"RefreshProgress,omitempty"`
	RefreshStatus      *string  `json:"RefreshStatus,omitempty"`
}

// Getter for additional properties for ProblemDetails. Returns the specified
// element and whether it was found
func (a ProblemDetails) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ProblemDetails
func (a *ProblemDetails) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ProblemDetails to handle AdditionalProperties
func (a *ProblemDetails) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["detail"]; found {
		err = json.Unmarshal(raw, &a.Detail)
		if err != nil {
			return fmt.Errorf("error reading 'detail': %w", err)
		}
		delete(object, "detail")
	}

	if raw, found := object["instance"]; found {
		err = json.Unmarshal(raw, &a.Instance)
		if err != nil {
			return fmt.Errorf("error reading 'instance': %w", err)
		}
		delete(object, "instance")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["title"]; found {
		err = json.Unmarshal(raw, &a.Title)
		if err != nil {
			return fmt.Errorf("error reading 'title': %w", err)
		}
		delete(object, "title")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ProblemDetails to handle AdditionalProperties
func (a ProblemDetails) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Detail != nil {
		object["detail"], err = json.Marshal(a.Detail)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'detail': %w", err)
		}
	}

	if a.Instance != nil {
		object["instance"], err = json.Marshal(a.Instance)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'instance': %w", err)
		}
	}

	if a.Status != nil {
		object["status"], err = json.Marshal(a.Status)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'status': %w", err)
		}
	}

	if a.Title != nil {
		object["title"], err = json.Marshal(a.Title)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'title': %w", err)
		}
	}

	if a.Type != nil {
		object["type"], err = json.Marshal(a.Type)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'type': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// GetVirtualFolders Gets all virtual folders.
	//
	// Corresponds with GET /Library/VirtualFolders (the `GetVirtualFolders` operationId).
	GetVirtualFolders(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetSystemInfo Gets information about the server.
	//
	// Corresponds with GET /System/Info (the `GetSystemInfo` operationId).
	GetSystemInfo(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// GetVirtualFolders Gets all virtual folders.
//
// Corresponds with GET /Library/VirtualFolders (the `GetVirtualFolders` operationId).
func (c *Client) GetVirtualFolders(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetVirtualFoldersRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetSystemInfo Gets information about the server.
//
// Corresponds with GET /System/Info (the `GetSystemInfo` operationId).
func (c *Client) GetSystemInfo(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSystemInfoRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetVirtualFoldersRequest constructs an http.Request for the GetVirtualFolders method
func NewGetVirtualFoldersRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/Library/VirtualFolders")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetSystemInfoRequest constructs an http.Request for the GetSystemInfo method
func NewGetSystemInfoRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/System/Info")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// GetVirtualFoldersWithResponse Gets all virtual folders.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /Library/VirtualFolders (the `GetVirtualFolders` operationId).
	GetVirtualFoldersWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetVirtualFoldersResponse, error)

	// GetSystemInfoWithResponse Gets information about the server.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /System/Info (the `GetSystemInfo` operationId).
	GetSystemInfoWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetSystemInfoResponse, error)
}

// GetVirtualFoldersResponse503Headers the declared response headers of an HTTP 503 response for GetVirtualFolders
type GetVirtualFoldersResponse503Headers struct {
	Message    *string
	RetryAfter *int32
}

type GetVirtualFoldersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *[]VirtualFolderInfo
	// ApplicationjsonProfileCamelCase200 the response for an HTTP 200 `application/json; profile="CamelCase"` response
	ApplicationjsonProfileCamelCase200 *[]VirtualFolderInfo
	// ApplicationjsonProfilePascalCase200 the response for an HTTP 200 `application/json; profile="PascalCase"` response
	ApplicationjsonProfilePascalCase200 *[]VirtualFolderInfo
	// Headers503 the parsed response headers for an HTTP 503 response
	Headers503 *GetVirtualFoldersResponse503Headers
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetVirtualFoldersResponse) GetJSON200() *[]VirtualFolderInfo {
	return r.JSON200
}

// GetApplicationjsonProfileCamelCase200 returns the response for an HTTP 200 `application/json; profile="CamelCase"` response
func (r GetVirtualFoldersResponse) GetApplicationjsonProfileCamelCase200() *[]VirtualFolderInfo {
	return r.ApplicationjsonProfileCamelCase200
}

// GetApplicationjsonProfilePascalCase200 returns the response for an HTTP 200 `application/json; profile="PascalCase"` response
func (r GetVirtualFoldersResponse) GetApplicationjsonProfilePascalCase200() *[]VirtualFolderInfo {
	return r.ApplicationjsonProfilePascalCase200
}

// GetBody returns the raw response body bytes
func (r GetVirtualFoldersResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetVirtualFoldersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetVirtualFoldersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetVirtualFoldersResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetSystemInfoResponse503Headers the declared response headers of an HTTP 503 response for GetSystemInfo
type GetSystemInfoResponse503Headers struct {
	Message    *string
	RetryAfter *int32
}

type GetSystemInfoResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *SystemInfo
	// ApplicationjsonProfileCamelCase200 the response for an HTTP 200 `application/json; profile="CamelCase"` response
	ApplicationjsonProfileCamelCase200 *SystemInfo
	// ApplicationjsonProfilePascalCase200 the response for an HTTP 200 `application/json; profile="PascalCase"` response
	ApplicationjsonProfilePascalCase200 *SystemInfo
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *ProblemDetails
	// ApplicationjsonProfileCamelCase403 the response for an HTTP 403 `application/json; profile="CamelCase"` response
	ApplicationjsonProfileCamelCase403 *ProblemDetails
	// ApplicationjsonProfilePascalCase403 the response for an HTTP 403 `application/json; profile="PascalCase"` response
	ApplicationjsonProfilePascalCase403 *ProblemDetails
	// Headers503 the parsed response headers for an HTTP 503 response
	Headers503 *GetSystemInfoResponse503Headers
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetSystemInfoResponse) GetJSON200() *SystemInfo {
	return r.JSON200
}

// GetApplicationjsonProfileCamelCase200 returns the response for an HTTP 200 `application/json; profile="CamelCase"` response
func (r GetSystemInfoResponse) GetApplicationjsonProfileCamelCase200() *SystemInfo {
	return r.ApplicationjsonProfileCamelCase200
}

// GetApplicationjsonProfilePascalCase200 returns the response for an HTTP 200 `application/json; profile="PascalCase"` response
func (r GetSystemInfoResponse) GetApplicationjsonProfilePascalCase200() *SystemInfo {
	return r.ApplicationjsonProfilePascalCase200
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r GetSystemInfoResponse) GetJSON403() *ProblemDetails {
	return r.JSON403
}

// GetApplicationjsonProfileCamelCase403 returns the response for an HTTP 403 `application/json; profile="CamelCase"` response
func (r GetSystemInfoResponse) GetApplicationjsonProfileCamelCase403() *ProblemDetails {
	return r.ApplicationjsonProfileCamelCase403
}

// GetApplicationjsonProfilePascalCase403 returns the response for an HTTP 403 `application/json; profile="PascalCase"` response
func (r GetSystemInfoResponse) GetApplicationjsonProfilePascalCase403() *ProblemDetails {
	return r.ApplicationjsonProfilePascalCase403
}

// GetBody returns the raw response body bytes
func (r GetSystemInfoResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetSystemInfoResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetSystemInfoResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetSystemInfoResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetVirtualFoldersWithResponse Gets all virtual folders.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /Library/VirtualFolders (the `GetVirtualFolders` operationId).
func (c *ClientWithResponses) GetVirtualFoldersWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetVirtualFoldersResponse, error) {
	rsp, err := c.GetVirtualFolders(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetVirtualFoldersResponse(rsp)
}

// GetSystemInfoWithResponse Gets information about the server.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /System/Info (the `GetSystemInfo` operationId).
func (c *ClientWithResponses) GetSystemInfoWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetSystemInfoResponse, error) {
	rsp, err := c.GetSystemInfo(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetSystemInfoResponse(rsp)
}

// ParseGetVirtualFoldersResponse parses an HTTP response from a GetVirtualFoldersWithResponse call
func ParseGetVirtualFoldersResponse(rsp *http.Response) (*GetVirtualFoldersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetVirtualFoldersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.Header.Get("Content-Type") == "application/json" && rsp.StatusCode == 200:
		var dest []VirtualFolderInfo
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case rsp.Header.Get("Content-Type") == "application/json; profile=\"CamelCase\"" && rsp.StatusCode == 200:
		var dest []VirtualFolderInfo
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationjsonProfileCamelCase200 = &dest

	case rsp.Header.Get("Content-Type") == "application/json; profile=\"PascalCase\"" && rsp.StatusCode == 200:
		var dest []VirtualFolderInfo
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationjsonProfilePascalCase200 = &dest

	case rsp.StatusCode == 401:
		break // No content-type

	case rsp.StatusCode == 403:
		break // No content-type

	}

	switch {
	case rsp.StatusCode == 503:
		var headers GetVirtualFoldersResponse503Headers
		if values := rsp.Header.Values("Message"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "Message", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: "text"}); err != nil {
				return nil, err
			}
			headers.Message = &value
		}
		if values := rsp.Header.Values("Retry-After"); len(values) > 0 {
			var value int32
			if err := runtime.BindStyledParameterWithOptions("simple", "Retry-After", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "integer", Format: "int32"}); err != nil {
				return nil, err
			}
			headers.RetryAfter = &value
		}
		response.Headers503 = &headers
	}

	return response, nil
}

// ParseGetSystemInfoResponse parses an HTTP response from a GetSystemInfoWithResponse call
func ParseGetSystemInfoResponse(rsp *http.Response) (*GetSystemInfoResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetSystemInfoResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.Header.Get("Content-Type") == "application/json" && rsp.StatusCode == 200:
		var dest SystemInfo
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case rsp.Header.Get("Content-Type") == "application/json; profile=\"CamelCase\"" && rsp.StatusCode == 200:
		var dest SystemInfo
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationjsonProfileCamelCase200 = &dest

	case rsp.Header.Get("Content-Type") == "application/json; profile=\"PascalCase\"" && rsp.StatusCode == 200:
		var dest SystemInfo
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationjsonProfilePascalCase200 = &dest

	case rsp.StatusCode == 401:
		break // No content-type

	case rsp.Header.Get("Content-Type") == "application/json" && rsp.StatusCode == 403:
		var dest ProblemDetails
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case rsp.Header.Get("Content-Type") == "application/json; profile=\"CamelCase\"" && rsp.StatusCode == 403:
		var dest ProblemDetails
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationjsonProfileCamelCase403 = &dest

	case rsp.Header.Get("Content-Type") == "application/json; profile=\"PascalCase\"" && rsp.StatusCode == 403:
		var dest ProblemDetails
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationjsonProfilePascalCase403 = &dest

	}

	switch {
	case rsp.StatusCode == 503:
		var headers GetSystemInfoResponse503Headers
		if values := rsp.Header.Values("Message"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "Message", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: "text"}); err != nil {
				return nil, err
			}
			headers.Message = &value
		}
		if values := rsp.Header.Values("Retry-After"); len(values) > 0 {
			var value int32
			if err := runtime.BindStyledParameterWithOptions("simple", "Retry-After", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "integer", Format: "int32"}); err != nil {
				return nil, err
			}
			headers.RetryAfter = &value
		}
		response.Headers503 = &headers
	}

	return response, nil
}
